import "server-only";
import { randomUUID, createHash } from "node:crypto";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db/prisma";
import { toPrismaJson } from "@/lib/db/json";
import { audit } from "@/lib/audit/service";
import { requireWorkspaceAccess } from "@/lib/auth/rbac";
import { authorizeMeetingJoin } from "@/lib/meetings/service";
import { buildMeetingRecordingKey, mapLiveKitStatus, queryRoomCompositeRecording, sanitizeProviderError, startRoomCompositeRecording, stopRoomCompositeRecording } from "@/lib/meetings/egress";
import { deleteMeetingRecordingObject } from "@/lib/storage/meeting-recordings";
import type { MeetingRecording, MeetingRecordingEventType } from "@prisma/client";

const activeStatuses = ["CONSENT_REQUIRED","READY","STARTING","RECORDING","STOPPING","PROCESSING"] as const;
export function safeRecordingError(error: unknown, fallback="Recording action failed.") { const msg=error instanceof Error?error.message:String(error||fallback); return /secret|token|credential|authorization|key/i.test(msg)?fallback:msg.slice(0,240); }
async function event(recording: {id:string; workspaceId:string; meetingRoomId:string}, type: MeetingRecordingEventType, metadata: Record<string,unknown>={}, key?: string) { await prisma.meetingRecordingEvent.upsert({ where: { eventKey: key ?? `${recording.id}:${type}:${randomUUID()}` }, update: {}, create: { workspaceId: recording.workspaceId, meetingRoomId: recording.meetingRoomId, recordingId: recording.id, type, eventKey: key, metadata: toPrismaJson(metadata) } }).catch(async()=> prisma.meetingRecordingEvent.create({ data:{ workspaceId:recording.workspaceId, meetingRoomId:recording.meetingRoomId, recordingId:recording.id, type, metadata:toPrismaJson(metadata)}})); }
async function assertHost(workspaceId:string, meetingId:string){ const {user}=await requireWorkspaceAccess(workspaceId); const p=await prisma.meetingParticipant.findFirst({where:{workspaceId,meetingId,userId:user.id}}); const meeting=await prisma.meetingRoom.findFirst({where:{id:meetingId,workspaceId}}); if(!meeting) notFound(); if(meeting.hostId!==user.id && p?.role!=="CO_HOST") throw new Error("Only the host or co-host can manage recording."); return {user,meeting}; }
export async function listMeetingRecordings(workspaceId:string, meetingId:string){ await requireWorkspaceAccess(workspaceId); return prisma.meetingRecording.findMany({ where:{workspaceId,meetingRoomId:meetingId}, include:{requestedBy:true, startedBy:true, stoppedBy:true, consents:true, transcriptionJobs:{orderBy:{createdAt:"desc"},take:1}}, orderBy:{createdAt:"desc"}}); }
export async function requestRecordingConsent(workspaceId:string, meetingId:string){ const {user,meeting}=await assertHost(workspaceId,meetingId); if(meeting.status==="ENDED"||meeting.status==="CANCELED") throw new Error("Ended meetings cannot be recorded."); const duplicate=await prisma.meetingRecording.findFirst({where:{workspaceId,meetingRoomId:meetingId,status:{in:[...activeStatuses]}}}); if(duplicate) return duplicate; const participants=await prisma.meetingParticipant.findMany({where:{workspaceId,meetingId,leftAt:null}}); const recording=await prisma.meetingRecording.create({data:{workspaceId,meetingRoomId:meetingId,requestedById:user.id,status:"CONSENT_REQUIRED",storageKey:buildMeetingRecordingKey(workspaceId,meetingId,"pending")}}); await prisma.meetingRecording.update({where:{id:recording.id},data:{storageKey:buildMeetingRecordingKey(workspaceId,meetingId,recording.id),bucketName:process.env.MEETING_RECORDINGS_R2_BUCKET,fileName:"recording.mp4",mimeType:"video/mp4"}});
 await prisma.meetingRecordingConsent.createMany({data:participants.map(p=>({workspaceId,meetingRoomId:meetingId,recordingId:recording.id,meetingParticipantId:p.id,userId:p.userId,livekitIdentity:p.identity,displayName:p.displayName,consentStatus:"PENDING"})), skipDuplicates:true}); await event(recording,"CONSENT_REQUESTED",{participantCount:participants.length},`consent-requested:${recording.id}`); await audit(workspaceId,"meeting.recording_consent_requested","MeetingRecording",recording.id,user.id,{meetingId,participantCount:participants.length}); return recording; }
export async function getActiveRecordingForParticipant(meetingId:string, identity:string){ return prisma.meetingRecording.findFirst({where:{meetingRoomId:meetingId,status:{in:[...activeStatuses,"AVAILABLE"]}}, include:{consents:{where:{livekitIdentity:identity}}}, orderBy:{createdAt:"desc"}}); }

function publicRecording(recording: MeetingRecording | null) {
  if (!recording) return null;
  return { id: recording.id, status: recording.status, transcriptionStatus: recording.transcriptionStatus, startedAt: recording.startedAt, stoppedAt: recording.stoppedAt, completedAt: recording.completedAt, safeFailureMessage: recording.safeFailureMessage };
}

export async function ensureParticipantConsentRow(recordingId:string, participant:{id:string; userId:string|null; identity:string; displayName:string}, meeting:{id:string; workspaceId:string}) {
  const recording = await prisma.meetingRecording.findFirst({ where: { id: recordingId, workspaceId: meeting.workspaceId, meetingRoomId: meeting.id } });
  if (!recording) notFound();
  return prisma.meetingRecordingConsent.upsert({
    where: { recordingId_livekitIdentity: { recordingId, livekitIdentity: participant.identity } },
    update: { displayName: participant.displayName, meetingParticipantId: participant.id, userId: participant.userId },
    create: { workspaceId: meeting.workspaceId, meetingRoomId: meeting.id, recordingId, meetingParticipantId: participant.id, userId: participant.userId, livekitIdentity: participant.identity, displayName: participant.displayName, consentStatus: "PENDING" }
  });
}

export async function assertRecordingConsentForToken(meeting:{id:string; workspaceId:string}, participant:{id:string; userId:string|null; identity:string; displayName:string}, actorId?:string) {
  const recording = await prisma.meetingRecording.findFirst({ where: { workspaceId: meeting.workspaceId, meetingRoomId: meeting.id, status: { in: ["CONSENT_REQUIRED", "READY", "STARTING"] } }, include: { consents: { where: { livekitIdentity: participant.identity } } }, orderBy: { createdAt: "desc" } });
  if (!recording) return;
  const consent = recording.consents[0] ?? await ensureParticipantConsentRow(recording.id, participant, meeting);
  if (consent.consentStatus === "CONSENTED") { await promoteReady(recording.id); return; }
  await audit(meeting.workspaceId, "meeting.recording_token_denied_consent_missing", "MeetingRecording", recording.id, actorId, { meetingId: meeting.id, participantId: participant.id, consentStatus: consent.consentStatus });
  if (consent.consentStatus === "DECLINED") throw new Error("You declined recording consent and cannot join this recorded session.");
  if (consent.consentStatus === "REVOKED") throw new Error("Your recording consent is no longer active.");
  throw new Error("Recording consent is required before joining.");
}

export async function getRecordingRoomStatus(authorization: Awaited<ReturnType<typeof authorizeMeetingJoin>>) {
  const { meeting, participant } = authorization;
  const recording = await prisma.meetingRecording.findFirst({ where: { workspaceId: meeting.workspaceId, meetingRoomId: meeting.id, status: { in: [...activeStatuses, "AVAILABLE", "FAILED"] } }, include: { consents: { orderBy: { displayName: "asc" } } }, orderBy: { createdAt: "desc" } });
  const isHost = participant.role === "HOST" || participant.role === "CO_HOST";
  const consent = recording ? (recording.consents.find(c => c.livekitIdentity === participant.identity) ?? await ensureParticipantConsentRow(recording.id, participant, meeting)) : null;
  const participants = recording?.consents.map(c => ({ displayName: c.displayName, role: c.meetingParticipantId === participant.id ? participant.role : "PARTICIPANT", status: c.consentStatus })) ?? [];
  const counts = (status:string) => participants.filter(p => p.status === status).length;
  const required = Boolean(recording && ["CONSENT_REQUIRED", "READY", "STARTING"].includes(recording.status));
  return { meetingStatus: meeting.status, recording: publicRecording(recording), currentParticipantConsent: consent ? { status: consent.consentStatus, respondedAt: consent.respondedAt } : null, consentSummary: { required, consented: counts("CONSENTED"), pending: counts("PENDING"), declined: counts("DECLINED"), revoked: counts("REVOKED"), participants }, permissions: { canRequestConsent: isHost && !recording, canStartRecording: isHost && recording?.status === "READY", canStopRecording: isHost && recording?.status === "RECORDING", canRefreshRecording: isHost && Boolean(recording && ["STARTING","STOPPING","PROCESSING","FAILED"].includes(recording.status)) } };
}
export async function respondToRecordingConsent(meetingId:string,input:{invitationToken?:string; displayName?:string; recordingId:string; consent:boolean}){ const auth=await authorizeMeetingJoin({meetingId,invitationToken:input.invitationToken,displayName:input.displayName}); const {meeting,participant,actorId}=auth; const recording=await prisma.meetingRecording.findFirst({where:{id:input.recordingId,workspaceId:meeting.workspaceId,meetingRoomId:meeting.id}}); if(!recording) notFound(); const status=input.consent?"CONSENTED":"DECLINED"; const consent=await prisma.meetingRecordingConsent.upsert({where:{recordingId_livekitIdentity:{recordingId:recording.id,livekitIdentity:participant.identity}},update:{consentStatus:status,respondedAt:new Date(),revokedAt:null,displayName:participant.displayName,meetingParticipantId:participant.id,userId:participant.userId},create:{workspaceId:meeting.workspaceId,meetingRoomId:meeting.id,recordingId:recording.id,meetingParticipantId:participant.id,userId:participant.userId,livekitIdentity:participant.identity,displayName:participant.displayName,consentStatus:status,respondedAt:new Date()}}); await event(recording,input.consent?"CONSENT_GRANTED":"CONSENT_DECLINED",{displayName:participant.displayName},`${recording.id}:${participant.identity}:${status}`); if(!input.consent) await prisma.meetingRecording.update({where:{id:recording.id},data:{status:"CONSENT_REQUIRED",safeFailureMessage:"A participant declined recording consent."}}); else await promoteReady(recording.id); await audit(meeting.workspaceId,input.consent?"meeting.recording_consent_granted":"meeting.recording_consent_declined","MeetingRecording",recording.id,actorId,{meetingId:meeting.id,role:participant.role,displayName:participant.displayName}); return consent; }
export async function revokeRecordingConsent(meetingId:string,input:{invitationToken?:string; displayName?:string; recordingId:string}){ const auth=await authorizeMeetingJoin({meetingId,invitationToken:input.invitationToken,displayName:input.displayName}); const {meeting,participant,actorId}=auth; const recording=await prisma.meetingRecording.findFirst({where:{id:input.recordingId,workspaceId:meeting.workspaceId,meetingRoomId:meeting.id}}); if(!recording) notFound(); await prisma.meetingRecordingConsent.updateMany({where:{recordingId:recording.id,livekitIdentity:participant.identity},data:{consentStatus:"REVOKED",revokedAt:new Date()}}); await event(recording,"CONSENT_REVOKED",{displayName:participant.displayName}); await audit(meeting.workspaceId,"meeting.recording_consent_revoked","MeetingRecording",recording.id,actorId,{meetingId:meeting.id}); if(recording.status==="RECORDING") await stopRecording(meeting.workspaceId,meeting.id,recording.id,true); }
async function promoteReady(recordingId:string){ const rec=await prisma.meetingRecording.findUnique({where:{id:recordingId},include:{consents:true}}); if(rec && rec.consents.length>0 && rec.consents.every(c=>c.consentStatus==="CONSENTED")) await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"READY",safeFailureMessage:null}}); }
export async function startRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user,meeting}=await assertHost(workspaceId,meetingId); const recording=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{consents:true}}); if(!recording) notFound(); if(recording.status==="RECORDING") return recording; if(recording.status!=="READY") throw new Error("Recording cannot start until every required participant has consented."); if(recording.consents.length===0||recording.consents.some(c=>c.consentStatus!=="CONSENTED")) throw new Error("Recording cannot start until every required participant has consented."); const active=await prisma.meetingRecording.count({where:{workspaceId,meetingRoomId:meetingId,status:{in:["STARTING","RECORDING","STOPPING","PROCESSING"]},id:{not:recordingId}}}); if(active) throw new Error("Another recording is already active for this meeting."); await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"STARTING",startedById:user.id}}); await event(recording,"RECORDING_START_REQUESTED",{},`start-requested:${recording.id}`); try{ const result=await startRoomCompositeRecording({workspaceId,meetingId,recordingId,roomName:meeting.roomName}); const updated=await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"RECORDING",providerEgressId:result.egressId,storageKey:result.storageKey,bucketName:result.bucketName,fileName:result.fileName,mimeType:result.mimeType,startedAt:new Date(),startedById:user.id}}); await event(updated,"RECORDING_STARTED",{status:"RECORDING"},`started:${result.egressId}`); await audit(workspaceId,"meeting.recording_started","MeetingRecording",recordingId,user.id,{meetingId,status:"RECORDING"}); return updated;}catch(e){ const msg=sanitizeProviderError(e); const failed=await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"FAILED",failedAt:new Date(),failureCode:"EGRESS_START_FAILED",safeFailureMessage:msg}}); await event(failed,"RECORDING_FAILED",{failureCode:"EGRESS_START_FAILED"}); throw new Error(msg);} }
export async function stopRecording(workspaceId:string, meetingId:string, recordingId:string, system=false){ const {user}=system?{user:{id:undefined as string|undefined}}:await assertHost(workspaceId,meetingId); const recording=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId}}); if(!recording) notFound(); if(["STOPPING","PROCESSING","AVAILABLE","FAILED","CANCELLED"].includes(recording.status)) return recording; await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"STOPPING",stoppedAt:new Date(),stoppedById:user.id}}); await event(recording,"RECORDING_STOP_REQUESTED",{},`stop-requested:${recording.id}`); if(recording.providerEgressId) await stopRoomCompositeRecording(recording.providerEgressId).catch(async e=>{ await prisma.meetingRecording.update({where:{id:recordingId},data:{safeFailureMessage:sanitizeProviderError(e)}}); }); await audit(workspaceId,"meeting.recording_stop_requested","MeetingRecording",recordingId,user.id,{meetingId}); return prisma.meetingRecording.update({where:{id:recordingId},data:{status:"PROCESSING"}}); }
export async function reconcileRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user}=await assertHost(workspaceId,meetingId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId}}); if(!r) notFound(); if(!r.providerEgressId) return r; const provider=await queryRoomCompositeRecording(r.providerEgressId); const status=mapLiveKitStatus(JSON.stringify(provider)); const updated=await prisma.meetingRecording.update({where:{id:r.id},data:{status: r.status==="AVAILABLE"?"AVAILABLE":status}}); await audit(workspaceId,"meeting.recording_status_refreshed","MeetingRecording",r.id,user.id,{meetingId,status:updated.status}); return updated; }
export async function markWebhookRecordingAvailable(providerEgressId:string, metadata:Record<string,unknown>, eventKey:string){ const r=await prisma.meetingRecording.findUnique({where:{providerEgressId}}); if(!r) return null; if(r.status==="AVAILABLE") return r; const updated=await prisma.meetingRecording.update({where:{id:r.id},data:{status:"AVAILABLE",completedAt:new Date(),transcriptionStatus:"QUEUED",fileSizeBytes: typeof metadata.sizeBytes==="number"?BigInt(metadata.sizeBytes):undefined,durationSeconds: typeof metadata.durationSeconds==="number"?metadata.durationSeconds:undefined}}); await event(updated,"RECORDING_AVAILABLE",metadata,eventKey); await prisma.meetingTranscriptionJob.upsert({where:{id:createHash("sha256").update(`transcription:${r.id}`).digest("hex").slice(0,24)},update:{},create:{id:createHash("sha256").update(`transcription:${r.id}`).digest("hex").slice(0,24),workspaceId:r.workspaceId,meetingRoomId:r.meetingRoomId,recordingId:r.id,status:"QUEUED"}}); await audit(r.workspaceId,"meeting.recording_finalized","MeetingRecording",r.id,undefined,{meetingId:r.meetingRoomId}); return updated; }
export async function deleteRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user}=await assertHost(workspaceId,meetingId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId}}); if(!r) notFound(); if(["STARTING","RECORDING","STOPPING","PROCESSING"].includes(r.status)) throw new Error("Active or processing recordings cannot be deleted."); if(r.transcriptApprovedAt || r.callSessionId) throw new Error("Approved or handed-off recordings must preserve source history."); if(r.storageKey) await deleteMeetingRecordingObject(r.storageKey); await prisma.meetingRecording.update({where:{id:r.id},data:{status:"DELETED"}}); await audit(workspaceId,"meeting.recording_deleted","MeetingRecording",r.id,user.id,{meetingId}); return r; }
