import { randomUUID } from "node:crypto";
import type { MeetingProviderArtifact } from "@prisma/client";
export const MAX_UPLOAD_BYTES=BigInt(process.env.MEETING_RECORDING_MAX_UPLOAD_BYTES||"5368709120");
const types:Record<string,string[]>={"video/mp4":[".mp4"],"video/webm":[".webm"],"video/quicktime":[".mov"],"audio/mp4":[".m4a",".mp4"],"audio/m4a":[".m4a"],"audio/mpeg":[".mp3"],"audio/wav":[".wav"],"audio/x-wav":[".wav"],"audio/webm":[".webm"]};
export function safeFileName(n:string){return (n.split(/[\\/]/).pop()||"recording").replace(/[^a-zA-Z0-9._-]+/g,"-").slice(0,120)||"recording"}
export function validateRecordingFile(name:string,mime:string,size:bigint){ const lower=safeFileName(name).toLowerCase(); if(size<=BigInt(0)) throw new Error("Recording file is empty."); if(size>MAX_UPLOAD_BYTES) throw new Error("Recording file is larger than the configured upload limit."); const ok=types[mime]?.some(ext=>lower.endsWith(ext)); if(!ok) throw new Error("Unsupported recording file type. Upload MP4, M4A, MP3, WAV, WebM, or MOV."); }
export function recordingObjectKey(workspaceId:string,meetingId:string,recordingId:string,source:"local"|"zoom",fileName:string,artifactId?:string){return `workspaces/${workspaceId}/meetings/${meetingId}/recordings/${recordingId}/${source}/${artifactId?`${artifactId}/`:""}${randomUUID()}-${safeFileName(fileName)}`}
export function mimeFromZoomFileType(fileType?:string){ const f=(fileType||"").toUpperCase(); if(f==="MP4") return "video/mp4"; if(f==="M4A") return "audio/mp4"; if(f==="MP3") return "audio/mpeg"; if(f==="WAV") return "audio/wav"; if(f==="WEBM") return "video/webm"; if(f==="VTT") return "text/vtt"; if(f==="TXT") return "text/plain"; return "application/octet-stream"; }
export function isTranscriptArtifact(a:Pick<MeetingProviderArtifact,"fileType"|"recordingType"|"mimeType">){return [a.fileType,a.recordingType,a.mimeType].some(v=>String(v||"").toLowerCase().includes("transcript")||String(v||"").toLowerCase().includes("vtt"))}
