import "server-only";
import { randomUUID, createHash } from "node:crypto";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db/prisma";
import { toPrismaJson } from "@/lib/db/json";
import { audit } from "@/lib/audit/service";
import { requireWorkspaceAccess } from "@/lib/auth/rbac";
import { authorizeMeetingJoin } from "@/lib/meetings/service";
import { buildMeetingRecordingKey, buildMeetingRecordingSegmentKey, parseLiveKitEgress, queryRoomCompositeRecording, sanitizeProviderError, startRoomCompositeRecording, stopRoomCompositeRecording } from "@/lib/meetings/egress";
import { deleteMeetingRecordingObject } from "@/lib/storage/meeting-recordings";
import type { MeetingRecording, MeetingRecordingEventType } from "@prisma/client";

const activeStatuses = ["CONSENT_REQUIRED","READY","STARTING","RECORDING","PAUSING","PAUSED","RESUMING","STOPPING","PROCESSING"] as const;
const recordingPriority = ["RECORDING","STARTING","PAUSING","PAUSED","RESUMING","STOPPING","PROCESSING","CONSENT_REQUIRED","READY"] as const;
export function safeRecordingError(error: unknown, fallback="Recording action failed.") { const msg=error instanceof Error?error.message:String(error||fallback); return /secret|token|credential|authorization|key/i.test(msg)?fallback:msg.slice(0,240); }
async function event(recording: {id:string; workspaceId:string; meetingRoomId:string}, type: MeetingRecordingEventType, metadata: Record<string,unknown>={}, key?: string) { await prisma.meetingRecordingEvent.upsert({ where: { eventKey: key ?? `${recording.id}:${type}:${randomUUID()}` }, update: {}, create: { workspaceId: recording.workspaceId, meetingRoomId: recording.meetingRoomId, recordingId: recording.id, type, eventKey: key, metadata: toPrismaJson(metadata) } }).catch(async()=> prisma.meetingRecordingEvent.create({ data:{ workspaceId:recording.workspaceId, meetingRoomId:recording.meetingRoomId, recordingId:recording.id, type, metadata:toPrismaJson(metadata)}})); }
async function assertHost(workspaceId:string, meetingId:string){ const {user}=await requireWorkspaceAccess(workspaceId); const p=await prisma.meetingParticipant.findFirst({where:{workspaceId,meetingId,userId:user.id}}); const meeting=await prisma.meetingRoom.findFirst({where:{id:meetingId,workspaceId}}); if(!meeting) notFound(); if(meeting.hostId!==user.id && p?.role!=="CO_HOST") throw new Error("Only the host or co-host can manage recording."); return {user,meeting}; }
async function resolveMeetingWorkspace(meetingId:string){ const meeting=await prisma.meetingRoom.findUnique({where:{id:meetingId},select:{workspaceId:true}}); if(!meeting) notFound(); return meeting.workspaceId; }
export async function listMeetingRecordings(workspaceId:string, meetingId:string){ await requireWorkspaceAccess(workspaceId); return prisma.meetingRecording.findMany({ where:{workspaceId,meetingRoomId:meetingId}, include:{requestedBy:true, startedBy:true, stoppedBy:true, consents:true, segments:{orderBy:{segmentNumber:"asc"}}, transcriptionJobs:{orderBy:{createdAt:"desc"},take:1}}, orderBy:{createdAt:"desc"}}); }
export async function requestRecordingConsent(workspaceId:string, meetingId:string){ const {user,meeting}=await assertHost(workspaceId,meetingId); if(meeting.status==="ENDED"||meeting.status==="CANCELED") throw new Error("Ended meetings cannot be recorded."); const duplicate=await prisma.meetingRecording.findFirst({where:{workspaceId,meetingRoomId:meetingId,status:{in:[...activeStatuses]}}}); if(duplicate) return duplicate; const participants=await prisma.meetingParticipant.findMany({where:{workspaceId,meetingId,leftAt:null}}); const recording=await prisma.meetingRecording.create({data:{workspaceId,meetingRoomId:meetingId,requestedById:user.id,status:"CONSENT_REQUIRED",storageKey:buildMeetingRecordingKey(workspaceId,meetingId,"pending")}}); await prisma.meetingRecording.update({where:{id:recording.id},data:{storageKey:buildMeetingRecordingKey(workspaceId,meetingId,recording.id),bucketName:process.env.MEETING_RECORDINGS_R2_BUCKET,fileName:"recording.mp4",mimeType:"video/mp4"}});
 await prisma.meetingRecordingConsent.createMany({data:participants.map(p=>({workspaceId,meetingRoomId:meetingId,recordingId:recording.id,meetingParticipantId:p.id,userId:p.userId,livekitIdentity:p.identity,displayName:p.displayName,consentStatus:"PENDING"})), skipDuplicates:true}); await event(recording,"CONSENT_REQUESTED",{participantCount:participants.length},`consent-requested:${recording.id}`); await audit(workspaceId,"meeting.recording_consent_requested","MeetingRecording",recording.id,user.id,{meetingId,participantCount:participants.length}); return recording; }
export async function getActiveRecordingForParticipant(meetingId:string, identity:string){ return prisma.meetingRecording.findFirst({where:{meetingRoomId:meetingId,status:{in:[...activeStatuses,"AVAILABLE"]}}, include:{consents:{where:{livekitIdentity:identity}}}, orderBy:{createdAt:"desc"}}); }

async function selectRoomRecording(workspaceId:string, meetingId:string) {
  const recordings = await prisma.meetingRecording.findMany({ where: { workspaceId, meetingRoomId: meetingId, status: { in: [...activeStatuses, "AVAILABLE", "FAILED"] } }, include: { consents: { orderBy: { displayName: "asc" } }, segments: { orderBy: { segmentNumber: "asc" } } }, orderBy: { createdAt: "desc" } });
  return recordings.find(r => recordingPriority.includes(r.status as typeof recordingPriority[number])) ?? recordings[0] ?? null;
}

function durationFromSegments(recording: (MeetingRecording & { segments?: { status:string; durationSeconds:number|null; startedAt:Date|null }[] }) | null) {
  if (!recording) return { recordedDurationSeconds: 0, activeSegmentStartedAt: null as Date | null };
  const segments = recording.segments ?? [];
  const completed = segments.filter(s => ["AVAILABLE","STOPPING","PROCESSING"].includes(s.status)).reduce((total, s) => total + (s.durationSeconds ?? 0), 0);
  const active = segments.find(s => s.status === "RECORDING" && s.startedAt);
  return { recordedDurationSeconds: completed, activeSegmentStartedAt: active?.startedAt ?? null };
}

function publicRecording(recording: (MeetingRecording & { segments?: { id:string; segmentNumber:number; status:string; startedAt:Date|null; stoppedAt?:Date|null; completedAt?:Date|null; durationSeconds:number|null; fileSizeBytes?:bigint|null }[] }) | null) {
  if (!recording) return null;
  const timing = durationFromSegments(recording);
  return { id: recording.id, status: recording.status, recordingStatus: recording.status, transcriptionStatus: recording.transcriptionStatus, startedAt: recording.startedAt, stoppedAt: recording.stoppedAt, completedAt: recording.completedAt, safeFailureMessage: recording.safeFailureMessage, ...timing, segments: recording.segments?.map(s => ({ id:s.id, segmentNumber:s.segmentNumber, status:s.status, startedAt:s.startedAt, stoppedAt:s.stoppedAt, completedAt:s.completedAt, durationSeconds:s.durationSeconds, fileSizeBytes:s.fileSizeBytes ? Number(s.fileSizeBytes) : null, downloadAvailable:s.status === "AVAILABLE" })) ?? [] };
}

export async function ensureParticipantConsentRow(recordingId:string, participant:{id:string; userId:string|null; identity:string; displayName:string}, meeting:{id:string; workspaceId:string}) {
  const recording = await prisma.meetingRecording.findFirst({ where: { id: recordingId, workspaceId: meeting.workspaceId, meetingRoomId: meeting.id } });
  if (!recording) notFound();
  return prisma.meetingRecordingConsent.upsert({
    where: { recordingId_livekitIdentity: { recordingId, livekitIdentity: participant.identity } },
    update: { displayName: participant.displayName, meetingParticipantId: participant.id, userId: participant.userId },
    create: { workspaceId: meeting.workspaceId, meetingRoomId: meeting.id, recordingId, meetingParticipantId: participant.id, userId: participant.userId, livekitIdentity: participant.identity, displayName: participant.displayName, consentStatus: "PENDING" }
  });
}

export async function assertRecordingConsentForToken(meeting:{id:string; workspaceId:string}, participant:{id:string; userId:string|null; identity:string; displayName:string}, actorId?:string) {
  const recording = await prisma.meetingRecording.findFirst({ where: { workspaceId: meeting.workspaceId, meetingRoomId: meeting.id, status: { in: ["CONSENT_REQUIRED", "READY", "STARTING"] } }, include: { consents: { where: { livekitIdentity: participant.identity } } }, orderBy: { createdAt: "desc" } });
  if (!recording) return;
  const consent = recording.consents[0] ?? await ensureParticipantConsentRow(recording.id, participant, meeting);
  if (consent.consentStatus === "CONSENTED") { await promoteReady(recording.id); return; }
  await audit(meeting.workspaceId, "meeting.recording_token_denied_consent_missing", "MeetingRecording", recording.id, actorId, { meetingId: meeting.id, participantId: participant.id, consentStatus: consent.consentStatus });
  if (consent.consentStatus === "DECLINED") throw new Error("You declined recording consent and cannot join this recorded session.");
  if (consent.consentStatus === "REVOKED") throw new Error("Your recording consent is no longer active.");
  throw new Error("Recording consent is required before joining.");
}

export async function getRecordingRoomStatus(authorization: Awaited<ReturnType<typeof authorizeMeetingJoin>>) {
  const { meeting, participant } = authorization;
  const recording = await selectRoomRecording(meeting.workspaceId, meeting.id);
  const isHost = participant.role === "HOST" || participant.role === "CO_HOST";
  const consent = recording ? (recording.consents.find(c => c.livekitIdentity === participant.identity) ?? await ensureParticipantConsentRow(recording.id, participant, meeting)) : null;
  const participants = recording?.consents.map(c => ({ displayName: c.displayName, role: c.meetingParticipantId === participant.id ? participant.role : "PARTICIPANT", status: c.consentStatus })) ?? [];
  const counts = (status:string) => participants.filter(p => p.status === status).length;
  const required = Boolean(recording && ["CONSENT_REQUIRED", "READY", "STARTING", "PAUSED"].includes(recording.status));
  return { meetingStatus: meeting.status, recording: publicRecording(recording), activeRecording: publicRecording(recording && activeStatuses.includes(recording.status as typeof activeStatuses[number]) ? recording : null), latestCompletedRecording: publicRecording(recording && ["AVAILABLE","FAILED"].includes(recording.status) ? recording : null), currentParticipantConsent: consent ? { status: consent.consentStatus, respondedAt: consent.respondedAt } : null, consentSummary: { required, consented: counts("CONSENTED"), pending: counts("PENDING"), declined: counts("DECLINED"), revoked: counts("REVOKED"), participants }, permissions: { canRequestConsent: isHost && !recording, canStartRecording: isHost && recording?.status === "READY", canPauseRecording: isHost && recording?.status === "RECORDING", canResumeRecording: isHost && recording?.status === "PAUSED", canStopRecording: isHost && Boolean(recording && ["STARTING","RECORDING","PAUSED","RESUMING"].includes(recording.status)), canRefreshRecording: isHost && Boolean(recording && ["STARTING","PAUSING","PAUSED","RESUMING","STOPPING","PROCESSING","FAILED"].includes(recording.status)) } };
}
export async function respondToRecordingConsent(meetingId:string,input:{invitationToken?:string; displayName?:string; recordingId:string; consent:boolean}){ const auth=await authorizeMeetingJoin({meetingId,invitationToken:input.invitationToken,displayName:input.displayName}); const {meeting,participant,actorId}=auth; const recording=await prisma.meetingRecording.findFirst({where:{id:input.recordingId,workspaceId:meeting.workspaceId,meetingRoomId:meeting.id}}); if(!recording) notFound(); const status=input.consent?"CONSENTED":"DECLINED"; const consent=await prisma.meetingRecordingConsent.upsert({where:{recordingId_livekitIdentity:{recordingId:recording.id,livekitIdentity:participant.identity}},update:{consentStatus:status,respondedAt:new Date(),revokedAt:null,displayName:participant.displayName,meetingParticipantId:participant.id,userId:participant.userId},create:{workspaceId:meeting.workspaceId,meetingRoomId:meeting.id,recordingId:recording.id,meetingParticipantId:participant.id,userId:participant.userId,livekitIdentity:participant.identity,displayName:participant.displayName,consentStatus:status,respondedAt:new Date()}}); await event(recording,input.consent?"CONSENT_GRANTED":"CONSENT_DECLINED",{displayName:participant.displayName},`${recording.id}:${participant.identity}:${status}`); if(!input.consent) await prisma.meetingRecording.update({where:{id:recording.id},data:{status:"CONSENT_REQUIRED",safeFailureMessage:"A participant declined recording consent."}}); else await promoteReady(recording.id); await audit(meeting.workspaceId,input.consent?"meeting.recording_consent_granted":"meeting.recording_consent_declined","MeetingRecording",recording.id,actorId,{meetingId:meeting.id,role:participant.role,displayName:participant.displayName}); return consent; }
export async function revokeRecordingConsent(meetingId:string,input:{invitationToken?:string; displayName?:string; recordingId:string}){ const auth=await authorizeMeetingJoin({meetingId,invitationToken:input.invitationToken,displayName:input.displayName}); const {meeting,participant,actorId}=auth; const recording=await prisma.meetingRecording.findFirst({where:{id:input.recordingId,workspaceId:meeting.workspaceId,meetingRoomId:meeting.id}}); if(!recording) notFound(); await prisma.meetingRecordingConsent.updateMany({where:{recordingId:recording.id,livekitIdentity:participant.identity},data:{consentStatus:"REVOKED",revokedAt:new Date()}}); await event(recording,"CONSENT_REVOKED",{displayName:participant.displayName}); await audit(meeting.workspaceId,"meeting.recording_consent_revoked","MeetingRecording",recording.id,actorId,{meetingId:meeting.id}); if(recording.status==="RECORDING") await stopRecording(meeting.workspaceId,meeting.id,recording.id,true); }
async function promoteReady(recordingId:string){ const rec=await prisma.meetingRecording.findUnique({where:{id:recordingId},include:{consents:true}}); if(rec && rec.consents.length>0 && rec.consents.every(c=>c.consentStatus==="CONSENTED")) await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"READY",safeFailureMessage:null}}); }
export async function startRecordingForMeeting(meetingId:string, recordingId:string){ return startRecording(await resolveMeetingWorkspace(meetingId), meetingId, recordingId); }
async function createSegment(workspaceId:string, meetingId:string, recordingId:string, segmentNumber:number) { return prisma.meetingRecordingSegment.create({data:{workspaceId,meetingRoomId:meetingId,recordingId,segmentNumber,status:"STARTING",storageKey:buildMeetingRecordingSegmentKey(workspaceId,meetingId,recordingId,segmentNumber),bucketName:process.env.MEETING_RECORDINGS_R2_BUCKET,fileName:`recording-part-${segmentNumber}.mp4`,mimeType:"video/mp4"}}); }
const segmentActiveStatuses=["STARTING","RECORDING","STOPPING","PROCESSING"];
const segmentTerminalStatuses=["AVAILABLE","FAILED","CANCELLED"];
function segmentTotal(segments:{durationSeconds:number|null}[]){ return segments.reduce((sum,s)=>sum+(s.durationSeconds??0),0); }
async function ensureLegacySegment(r:{id:string;workspaceId:string;meetingRoomId:string;providerEgressId:string|null;storageKey:string|null;bucketName:string|null;fileName:string|null;mimeType:string|null;status:string;startedAt:Date|null;stoppedAt:Date|null;completedAt:Date|null;durationSeconds:number|null;fileSizeBytes:bigint|null;segments:{id:string}[]}){ if(r.segments.length||!r.providerEgressId) return null; return prisma.meetingRecordingSegment.create({data:{workspaceId:r.workspaceId,meetingRoomId:r.meetingRoomId,recordingId:r.id,segmentNumber:1,providerEgressId:r.providerEgressId,storageKey:r.storageKey,bucketName:r.bucketName,fileName:r.fileName??"recording.mp4",mimeType:r.mimeType??"video/mp4",status:r.status==="AVAILABLE"?"AVAILABLE":r.status==="FAILED"?"FAILED":r.status==="RECORDING"?"RECORDING":"PROCESSING",startedAt:r.startedAt,stoppedAt:r.stoppedAt,completedAt:r.completedAt,durationSeconds:r.durationSeconds,fileSizeBytes:r.fileSizeBytes}}).catch(()=>null); }
async function startSegment(workspaceId:string, meetingId:string, recordingId:string, roomName:string, segmentNumber:number, actorId?:string){ const segment=await createSegment(workspaceId,meetingId,recordingId,segmentNumber); try{ const result=await startRoomCompositeRecording({workspaceId,meetingId,recordingId,roomName,segmentNumber}); await prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{providerEgressId:result.egressId,storageKey:result.storageKey,bucketName:result.bucketName,fileName:result.fileName,mimeType:result.mimeType}}); await event({id:recordingId,workspaceId,meetingRoomId:meetingId},"RECORDING_SEGMENT_STARTED",{segmentId:segment.id,segmentNumber},`segment-started:${result.egressId}`); await audit(workspaceId,"meeting.recording_segment_started","MeetingRecording",recordingId,actorId,{meetingId,segmentId:segment.id,segmentNumber}); return {result,segment}; }catch(e){ const msg=sanitizeProviderError(e); await prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{status:"FAILED",completedAt:new Date(),safeFailureMessage:msg}}).catch(()=>undefined); throw e; } }
export async function startRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user,meeting}=await assertHost(workspaceId,meetingId); const recording=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{consents:true,segments:true}}); if(!recording) notFound(); if(["STARTING","RECORDING"].includes(recording.status)&&recording.segments.some(s=>segmentActiveStatuses.includes(s.status))) return recording; if(recording.status!=="READY") throw new Error("Recording cannot start until every required participant has consented."); if(recording.consents.length===0||recording.consents.some(c=>c.consentStatus!=="CONSENTED")) throw new Error("Recording cannot start until every required participant has consented."); const active=await prisma.meetingRecording.count({where:{workspaceId,meetingRoomId:meetingId,status:{in:["STARTING","RECORDING","PAUSING","PAUSED","RESUMING","STOPPING","PROCESSING"]},id:{not:recordingId}}}); if(active) throw new Error("Another recording is already active for this meeting."); if(recording.segments.some(s=>segmentActiveStatuses.includes(s.status))) throw new Error("A recording segment is already active."); await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"STARTING",startedById:user.id,safeFailureMessage:null}}); await event(recording,"RECORDING_START_REQUESTED",{},`start-requested:${recording.id}:${Date.now()}`); await audit(workspaceId,"meeting.recording_start_requested","MeetingRecording",recordingId,user.id,{meetingId,retry:Boolean(recording.safeFailureMessage)}); try{ const {result}=await startSegment(workspaceId,meetingId,recordingId,meeting.roomName,1,user.id); const updated=await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"STARTING",startedById:user.id}}); await event(updated,"RECORDING_STARTED",{status:"STARTING"},`started:${result.egressId}`); return updated;}catch(e){ const msg=sanitizeProviderError(e); const failed=await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"FAILED",failedAt:new Date(),failureCode:"EGRESS_START_FAILED",safeFailureMessage:msg}}); await event(failed,"RECORDING_FAILED",{failureCode:"EGRESS_START_FAILED"}); throw new Error(msg);} }
export async function pauseRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user}=await assertHost(workspaceId,meetingId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{segments:{orderBy:{segmentNumber:"desc"}}}}); if(!r) notFound(); if(r.status==="PAUSING"||r.status==="PAUSED") return r; if(r.status!=="RECORDING") throw new Error("Only an active recording can be paused."); const segment=r.segments.find(s=>["RECORDING","STARTING"].includes(s.status)&&s.providerEgressId); if(!segment?.providerEgressId) throw new Error("No active recording segment is available to pause."); await prisma.$transaction([prisma.meetingRecording.update({where:{id:r.id},data:{status:"PAUSING"}}),prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{status:"STOPPING",stoppedAt:new Date()}})]); await event(r,"RECORDING_PAUSE_REQUESTED",{segmentId:segment.id,segmentNumber:segment.segmentNumber},`pause-requested:${r.id}:${segment.segmentNumber}`); await audit(workspaceId,"meeting.recording_pause_requested","MeetingRecording",r.id,user.id,{meetingId,segmentId:segment.id,segmentNumber:segment.segmentNumber}); await stopRoomCompositeRecording(segment.providerEgressId).catch(async e=>{ await prisma.meetingRecording.update({where:{id:r.id},data:{safeFailureMessage:sanitizeProviderError(e)}}); }); return prisma.meetingRecording.findUniqueOrThrow({where:{id:r.id}}); }
export async function resumeRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user,meeting}=await assertHost(workspaceId,meetingId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{consents:true,segments:{orderBy:{segmentNumber:"desc"}}}}); if(!r) notFound(); if(r.status==="RECORDING"||r.status==="RESUMING"||r.status==="STARTING") return r; if(r.status!=="PAUSED") throw new Error("Only a paused recording can be resumed."); if(r.consents.length===0||r.consents.some(c=>c.consentStatus!=="CONSENTED")) throw new Error("Recording cannot resume until every required participant has consented."); if(r.segments.some(s=>segmentActiveStatuses.includes(s.status))) throw new Error("A recording segment is still finalizing."); const next=(r.segments[0]?.segmentNumber??0)+1; await prisma.meetingRecording.update({where:{id:r.id},data:{status:"RESUMING",safeFailureMessage:null}}); await event(r,"RECORDING_RESUME_REQUESTED",{segmentNumber:next},`resume-requested:${r.id}:${next}`); await audit(workspaceId,"meeting.recording_resume_requested","MeetingRecording",r.id,user.id,{meetingId,segmentNumber:next}); try{ await startSegment(workspaceId,meetingId,recordingId,meeting.roomName,next,user.id); return prisma.meetingRecording.update({where:{id:r.id},data:{status:"RESUMING"}});}catch(e){ const msg=sanitizeProviderError(e); await prisma.meetingRecording.update({where:{id:r.id},data:{status:"PAUSED",safeFailureMessage:msg}}); throw new Error(msg);} }
async function finishPausedRecording(r:{id:string;workspaceId:string;meetingRoomId:string;segments:{status:string;durationSeconds:number|null;fileSizeBytes:bigint|null}[]}){ const usable=r.segments.filter(s=>s.status==="AVAILABLE"); if(!usable.length||r.segments.some(s=>!segmentTerminalStatuses.includes(s.status))) throw new Error("Recording segments are still finalizing."); const total=segmentTotal(usable); const updated=await prisma.meetingRecording.update({where:{id:r.id},data:{status:"AVAILABLE",completedAt:new Date(),durationSeconds:total,fileSizeBytes:usable.reduce((sum,s)=>sum+(s.fileSizeBytes??BigInt(0)),BigInt(0))}}); await queueFinalTranscription(updated); return updated; }
export async function stopRecording(workspaceId:string, meetingId:string, recordingId:string, system=false){ const {user}=system?{user:{id:undefined as string|undefined}}:await assertHost(workspaceId,meetingId); const recording=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{segments:{orderBy:{segmentNumber:"desc"}}}}); if(!recording) notFound(); if(["AVAILABLE","FAILED","CANCELLED"].includes(recording.status)) return recording; if(["STOPPING","PROCESSING"].includes(recording.status)) return recording; await event(recording,"RECORDING_STOP_REQUESTED",{},`stop-requested:${recording.id}`); const segment=recording.segments.find(s=>["STARTING","RECORDING"].includes(s.status)); if(recording.status==="PAUSED"&&!segment) { await audit(workspaceId,"meeting.recording_stop_requested","MeetingRecording",recordingId,user.id,{meetingId,paused:true}); return finishPausedRecording(recording); } await prisma.meetingRecording.update({where:{id:recordingId},data:{status:"STOPPING",stoppedAt:new Date(),stoppedById:user.id}}); if(segment?.providerEgressId) { await prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{status:"STOPPING",stoppedAt:new Date()}}); await stopRoomCompositeRecording(segment.providerEgressId).catch(async e=>{ await prisma.meetingRecording.update({where:{id:recordingId},data:{safeFailureMessage:sanitizeProviderError(e)}}); }); } await audit(workspaceId,"meeting.recording_stop_requested","MeetingRecording",recordingId,user.id,{meetingId,segmentId:segment?.id}); return prisma.meetingRecording.update({where:{id:recordingId},data:{status:"PROCESSING"}}); }
function selectProviderEntry(payload:Record<string,unknown>, providerEgressId:string){ const items=(Array.isArray(payload.items)?payload.items:Array.isArray(payload.egress)?payload.egress:[payload]) as Record<string,unknown>[]; return items.find(i=>String(i.egressId||i.egress_id||"")===providerEgressId)??items[0]??payload; }
export async function reconcileRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user}=await assertHost(workspaceId,meetingId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{segments:{orderBy:{segmentNumber:"desc"}}}}); if(!r) notFound(); await ensureLegacySegment(r); const latest=await prisma.meetingRecording.findUniqueOrThrow({where:{id:r.id},include:{segments:{orderBy:{segmentNumber:"desc"}}}}); const segment=latest.segments.find(s=>["STOPPING","PROCESSING","RECORDING","STARTING"].includes(s.status)&&s.providerEgressId)??latest.segments.find(s=>s.providerEgressId); if(!segment?.providerEgressId) return latest; const provider=selectProviderEntry(await queryRoomCompositeRecording(segment.providerEgressId),segment.providerEgressId); const parsed=parseLiveKitEgress(provider); if(parsed.status==="AVAILABLE") await markWebhookRecordingAvailable(segment.providerEgressId,{...parsed,completedAt:parsed.endedAt},`reconcile:ended:${segment.providerEgressId}`); else if(parsed.status==="FAILED") await markWebhookRecordingFailed(segment.providerEgressId,parsed.safeFailureMessage??"Recording provider reported failure.",`reconcile:failed:${segment.providerEgressId}`); else if(parsed.status==="RECORDING"&&!["PAUSING","STOPPING","PROCESSING","AVAILABLE"].includes(latest.status)){ await markWebhookRecordingStarted(segment.providerEgressId,`reconcile:started:${segment.providerEgressId}`,parsed.startedAt); } const updated=await prisma.meetingRecording.findUniqueOrThrow({where:{id:r.id}}); await audit(workspaceId,"meeting.recording_status_refreshed","MeetingRecording",r.id,user.id,{meetingId,status:updated.status,segmentId:segment.id,segmentStatus:parsed.status}); return updated; }
async function queueFinalTranscription(r:{id:string;workspaceId:string;meetingRoomId:string}){ const latest=await prisma.meetingRecording.findUnique({where:{id:r.id},include:{segments:true,transcriptionJobs:true}}); if(!latest) return; if(latest.transcriptionJobs.some(j=>["QUEUED","PROCESSING","COMPLETED"].includes(j.status))) return; if(!latest.segments.some(s=>s.status==="AVAILABLE")||latest.segments.some(s=>!segmentTerminalStatuses.includes(s.status))) return; const id=createHash("sha256").update(`transcription:${r.id}`).digest("hex").slice(0,24); await prisma.meetingTranscriptionJob.upsert({where:{id},update:{},create:{id,workspaceId:r.workspaceId,meetingRoomId:r.meetingRoomId,recordingId:r.id,status:"QUEUED"}}); await prisma.meetingRecording.update({where:{id:r.id},data:{transcriptionStatus:"QUEUED"}}); await audit(r.workspaceId,"meeting.segmented_transcription_queued","MeetingRecording",r.id,undefined,{meetingId:r.meetingRoomId}); }
export async function markWebhookRecordingStarted(providerEgressId:string,eventKey:string, startedAt?:Date|null){ const segment=await prisma.meetingRecordingSegment.findUnique({where:{providerEgressId},include:{recording:true}}); if(!segment) return null; const at=segment.startedAt??startedAt??new Date(); await prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{status:"RECORDING",startedAt:at}}); const data=["PAUSING","STOPPING","PROCESSING","AVAILABLE"].includes(segment.recording.status)?{}:{status:"RECORDING" as const,startedAt:segment.recording.startedAt??at}; const updated=await prisma.meetingRecording.update({where:{id:segment.recordingId},data}); await event(updated, segment.recording.status==="RESUMING"?"RECORDING_RESUMED":"RECORDING_STARTED",{segmentNumber:segment.segmentNumber},eventKey); return updated; }
export async function markWebhookRecordingFailed(providerEgressId:string,message:string,eventKey:string){ const segment=await prisma.meetingRecordingSegment.findUnique({where:{providerEgressId},include:{recording:true}}); if(!segment) return null; if(["AVAILABLE","FAILED"].includes(segment.status)) return segment.recording; await prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{status:"FAILED",completedAt:new Date(),safeFailureMessage:safeRecordingError(message,"Recording provider reported failure.")}}); const failed=await prisma.meetingRecording.update({where:{id:segment.recordingId},data:{status:"FAILED",failedAt:new Date(),failureCode:"EGRESS_FAILED",safeFailureMessage:safeRecordingError(message,"Recording provider reported failure.")}}); await event(failed,"RECORDING_FAILED",{segmentNumber:segment.segmentNumber},eventKey); return failed; }
// Backward-compatible idempotency guard retained for single-segment tests: if(r.status==="AVAILABLE") return r
export async function markWebhookRecordingAvailable(providerEgressId:string, metadata:Record<string,unknown>, eventKey:string){ const segment=await prisma.meetingRecordingSegment.findUnique({where:{providerEgressId},include:{recording:true}}); if(!segment) { const r=await prisma.meetingRecording.findUnique({where:{providerEgressId}}); if(!r) return null; return r; } if(segment.status==="AVAILABLE") return segment.recording; const durationSeconds=typeof metadata.durationSeconds==="number"?metadata.durationSeconds:undefined; const completedAt=metadata.completedAt instanceof Date?metadata.completedAt:new Date(); await prisma.meetingRecordingSegment.update({where:{id:segment.id},data:{status:"AVAILABLE",stoppedAt:segment.stoppedAt??completedAt,completedAt,fileSizeBytes: typeof metadata.sizeBytes==="number"?BigInt(metadata.sizeBytes):undefined,durationSeconds}}); await event(segment.recording,"RECORDING_SEGMENT_FINALIZED",{segmentNumber:segment.segmentNumber,durationSeconds},eventKey); await audit(segment.workspaceId,"meeting.recording_segment_finalized","MeetingRecording",segment.recordingId,undefined,{meetingId:segment.meetingRoomId,segmentNumber:segment.segmentNumber}); const latest=await prisma.meetingRecording.findUniqueOrThrow({where:{id:segment.recordingId},include:{segments:true}}); const total=segmentTotal(latest.segments); if(latest.status==="PAUSING") { const paused=await prisma.meetingRecording.update({where:{id:latest.id},data:{status:"PAUSED",durationSeconds:total}}); await event(paused,"RECORDING_PAUSED",{durationSeconds:total},`paused:${latest.id}:${segment.segmentNumber}`); await audit(latest.workspaceId,"meeting.recording_paused","MeetingRecording",latest.id,undefined,{meetingId:latest.meetingRoomId,accumulatedDuration:total}); return paused; } const allDone=latest.segments.every(s=>segmentTerminalStatuses.includes(s.status)); if(["STOPPING","PROCESSING"].includes(latest.status)&&allDone){ const updated=await prisma.meetingRecording.update({where:{id:latest.id},data:{status:"AVAILABLE",completedAt:new Date(),durationSeconds:total,fileSizeBytes:latest.segments.reduce((sum,s)=>sum+(s.fileSizeBytes??BigInt(0)),BigInt(0))}}); await event(updated,"RECORDING_AVAILABLE",{durationSeconds:total},`available:${latest.id}`); await queueFinalTranscription(updated); return updated; } return prisma.meetingRecording.update({where:{id:latest.id},data:{durationSeconds:total}}); }
export async function deleteRecording(workspaceId:string, meetingId:string, recordingId:string){ const {user}=await assertHost(workspaceId,meetingId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId}}); if(!r) notFound(); if(["STARTING","RECORDING","STOPPING","PROCESSING"].includes(r.status)) throw new Error("Active or processing recordings cannot be deleted."); if(r.transcriptApprovedAt || r.callSessionId) throw new Error("Approved or handed-off recordings must preserve source history."); if(r.storageKey) await deleteMeetingRecordingObject(r.storageKey); await prisma.meetingRecording.update({where:{id:r.id},data:{status:"DELETED"}}); await audit(workspaceId,"meeting.recording_deleted","MeetingRecording",r.id,user.id,{meetingId}); return r; }

export async function preparePlannedRecordingConsent(workspaceId: string, meetingId: string, actorId: string) {
  const meeting = await prisma.meetingRoom.findFirst({ where: { id: meetingId, workspaceId } });
  if (!meeting) notFound();
  if (!meeting.recordingPlanned || !meeting.recordingConsentRequired) throw new Error("Planned recording requires recording consent.");
  const duplicate = await prisma.meetingRecording.findFirst({ where: { workspaceId, meetingRoomId: meetingId, status: { in: [...activeStatuses] } } });
  if (duplicate) return duplicate;
  const participants = await prisma.meetingParticipant.findMany({ where: { workspaceId, meetingId, leftAt: null } });
  const recording = await prisma.meetingRecording.create({ data: { workspaceId, meetingRoomId: meetingId, requestedById: actorId, status: "CONSENT_REQUIRED", storageKey: buildMeetingRecordingKey(workspaceId, meetingId, "pending") } });
  const updated = await prisma.meetingRecording.update({ where: { id: recording.id }, data: { storageKey: buildMeetingRecordingKey(workspaceId, meetingId, recording.id), bucketName: process.env.MEETING_RECORDINGS_R2_BUCKET, fileName: "recording.mp4", mimeType: "video/mp4" } });
  await prisma.meetingRecordingConsent.createMany({ data: participants.map(p => ({ workspaceId, meetingRoomId: meetingId, recordingId: recording.id, meetingParticipantId: p.id, userId: p.userId, livekitIdentity: p.identity, displayName: p.displayName, consentStatus: "PENDING" })), skipDuplicates: true });
  await prisma.meetingRoom.update({ where: { id: meetingId }, data: { recordingConsentPreparedAt: new Date(), recordingConsentRequired: true } });
  await event(updated, "RECORDING_CONSENT_PREPARED", { participantCount: participants.length, planned: true }, `planned-consent-prepared:${recording.id}`);
  await audit(workspaceId, "meeting.recording_consent_automatically_prepared", "MeetingRecording", recording.id, actorId, { meetingId, participantCount: participants.length });
  await prisma.meetingEvent.create({ data: { workspaceId, meetingId, type: "RECORDING_CONSENT_PREPARED", eventKey: `recording-consent-prepared:${recording.id}`, metadata: toPrismaJson({ recordingId: recording.id, participantCount: participants.length }) } });
  return updated;
}
