import { notFound } from "next/navigation";
import { prisma } from "@/lib/db/prisma";
import { audit } from "@/lib/audit/service";
import { requireUserProfile } from "@/lib/auth/rbac";
import { generateInvitationToken, generateLiveKitRoomName, generateMeetingSlug, hashInvitationToken, participantIdentity, createLiveKitToken } from "@/lib/meetings/livekit";
import { toPrismaJson } from "@/lib/db/json";
import type { MeetingEventType, MeetingParticipantRole, Prisma } from "@prisma/client";

const include = { hostUser: true, lead: true, contact: { include: { company: true } }, company: true, opportunity: { include: { company: true } }, callSession: true, participants: true, invitations: true, events: { orderBy: { createdAt: "desc" as const }, take: 12 } };
const clean = (v: FormDataEntryValue | null) => typeof v === "string" && v.trim() ? v.trim() : undefined;
async function ensure(workspaceId: string, model: "lead"|"contact"|"company"|"opportunity"|"callSession", id?: string) { if (!id) return undefined; let row: { id: string } | null = null;
  if (model === "lead") row = await prisma.lead.findFirst({ where: { id, workspaceId }, select: { id: true } });
  if (model === "contact") row = await prisma.contact.findFirst({ where: { id, workspaceId }, select: { id: true } });
  if (model === "company") row = await prisma.company.findFirst({ where: { id, workspaceId }, select: { id: true } });
  if (model === "opportunity") row = await prisma.opportunity.findFirst({ where: { id, workspaceId }, select: { id: true } });
  if (model === "callSession") row = await prisma.callSession.findFirst({ where: { id, workspaceId }, select: { id: true } }); if (!row) throw new Error("Linked CRM or call record is not available in this workspace."); return id; }
export async function listMeetingRooms(workspaceId: string) { return prisma.meetingRoom.findMany({ where: { workspaceId }, include, orderBy: { updatedAt: "desc" } }); }
export async function getMeetingRoom(workspaceId: string, id: string) { const room = await prisma.meetingRoom.findFirst({ where: { id, workspaceId }, include }); if (!room) notFound(); return room; }
export async function getMeetingFormOptions(workspaceId: string) { const [members, leads, contacts, companies, opportunities, callSessions] = await Promise.all([prisma.workspaceMember.findMany({ where: { workspaceId, status: "ACTIVE" }, include: { user: true }, orderBy: { createdAt: "asc" } }), prisma.lead.findMany({ where: { workspaceId }, orderBy: { updatedAt: "desc" }, take: 100 }), prisma.contact.findMany({ where: { workspaceId }, include: { company: true }, orderBy: { updatedAt: "desc" }, take: 100 }), prisma.company.findMany({ where: { workspaceId }, orderBy: { updatedAt: "desc" }, take: 100 }), prisma.opportunity.findMany({ where: { workspaceId }, include: { company: true }, orderBy: { updatedAt: "desc" }, take: 100 }), prisma.callSession.findMany({ where: { workspaceId }, orderBy: { updatedAt: "desc" }, take: 100 })]); return { members, leads, contacts, companies, opportunities, callSessions }; }
export async function recordMeetingEvent(workspaceId: string, meetingRoomId: string, type: MeetingEventType, participantId?: string, metadata: Record<string, unknown> = {}) { await prisma.meetingEvent.create({ data: { workspaceId, meetingRoomId, type, participantId, metadata: toPrismaJson(metadata) } }); }
export async function createMeetingRoom(workspaceId: string, formData: FormData) { const user = await requireUserProfile(); const scheduledAt = clean(formData.get("scheduledAt")); const data = { workspaceId, createdById: user.id, hostUserId: clean(formData.get("hostUserId")) ?? user.id, title: clean(formData.get("title")) ?? "Untitled meeting", description: clean(formData.get("description")), scheduledAt: scheduledAt ? new Date(scheduledAt) : undefined, status: scheduledAt ? "SCHEDULED" as const : "DRAFT" as const, roomName: generateLiveKitRoomName(workspaceId), slug: generateMeetingSlug(), leadId: await ensure(workspaceId, "lead", clean(formData.get("leadId"))), contactId: await ensure(workspaceId, "contact", clean(formData.get("contactId"))), companyId: await ensure(workspaceId, "company", clean(formData.get("companyId"))), opportunityId: await ensure(workspaceId, "opportunity", clean(formData.get("opportunityId"))), callSessionId: await ensure(workspaceId, "callSession", clean(formData.get("callSessionId"))) } satisfies Prisma.MeetingRoomUncheckedCreateInput; const room = await prisma.meetingRoom.create({ data }); await recordMeetingEvent(workspaceId, room.id, "ROOM_CREATED", undefined, { title: room.title }); await audit(workspaceId, "meeting.created", "MeetingRoom", room.id, user.id, { meetingId: room.id }); return room; }
export async function openMeetingRoom(workspaceId: string, id: string) { const user = await requireUserProfile(); const room = await prisma.meetingRoom.update({ where: { id, workspaceId }, data: { status: "OPEN" } }); await recordMeetingEvent(workspaceId, id, "ROOM_OPENED"); await audit(workspaceId, "meeting.opened", "MeetingRoom", id, user.id, { meetingId: id }); return room; }
export async function endMeetingRoom(workspaceId: string, id: string) { const user = await requireUserProfile(); await prisma.meetingRoom.update({ where: { id, workspaceId }, data: { status: "ENDED", endedAt: new Date() } }); await recordMeetingEvent(workspaceId, id, "ROOM_ENDED"); await audit(workspaceId, "meeting.ended", "MeetingRoom", id, user.id, { meetingId: id }); }
export async function createInvitation(workspaceId: string, meetingRoomId: string, formData: FormData) { const user = await requireUserProfile(); await getMeetingRoom(workspaceId, meetingRoomId); const token = generateInvitationToken(); const expiresAt = clean(formData.get("expiresAt")); const inv = await prisma.meetingInvitation.create({ data: { workspaceId, meetingRoomId, email: clean(formData.get("email")), displayName: clean(formData.get("displayName")), tokenHash: hashInvitationToken(token), role: "GUEST", expiresAt: expiresAt ? new Date(expiresAt) : undefined } }); await recordMeetingEvent(workspaceId, meetingRoomId, "INVITATION_CREATED", undefined, { invitationId: inv.id }); await audit(workspaceId, "meeting.invitation.created", "MeetingInvitation", inv.id, user.id, { meetingId: meetingRoomId }); return { invitation: inv, token }; }
export async function revokeInvitation(workspaceId: string, meetingRoomId: string, invitationId: string) { const user = await requireUserProfile(); await prisma.meetingInvitation.update({ where: { id: invitationId, workspaceId, meetingRoomId }, data: { revokedAt: new Date() } }); await recordMeetingEvent(workspaceId, meetingRoomId, "INVITATION_REVOKED", undefined, { invitationId }); await audit(workspaceId, "meeting.invitation.revoked", "MeetingInvitation", invitationId, user.id, { meetingId: meetingRoomId }); }
export async function loadPublicMeeting(slug: string, token?: string) { const room = await prisma.meetingRoom.findUnique({ where: { slug }, include: { invitations: true } }); if (!room) notFound(); const invitation = token ? room.invitations.find(i => i.tokenHash === hashInvitationToken(token) && !i.revokedAt && (!i.expiresAt || i.expiresAt > new Date())) : null; return { room, invitation, tokenValid: Boolean(invitation) }; }
export async function issueMeetingToken(input: { meetingId: string; workspaceId?: string; invitationToken?: string; displayName: string }) { const user = input.workspaceId ? await requireUserProfile().catch(() => null) : null; const room = await prisma.meetingRoom.findFirst({ where: input.workspaceId ? { id: input.meetingId, workspaceId: input.workspaceId } : { id: input.meetingId } }); if (!room) throw new Error("Meeting access denied."); let role: MeetingParticipantRole = "GUEST"; let email: string|undefined; let subject = `guest-${hashInvitationToken(input.invitationToken ?? input.displayName).slice(0,16)}`; if (user && input.workspaceId === room.workspaceId) { role = room.hostUserId === user.id ? "HOST" : "PARTICIPANT"; subject = user.id; email = user.email; } else { const inv = input.invitationToken ? await prisma.meetingInvitation.findFirst({ where: { meetingRoomId: room.id, tokenHash: hashInvitationToken(input.invitationToken), revokedAt: null, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] } }) : null; if (!inv) throw new Error("A valid invitation is required to join this meeting."); role = inv.role; email = inv.email ?? undefined; }
 const identity = participantIdentity(room.id, subject); const participant = await prisma.meetingParticipant.upsert({ where: { meetingRoomId_livekitIdentity: { meetingRoomId: room.id, livekitIdentity: identity } }, update: { guestName: input.displayName, guestEmail: email, role, leftAt: null }, create: { workspaceId: room.workspaceId, meetingRoomId: room.id, userId: user?.id, guestName: user ? undefined : input.displayName, guestEmail: email, livekitIdentity: identity, role } }); const token = createLiveKitToken({ roomName: room.roomName, identity, displayName: input.displayName, meetingId: room.id, workspaceId: room.workspaceId, role }); await prisma.meetingRoom.update({ where: { id: room.id }, data: { status: "IN_PROGRESS", startedAt: room.startedAt ?? new Date() } }); await prisma.meetingParticipant.update({ where: { id: participant.id }, data: { joinedAt: participant.joinedAt ?? new Date() } }); await recordMeetingEvent(room.workspaceId, room.id, "TOKEN_ISSUED", participant.id, { role, displayName: input.displayName }); await audit(room.workspaceId, "meeting.token.issued", "MeetingRoom", room.id, user?.id, { meetingId: room.id, participantRole: role, displayName: input.displayName }); return { ...token, participantId: participant.id, role } }
export async function markParticipantLeft(participantId: string) { const p = await prisma.meetingParticipant.update({ where: { id: participantId }, data: { leftAt: new Date() } }); await recordMeetingEvent(p.workspaceId, p.meetingRoomId, "PARTICIPANT_LEFT", p.id, { role: p.role, displayName: p.guestName }); }
