import "server-only";
import OpenAI, { toFile } from "openai";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/db/prisma";
import { audit } from "@/lib/audit/service";
import { getMeetingRecordingObject } from "@/lib/storage/meeting-recordings";
import { requireWorkspaceAccess } from "@/lib/auth/rbac";
import { toPrismaJson } from "@/lib/db/json";

const MAX_SYNC_TRANSCRIPTION_BYTES = 24 * 1024 * 1024;
const MAX_ATTEMPTS = 3;
const MODEL = () => process.env.MEETING_TRANSCRIPTION_MODEL || "gpt-4o-mini-transcribe";
function sanitize(error: unknown) { const msg=error instanceof Error?error.message:String(error); if(/api.?key|authorization|credential|secret/i.test(msg)) return "Transcription provider request failed."; return msg.slice(0,240)||"Transcription provider request failed."; }
async function rec(workspaceId:string, meetingId:string, recordingId:string){ await requireWorkspaceAccess(workspaceId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{segments:{orderBy:{segmentNumber:"asc"}},transcriptionJobs:{orderBy:{createdAt:"desc"},take:1}}}); if(!r) notFound(); return r; }
export async function queueTranscription(workspaceId:string, meetingId:string, recordingId:string){ const r=await rec(workspaceId,meetingId,recordingId); if(r.status!=="AVAILABLE") throw new Error("Recording must be available before transcription."); const job=await prisma.meetingTranscriptionJob.create({data:{workspaceId,meetingRoomId:meetingId,recordingId,status:"QUEUED"}}); await prisma.meetingRecording.update({where:{id:recordingId},data:{transcriptionStatus:"QUEUED"}}); await audit(workspaceId,"meeting.transcription_queued","MeetingRecording",recordingId,undefined,{meetingId}); return job; }
export async function processTranscriptionJob(workspaceId:string, meetingId:string, recordingId:string){ const r=await rec(workspaceId,meetingId,recordingId); const segments=(r.segments?.length?r.segments:[{segmentNumber:1,storageKey:r.storageKey,fileName:r.fileName,mimeType:r.mimeType,fileSizeBytes:r.fileSizeBytes,status:r.status}]).filter(s=>s.status==="AVAILABLE"); if(!segments.length) throw new Error("Recording file is not available for transcription."); const failed=r.segments?.find(s=>s.status==="FAILED"); if(failed) throw new Error(`Recording part ${failed.segmentNumber} failed and must be repaired before transcription.`); const oversized=segments.find(s=>s.fileSizeBytes && s.fileSizeBytes > BigInt(MAX_SYNC_TRANSCRIPTION_BYTES)); if(oversized) { const message=`Recording part ${oversized.segmentNumber} is too large for automatic transcription in the current processing environment.`; await prisma.meetingRecording.update({where:{id:r.id},data:{transcriptionStatus:"FAILED",safeFailureMessage:message}}); throw new Error(message); }
 const existing=await prisma.meetingTranscriptionJob.findFirst({where:{recordingId:r.id,status:"PROCESSING"}}); if(existing) throw new Error("A transcription job is already processing."); const job=r.transcriptionJobs[0] ?? await prisma.meetingTranscriptionJob.create({data:{workspaceId,meetingRoomId:meetingId,recordingId,status:"QUEUED"}}); if(job.attemptCount>=MAX_ATTEMPTS) throw new Error("Transcription retry limit has been reached."); await prisma.meetingTranscriptionJob.update({where:{id:job.id},data:{status:"PROCESSING",startedAt:new Date(),lastAttemptAt:new Date(),attemptCount:{increment:1}}}); await prisma.meetingRecording.update({where:{id:r.id},data:{transcriptionStatus:"PROCESSING"}}); await audit(workspaceId,"meeting.segmented_transcription_started","MeetingRecording",r.id,undefined,{meetingId,attemptCount:job.attemptCount+1,segmentCount:segments.length,transcriptionModel:MODEL()});
 try { const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY}); const texts:string[]=[]; for (const segment of segments) { if(!segment.storageKey) throw new Error(`Recording part ${segment.segmentNumber} is missing its storage object.`); const object=await getMeetingRecordingObject(segment.storageKey); const size=Number(object.headers.get("content-length") || segment.fileSizeBytes || 0); if(size>MAX_SYNC_TRANSCRIPTION_BYTES) throw new Error(`Recording part ${segment.segmentNumber} is too large for automatic transcription in the current processing environment.`); const buffer=Buffer.from(await object.arrayBuffer()); const file=await toFile(buffer, segment.fileName || `recording-part-${segment.segmentNumber}.mp4`, { type: segment.mimeType || "video/mp4" }); const result=await client.audio.transcriptions.create({ file, model: MODEL() }); const text=String(result.text || "").trim(); if(!text) throw new Error(`Recording part ${segment.segmentNumber} transcription returned no text.`); texts.push(text); } const text=texts.join("\n\n").trim(); await prisma.$transaction([prisma.meetingRecording.update({where:{id:r.id},data:{transcriptionStatus:"REVIEW_REQUIRED",transcriptText:text,transcriptEditedText:text,transcriptModel:MODEL()}}), prisma.meetingTranscriptionJob.update({where:{id:job.id},data:{status:"COMPLETED",completedAt:new Date(),safeFailureMessage:null,failureCode:null}}), prisma.meetingRecordingEvent.create({data:{workspaceId,meetingRoomId:meetingId,recordingId:r.id,type:"TRANSCRIPTION_COMPLETED",metadata:toPrismaJson({characterCount:text.length,segmentCount:segments.length,transcriptionModel:MODEL()})}})]); await audit(workspaceId,"meeting.segmented_transcription_completed","MeetingRecording",r.id,undefined,{meetingId,characterCount:text.length,segmentCount:segments.length,transcriptionModel:MODEL()}); return {text}; } catch(e) { const message=sanitize(e); const attempts=job.attemptCount+1; await prisma.meetingTranscriptionJob.update({where:{id:job.id},data:{status:attempts>=MAX_ATTEMPTS?"FAILED":"RETRY_WAIT",failureCode:"TRANSCRIPTION_FAILED",safeFailureMessage:message,nextAttemptAt:attempts>=MAX_ATTEMPTS?null:new Date(Date.now()+attempts*5*60_000)}}); await prisma.meetingRecording.update({where:{id:r.id},data:{transcriptionStatus:attempts>=MAX_ATTEMPTS?"FAILED":"QUEUED",safeFailureMessage:message}}); await audit(workspaceId,"meeting.segmented_transcription_failed","MeetingRecording",r.id,undefined,{meetingId,attemptCount:attempts}); throw new Error(message); }
}
export async function saveTranscriptDraft(workspaceId:string, meetingId:string, recordingId:string, text:string){ const {user}=await requireWorkspaceAccess(workspaceId); const r=await rec(workspaceId,meetingId,recordingId); if(r.transcriptApprovedAt) throw new Error("Approved transcripts cannot be edited in this workflow."); const value=text.trim(); const updated=await prisma.meetingRecording.update({where:{id:r.id},data:{transcriptEditedText:value}}); await audit(workspaceId,"meeting.transcript_edited","MeetingRecording",r.id,user.id,{meetingId,characterCount:value.length}); return updated; }
export async function approveTranscript(workspaceId:string, meetingId:string, recordingId:string){ const {user}=await requireWorkspaceAccess(workspaceId); const r=await prisma.meetingRecording.findFirst({where:{id:recordingId,workspaceId,meetingRoomId:meetingId},include:{meetingRoom:true}}); if(!r) notFound(); if(r.transcriptApprovedAt) return r; const text=(r.transcriptEditedText||r.transcriptText||"").trim(); if(!text) throw new Error("Transcript text is required before approval."); const meeting=r.meetingRoom; const callId=meeting.callSessionId; if(callId){ const existing=await prisma.callSession.findFirst({where:{id:callId,workspaceId}}); if(existing?.transcriptText && existing.transcriptSource!==`meeting_recording:${r.id}`) throw new Error("The linked CallSession already has transcript text. Review manually before overwriting."); }
 const call=callId ? await prisma.callSession.update({where:{id:callId},data:{transcriptText:text,transcriptSource:`meeting_recording:${r.id}`,recordingUrl:`/api/meetings/${meetingId}/recordings/${r.id}/download`,status:"TRANSCRIPT_READY"}}) : await prisma.callSession.create({data:{workspaceId,leadId:meeting.leadId,contactId:meeting.contactId,companyId:meeting.companyId,opportunityId:meeting.opportunityId,provider:"OTHER",meetingUrl:`/dashboard/meetings/${meetingId}`,recordingUrl:`/api/meetings/${meetingId}/recordings/${r.id}/download`,transcriptText:text,transcriptSource:`meeting_recording:${r.id}`,callDate:meeting.startedAt??meeting.scheduledAt,createdById:user.id,status:"TRANSCRIPT_READY"}});
 if(!callId) await prisma.meetingRoom.update({where:{id:meetingId},data:{callSessionId:call.id}}); const updated=await prisma.meetingRecording.update({where:{id:r.id},data:{transcriptionStatus:"APPROVED",transcriptApprovedAt:new Date(),transcriptApprovedById:user.id,callSessionId:call.id}}); await audit(workspaceId,"meeting.transcript_approved","MeetingRecording",r.id,user.id,{meetingId,callSessionId:call.id,characterCount:text.length}); await audit(workspaceId,"meeting.call_session_updated_from_transcript","CallSession",call.id,user.id,{meetingId,recordingId:r.id}); return updated; }
export const transcriptionLimits={ MAX_SYNC_TRANSCRIPTION_BYTES, MAX_ATTEMPTS };
