import Link from "next/link";
import { getCurrentWorkspace } from "@/lib/workspaces/service";
import { initialKnowledgeManifest, listKnowledgeDocuments } from "@/lib/knowledge/service";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";

function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full border px-2 py-1 text-xs font-medium dark:border-slate-700">{children}</span>; }
export default async function KnowledgePage() {
  const workspace = await getCurrentWorkspace();
  if (!workspace) return <Card><CardHeader><CardTitle>No active workspace</CardTitle><CardDescription>Create or join a workspace before managing source-of-truth documents.</CardDescription></CardHeader></Card>;
  const documents = await listKnowledgeDocuments(workspace.id);
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-slate-500 dark:text-slate-400">Source-of-truth governance</p><h1 className="text-3xl font-semibold">Knowledge foundation</h1><p className="mt-2 max-w-3xl text-slate-600 dark:text-slate-300">Approve active methodology documents, map them to workflow stages, and let AI generation cite the governed chunks it used.</p></div><Button asChild><Link href="/dashboard/knowledge/new">Create document</Link></Button></header><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardDescription>Documents</CardDescription><CardTitle className="text-3xl">{documents.length}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Active doctrine</CardDescription><CardTitle className="text-3xl">{documents.filter((d) => d.status === "ACTIVE").length}</CardTitle></CardHeader></Card><Card><CardHeader><CardDescription>Chunks</CardDescription><CardTitle className="text-3xl">{documents.reduce((sum, doc) => sum + doc.chunks.length, 0)}</CardTitle></CardHeader></Card></div><Card><CardHeader><CardTitle>Workspace documents</CardTitle><CardDescription>Draft and archived records are visible here but are excluded from production prompt context.</CardDescription></CardHeader><CardContent className="space-y-3">{documents.map((doc) => <Link key={doc.id} href={`/dashboard/knowledge/${doc.id}`} className="block rounded-2xl border p-4 hover:bg-slate-50 dark:border-slate-800 dark:hover:bg-slate-900"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold">{doc.title}</h2><p className="text-sm text-slate-500 dark:text-slate-400">{doc.description ?? "No description"}</p></div><div className="flex flex-wrap gap-2"><Badge>{doc.status}</Badge><Badge>{doc.authorityLevel}</Badge><Badge>{doc.priority}</Badge><Badge>{doc.chunks.length} chunks</Badge></div></div></Link>)}{documents.length === 0 ? <p className="text-sm text-slate-500">No knowledge documents yet. Start with the 11-document manifest below.</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Initial source-of-truth manifest</CardTitle><CardDescription>PDF parsing is deferred. Create these records manually and paste approved text when source files are available.</CardDescription></CardHeader><CardContent className="grid gap-3 md:grid-cols-2">{initialKnowledgeManifest.map((item) => <div key={item.title} className="rounded-xl border p-4 dark:border-slate-800"><p className="font-medium">{item.title}</p><p className="mt-1 text-xs text-slate-500">{item.authorityLevel} · {item.priority}</p><p className="mt-2 text-sm text-slate-600 dark:text-slate-300">{item.useFor}</p></div>)}</CardContent></Card></div>;
}
