/* eslint-disable @typescript-eslint/no-explicit-any */
"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db/prisma";
import { requireOperatorAccess } from "@/lib/admin/operator";
import { bootstrapCommerceCatalog, entitlementKeys, numericEntitlements, parseBool, parseIntField, parseString, upsertProductEntitlement } from "@/lib/sending-infrastructure/operational";
export async function bootstrapCatalogAction(){ await requireOperatorAccess(); await bootstrapCommerceCatalog(); revalidatePath('/platform/catalog'); revalidatePath('/platform/sending-packages'); }
export async function saveProductAction(form: FormData){ await requireOperatorAccess(); const id=String(form.get('id')||''); const key=parseString(form,'key')!; if(!/^[A-Z][A-Z0-9_]*$/.test(key)) throw new Error('Product key must be an uppercase-safe identifier.'); const data={ key, name: parseString(form,'name')!, description: parseString(form,'description',false), category: parseString(form,'category')! as any, active: parseBool(form,'active'), recurring: parseBool(form,'recurring'), billingInterval: parseString(form,'billingInterval')! as any, stripeProductId: parseString(form,'stripeProductId',false), stripePriceId: parseString(form,'stripePriceId',false), stripeSetupPriceId: parseString(form,'stripeSetupPriceId',false), sortOrder: parseIntField(form,'sortOrder') } as const; if(!id && await prisma.commerceProduct.findUnique({where:{key}})) throw new Error('A product with this key already exists.'); if(id) await prisma.commerceProduct.update({where:{id},data}); else await prisma.commerceProduct.create({data}); revalidatePath('/platform/catalog'); revalidatePath('/platform/sending-packages'); }
export async function setProductActiveAction(form: FormData){ await requireOperatorAccess(); await prisma.commerceProduct.update({where:{id:parseString(form,'id')!},data:{active:parseBool(form,'active')}}); revalidatePath('/platform/catalog'); revalidatePath('/platform/sending-packages'); }
export async function saveEntitlementAction(form: FormData){ await requireOperatorAccess(); const productId=parseString(form,'productId')!; const key=parseString(form,'entitlementKey')! as any; if(!entitlementKeys.includes(key)) throw new Error('Unsupported entitlement.'); const value=numericEntitlements.has(key)?parseIntField(form,'value'):parseBool(form,'value'); await upsertProductEntitlement(productId,key,value); revalidatePath('/platform/catalog'); revalidatePath('/platform/sending-packages'); }
