/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "@/lib/db/prisma";
import { DEFAULT_COMMERCE_CATALOG, ENTITLEMENT_KEYS, EntitlementKey, aggregateEntitlements } from "./catalog";
import { getMailboxProvider, getProviderReadiness } from "./providers";
import { enforceAllowance, evaluateSenderReadiness } from "./readiness";
import { idempotencyKey, localPartIsValid, mailboxAddress } from "./provisioning";

export const entitlementKeys = Object.values(ENTITLEMENT_KEYS);
export const numericEntitlements = new Set<string>(entitlementKeys.filter((k) => !k.endsWith("_ENABLED")));
const activeStatuses = ["ACTIVE", "TRIALING"];

type Db = typeof prisma;
export function parseString(form: FormData, key: string, required = true) { const value = String(form.get(key) ?? "").trim(); if (required && !value) throw new Error(`${key} is required.`); return value || null; }
export function parseIntField(form: FormData, key: string, fallback = 0) { const raw = String(form.get(key) ?? "").trim(); if (!raw) return fallback; const n = Number(raw); if (!Number.isInteger(n) || n < 0) throw new Error(`${key} must be a non-negative integer.`); return n; }
export function parseBool(form: FormData, key: string) { return ["on", "true", "1", "yes"].includes(String(form.get(key) ?? "").toLowerCase()); }

export async function bootstrapCommerceCatalog(db: Db = prisma) {
  for (const product of DEFAULT_COMMERCE_CATALOG) {
    const saved = await db.commerceProduct.upsert({ where: { key: product.key }, update: { name: product.name, category: product.category as any, active: product.active, recurring: product.recurring, sortOrder: product.sortOrder }, create: { key: product.key, name: product.name, category: product.category as any, active: product.active, recurring: product.recurring, sortOrder: product.sortOrder } });
    for (const [entitlementKey, value] of Object.entries(product.entitlements)) await upsertProductEntitlement(saved.id, entitlementKey as EntitlementKey, value as any, db);
  }
}

export async function upsertProductEntitlement(productId: string, entitlementKey: EntitlementKey, value: number | boolean | string, db: Db = prisma) {
  if (!entitlementKeys.includes(entitlementKey)) throw new Error("Unsupported entitlement key.");
  const data = typeof value === "boolean" ? { booleanValue: value, integerValue: null, stringValue: null } : numericEntitlements.has(entitlementKey) ? { integerValue: Number(value), booleanValue: null, stringValue: null } : { stringValue: String(value), booleanValue: null, integerValue: null };
  return db.commerceProductEntitlement.upsert({ where: { productId_entitlementKey: { productId, entitlementKey } }, update: data, create: { productId, entitlementKey, ...data } });
}

export async function listCatalogProducts(db: Db = prisma) { return db.commerceProduct.findMany({ orderBy: [{ sortOrder: "asc" }, { name: "asc" }], include: { entitlements: true, subscriptionItems: { where: { status: { in: activeStatuses as any } }, select: { workspaceId: true } } } }); }
export function entitlementMap(product: Awaited<ReturnType<typeof listCatalogProducts>>[number]) { return Object.fromEntries(product.entitlements.map((e) => [e.entitlementKey, e.integerValue ?? e.booleanValue ?? e.stringValue ?? 0])); }

export async function getWorkspaceEffectiveEntitlements(workspaceId: string, db: Db = prisma) {
  const items = await db.saasSubscriptionItem.findMany({ where: { workspaceId, status: { in: activeStatuses as any } }, include: { commerceProduct: { include: { entitlements: true } } } });
  const catalog = items.map((i) => ({ key: i.commerceProduct.key, name: i.commerceProduct.name, category: i.commerceProduct.category as any, active: i.commerceProduct.active, recurring: i.commerceProduct.recurring, sortOrder: i.commerceProduct.sortOrder, stripePriceId: i.commerceProduct.stripePriceId, stripeProductId: i.commerceProduct.stripeProductId, entitlements: entitlementMap(i.commerceProduct as any) }));
  const overrides = await db.infrastructureEntitlementOverride.findMany({ where: { workspaceId, OR: [{ expiresAt: null }, { expiresAt: { gt: new Date() } }] } });
  const overrideMap = Object.fromEntries(overrides.map((o) => [o.entitlementKey, o.integerValue ?? o.booleanValue ?? o.stringValue ?? 0]));
  const effective = aggregateEntitlements(items.map((i) => ({ id: i.id, stripeSubscriptionItemId: i.stripeSubscriptionItemId, productKey: i.commerceProduct.key, quantity: i.quantity, status: i.status })), catalog, overrideMap as any);
  return { effective, items, overrides };
}

export function currentBillingPeriod(now = new Date()) { return { periodStart: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)), periodEnd: new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() + 1, 1)) }; }
export async function reconcileWorkspaceInfrastructureUsage(workspaceId: string, db: Db = prisma) { const { periodStart, periodEnd } = currentBillingPeriod(); const [sentMessageCount, managedDomainCount, activeMailboxCount, senderIdentityCount, activeOutreachContactCount, campaignSendCount, providerErrorCount] = await Promise.all([db.outboundMessageLedger.count({ where: { workspaceId, sentAt: { gte: periodStart, lt: periodEnd } } }), db.managedDomain.count({ where: { workspaceId } }), db.managedMailbox.count({ where: { workspaceId, status: { in: ["ACTIVE", "PROVISIONING", "PENDING", "PENDING_PROVIDER_CONFIGURATION"] as any } } }), db.infrastructureSenderIdentity.count({ where: { workspaceId } }), db.lead.count({ where: { workspaceId, status: { not: "ARCHIVED" } } }), db.campaignSendJob.count({ where: { workspaceId, createdAt: { gte: periodStart, lt: periodEnd } } }), db.mailboxProvisioningEvent.count({ where: { workspaceId, status: "FAILED" } })]); return db.workspaceInfrastructureUsage.upsert({ where: { workspaceId_periodStart_periodEnd: { workspaceId, periodStart, periodEnd } }, update: { sentMessageCount, managedDomainCount, activeMailboxCount, senderIdentityCount, activeOutreachContactCount, campaignSendCount, providerErrorCount }, create: { workspaceId, periodStart, periodEnd, sentMessageCount, managedDomainCount, activeMailboxCount, senderIdentityCount, activeOutreachContactCount, campaignSendCount, providerErrorCount } }); }

export async function getSubscriberSendingSnapshot(workspaceId: string, db: Db = prisma) { const [entitlements, domains, mailboxes, senders, provisioning, deliverability, usage] = await Promise.all([getWorkspaceEffectiveEntitlements(workspaceId, db), db.managedDomain.findMany({ where: { OR: [{ workspaceId }, { assignments: { some: { workspaceId, status: "ACTIVE" as any } } }] }, include: { assignments: true, dnsRecords: true, sesIdentity: true, warmupPlan: true } }), db.managedMailbox.findMany({ where: { workspaceId }, orderBy: { createdAt: "desc" } }), db.infrastructureSenderIdentity.findMany({ where: { workspaceId }, orderBy: { createdAt: "desc" } }), db.workspaceInfrastructureProvisioning.findMany({ where: { workspaceId }, orderBy: { updatedAt: "desc" }, take: 5 }), getDeliverabilityMetrics(workspaceId, db), reconcileWorkspaceInfrastructureUsage(workspaceId, db)]); const sendingPackage = entitlements.items.find((i) => i.commerceProduct.category === "SENDING_PACKAGE"); return { ...entitlements, sendingPackage, domains, mailboxes, senders, provisioning, deliverability, usage }; }

export async function getDeliverabilityMetrics(workspaceId: string, db: Db = prisma) { const [sent, delivered, hardBounces, softBounces, complaints, unsubscribes, suppressions, replies] = await Promise.all([db.outboundMessageLedger.count({ where: { workspaceId, sentAt: { not: null } } }), db.outboundMessageLedger.count({ where: { workspaceId, deliveredAt: { not: null } } }), db.outboundMessageLedger.count({ where: { workspaceId, bouncedAt: { not: null }, failureCode: { contains: "HARD" } } }), db.outboundMessageLedger.count({ where: { workspaceId, bouncedAt: { not: null }, NOT: { failureCode: { contains: "HARD" } } } }), db.outboundMessageLedger.count({ where: { workspaceId, complainedAt: { not: null } } }), db.outboundMessageLedger.count({ where: { workspaceId, unsubscribedAt: { not: null } } }), db.outboundMessageLedger.count({ where: { workspaceId, status: "SUPPRESSED" } }), db.inboundEmailMessage.count({ where: { workspaceId } })]); return { sent, delivered, hardBounces, softBounces, complaints, unsubscribes, suppressions, replies }; }

export async function createMailboxRequest(workspaceId: string, domainId: string, localPart: string, displayName?: string | null, db: Db = prisma) { if (!localPartIsValid(localPart)) throw new Error("Invalid mailbox local part."); const domain = await db.managedDomain.findFirst({ where: { id: domainId, OR: [{ workspaceId }, { assignments: { some: { workspaceId, status: "ACTIVE" as any } } }] }, include: { dnsRecords: true, sesIdentity: true } }); if (!domain) throw new Error("Domain is not assigned to this workspace."); const { effective } = await getWorkspaceEffectiveEntitlements(workspaceId, db); const used = await db.managedMailbox.count({ where: { workspaceId } }); const allowance = enforceAllowance("mailbox", effective, used); if (!allowance.allowed) throw new Error(allowance.reason); const emailAddress = mailboxAddress(localPart, domain.domainName); if (await db.managedMailbox.findUnique({ where: { workspaceId_emailAddress: { workspaceId, emailAddress } } })) throw new Error("Mailbox already exists."); const provider = getMailboxProvider(); const health = provider.getProviderHealth(); const eventKey = idempotencyKey(["mailbox", workspaceId, emailAddress]); const status = health.state === "NOT_CONFIGURED" ? "PENDING_PROVIDER_CONFIGURATION" : "PROVISIONING"; const mailbox = await db.managedMailbox.create({ data: { workspaceId, managedDomainId: domain.id, provider: provider.key as any, localPart, emailAddress, displayName, status: status as any, provisioningStatus: status } }); await db.mailboxProvisioningEvent.create({ data: { workspaceId, managedMailboxId: mailbox.id, idempotencyKey: eventKey, status, safeSummary: health.safeMessage } }); await enqueueInfrastructureJob({ workspaceId, jobType: "MAILBOX_PROVISION", idempotencyKey: eventKey, payload: { mailboxId: mailbox.id } }, db); return mailbox; }

export async function enqueueInfrastructureJob(input: { workspaceId?: string | null; jobType: string; idempotencyKey: string; payload?: unknown }, db: Db = prisma) { return (db as any).infrastructureJob.upsert({ where: { idempotencyKey: input.idempotencyKey }, update: {}, create: { workspaceId: input.workspaceId, jobType: input.jobType, idempotencyKey: input.idempotencyKey, payload: (input.payload ?? {}) as any } }); }
export async function retryInfrastructureJob(id: string, db: Db = prisma) { return (db as any).infrastructureJob.update({ where: { id }, data: { status: "QUEUED", lockedAt: null, lockedBy: null, attemptCount: { increment: 1 }, nextAttemptAt: new Date() } }); }
export async function deriveProvisioningStage(workspaceId: string, db: Db = prisma) { const [domains, mailboxes, senders] = await Promise.all([db.managedDomain.count({ where: { workspaceId } }), db.managedMailbox.count({ where: { workspaceId, status: "ACTIVE" as any } }), db.infrastructureSenderIdentity.count({ where: { workspaceId, campaignEligible: true } })]); const status = domains === 0 ? "DOMAIN_PENDING" : mailboxes === 0 ? "MAILBOX_PENDING" : senders === 0 ? "SENDER_PENDING" : "READY"; return db.workspaceInfrastructureProvisioning.upsert({ where: { idempotencyKey: idempotencyKey(["provisioning", workspaceId]) }, update: { status: status as any, stages: { domains, mailboxes, senders } as any, safeSummary: status === "READY" ? "All persisted readiness stages are ready." : `Blocked at ${status}.` }, create: { workspaceId, idempotencyKey: idempotencyKey(["provisioning", workspaceId]), status: status as any, stages: { domains, mailboxes, senders } as any, safeSummary: `Blocked at ${status}.` } }); }

export async function operatorReadiness(db: Db = prisma) { const provider = getProviderReadiness(); const [catalogMapped, commissionRules] = await Promise.all([db.commerceProduct.count({ where: { stripePriceId: { not: null } } }), db.commissionRule.count({ where: { active: true } })]); return [{ name: "Domain Provider", state: provider.domainProvider === "disabled" ? "NOT_CONFIGURED" : "READY", reason: `DOMAIN_PROVIDER=${provider.domainProvider}` }, { name: "Mailbox Provider", state: provider.mailbox.state, reason: provider.mailbox.safeMessage }, { name: "AWS SES", state: process.env.AWS_SES_REGION && process.env.AWS_ACCESS_KEY_ID ? "CONFIGURED" : "NOT_CONFIGURED", reason: process.env.AWS_SES_REGION ? "AWS SES region configured; credentials are not displayed." : "AWS_SES_REGION is not configured." }, { name: "DNS Provider", state: provider.dnsAutomationEnabled ? "READY" : "NOT_CONFIGURED", reason: provider.dnsAutomationEnabled ? "DNS automation enabled." : "DNS_AUTOMATION_ENABLED is false." }, { name: "Inbound Sync", state: provider.inboundSyncEnabled ? "READY" : "NOT_CONFIGURED", reason: provider.inboundSyncEnabled ? "Inbound sync enabled." : "INBOUND_EMAIL_SYNC_ENABLED is false." }, { name: "Campaign Worker", state: process.env.CAMPAIGN_WORKER_ENABLED === "true" ? "READY" : "NOT_CONFIGURED", reason: process.env.CAMPAIGN_WORKER_ENABLED === "true" ? "Worker enabled." : "Campaign worker is not enabled; jobs remain queued." }, { name: "Stripe Catalog Mapping", state: catalogMapped > 0 ? "PARTIAL" : "NOT_CONFIGURED", reason: `${catalogMapped} products have Stripe price mappings.` }, { name: "Commission Rules", state: commissionRules > 0 ? "READY" : "NOT_CONFIGURED", reason: `${commissionRules} active commission rules.` }]; }

export function senderReadinessFromRecords(sender: any, mailbox?: any, domain?: any) { return evaluateSenderReadiness({ domainReady: Boolean(domain && domain.lifecycleStatus !== "AVAILABLE"), mailboxActive: mailbox?.status === "ACTIVE", sesIdentityReady: sender.sesIdentityState === "VERIFIED" || domain?.sesIdentity?.verificationStatus === "SUCCESS", dkimReady: sender.dkimState === "VERIFIED" || domain?.sesIdentity?.dkimStatus === "SUCCESS", complianceReady: true, rampReady: domain?.warmupPlan?.status === "ACTIVE" || domain?.warmupPlan?.status === "COMPLETED", sendingEnabled: sender.sendingEnabled, dailySendCap: sender.dailySendCap ?? undefined }); }
