export type LifecycleState = "REQUESTED"|"PROVISIONING"|"PROVISIONED"|"DNS_PENDING"|"AUTHENTICATED"|"WARMUP_PENDING"|"WARMING"|"WARMUP_HELD"|"LIVE_READY"|"THROTTLED"|"PAUSED"|"RECOVERY"|"FAILED"|"RETIRED";
export type WarmupPolicy = { minimumDays: number; minimumDelivered: number; healthyDays: number; promotionScore: number; healthyBounceRate: number; pauseBounceRate: number; healthyComplaintRate: number; emergencyComplaintRate: number; minimumDeliveryRate: number; matureMailboxCap: number; domainCap: number };
export const DEFAULT_WARMUP_POLICY: WarmupPolicy = { minimumDays: 21, minimumDelivered: 150, healthyDays: 7, promotionScore: 90, healthyBounceRate: .02, pauseBounceRate: .03, healthyComplaintRate: .001, emergencyComplaintRate: .003, minimumDeliveryRate: .95, matureMailboxCap: 35, domainCap: 105 };
export type HealthInput = { state: LifecycleState; elapsedDays: number; delivered: number; sent: number; hardBounces: number; complaints: number; consecutiveHealthyDays: number; spf: boolean; dkim: boolean; dmarc: boolean; outboundTest: boolean; inboundTest: boolean; bouncePipeline: boolean; complaintPipeline: boolean; suppressionPipeline: boolean; providerHealthy: boolean; providerThrottled?: boolean; domainPaused?: boolean; legalHold?: boolean; isSimulated?: boolean; scenarioId?: string };
export type WarmupDecision = { action: "INCREASE"|"HOLD"|"REDUCE"|"PAUSE"|"PROMOTE_LIVE"|"DEMOTE_LIVE"|"NO_CHANGE"; nextState: LifecycleState; score: number; eligible: boolean; reasons: string[]; components: Record<string, { score: number; maximum: number; explanation: string }>; metrics: { deliveryRate: number; bounceRate: number; complaintRate: number }; isSimulated: boolean };
const rate = (n: number, d: number) => d > 0 ? n / d : 0;
export function evaluateWarmup(input: HealthInput, policy = DEFAULT_WARMUP_POLICY): WarmupDecision {
  const deliveryRate = rate(input.delivered, input.sent), bounceRate = rate(input.hardBounces, input.sent), complaintRate = rate(input.complaints, input.sent);
  const auth = input.spf && input.dkim && input.dmarc, delivery = input.sent > 0 && deliveryRate >= policy.minimumDeliveryRate, bounce = bounceRate < policy.healthyBounceRate, complaint = complaintRate < policy.healthyComplaintRate;
  const components = { authentication: { score: auth ? 20 : 0, maximum: 20, explanation: auth ? "SPF, DKIM, and DMARC pass." : "Email authentication is incomplete." }, delivery: { score: delivery ? 20 : 0, maximum: 20, explanation: `Delivery rate ${(deliveryRate*100).toFixed(2)}%.` }, bounce: { score: bounce ? 20 : bounceRate <= policy.pauseBounceRate ? 10 : 0, maximum: 20, explanation: `Hard-bounce rate ${(bounceRate*100).toFixed(2)}%.` }, complaint: { score: complaint ? 20 : complaintRate < policy.emergencyComplaintRate ? 10 : 0, maximum: 20, explanation: `Complaint rate ${(complaintRate*100).toFixed(3)}%.` }, consistency: { score: input.consecutiveHealthyDays >= policy.healthyDays ? 10 : Math.floor(10 * input.consecutiveHealthyDays / policy.healthyDays), maximum: 10, explanation: `${input.consecutiveHealthyDays} consecutive healthy days.` }, provider: { score: input.providerHealthy && !input.providerThrottled ? 5 : 0, maximum: 5, explanation: input.providerHealthy ? "Provider account available." : "Provider unavailable." }, domain: { score: !input.domainPaused ? 5 : 0, maximum: 5, explanation: input.domainPaused ? "Domain is paused." : "Domain has no active pause." } };
  const score = Object.values(components).reduce((sum, c) => sum + c.score, 0);
  const reasons: string[] = [];
  if (!input.spf) reasons.push("SPF_FAILED"); if (!input.dkim) reasons.push("DKIM_FAILED"); if (!input.dmarc) reasons.push("DMARC_INVALID");
  if (!input.outboundTest) reasons.push("OUTBOUND_TEST_REQUIRED"); if (!input.inboundTest) reasons.push("INBOUND_TEST_REQUIRED");
  if (!input.bouncePipeline) reasons.push("BOUNCE_PIPELINE_UNAVAILABLE"); if (!input.complaintPipeline) reasons.push("COMPLAINT_PIPELINE_UNAVAILABLE"); if (!input.suppressionPipeline) reasons.push("SUPPRESSION_PIPELINE_UNAVAILABLE");
  if (!input.providerHealthy) reasons.push("PROVIDER_UNHEALTHY"); if (input.providerThrottled) reasons.push("PROVIDER_THROTTLED"); if (input.domainPaused) reasons.push("DOMAIN_PAUSED"); if (input.legalHold) reasons.push("LEGAL_HOLD");
  if (bounceRate > policy.pauseBounceRate) reasons.push("BOUNCE_PAUSE_THRESHOLD"); if (complaintRate >= policy.emergencyComplaintRate) reasons.push("COMPLAINT_EMERGENCY_THRESHOLD");
  if (input.elapsedDays < policy.minimumDays) reasons.push("MINIMUM_DURATION_NOT_MET"); if (input.delivered < policy.minimumDelivered) reasons.push("MINIMUM_SAMPLE_NOT_MET"); if (input.consecutiveHealthyDays < policy.healthyDays) reasons.push("HEALTHY_DAYS_NOT_MET"); if (!delivery) reasons.push("DELIVERY_RATE_NOT_MET"); if (score < policy.promotionScore) reasons.push("HEALTH_SCORE_NOT_MET");
  const hardPause = reasons.some(r => ["SPF_FAILED","DKIM_FAILED","DMARC_INVALID","BOUNCE_PIPELINE_UNAVAILABLE","COMPLAINT_PIPELINE_UNAVAILABLE","SUPPRESSION_PIPELINE_UNAVAILABLE","PROVIDER_UNHEALTHY","DOMAIN_PAUSED","LEGAL_HOLD","BOUNCE_PAUSE_THRESHOLD","COMPLAINT_EMERGENCY_THRESHOLD"].includes(r));
  const eligible = reasons.length === 0;
  let action: WarmupDecision["action"] = "HOLD", nextState: LifecycleState = input.state;
  if (hardPause) { action = input.state === "LIVE_READY" ? "DEMOTE_LIVE" : "PAUSE"; nextState = "PAUSED"; }
  else if (eligible && input.state !== "LIVE_READY") { action = "PROMOTE_LIVE"; nextState = "LIVE_READY"; }
  else if (input.state === "LIVE_READY") action = "NO_CHANGE";
  else if (input.providerThrottled || !bounce || !complaint) { action = "REDUCE"; nextState = "WARMUP_HELD"; }
  return { action, nextState, score, eligible, reasons, components, metrics: { deliveryRate, bounceRate, complaintRate }, isSimulated: Boolean(input.isSimulated) };
}

export type SendGateInput = { mailboxState: LifecycleState; domainState: LifecycleState; providerHealthy: boolean; campaignApproved: boolean; suppressed: boolean; subscriptionActive: boolean; monthlyRemaining: number; mailboxRemaining: number; domainRemaining: number; liveSendingEnabled: boolean; preview: boolean };
export function enforceLiveSend(input: SendGateInput) { const reasons: string[] = []; if (input.mailboxState !== "LIVE_READY") reasons.push("MAILBOX_NOT_LIVE_READY"); if (input.domainState !== "LIVE_READY") reasons.push("DOMAIN_NOT_LIVE_READY"); if (!input.providerHealthy) reasons.push("PROVIDER_UNHEALTHY"); if (!input.campaignApproved) reasons.push("CAMPAIGN_NOT_APPROVED"); if (input.suppressed) reasons.push("RECIPIENT_SUPPRESSED"); if (!input.subscriptionActive) reasons.push("ENTITLEMENT_INVALID"); if (input.monthlyRemaining < 1) reasons.push("PLAN_SEND_LIMIT_REACHED"); if (input.mailboxRemaining < 1 || input.domainRemaining < 1) reasons.push("WARMUP_CAPACITY_EXHAUSTED"); if (!input.liveSendingEnabled || input.preview) reasons.push("LIVE_SENDING_DISABLED"); return { allowed: reasons.length === 0, code: reasons[0], reasons }; }

export function warmupDailyLimit(day: number) { if (day <= 3) return 5; if (day <= 7) return 10; if (day <= 14) return 15; if (day <= 21) return 25; if (day <= 28) return 30; return 35; }
