/* eslint-disable @typescript-eslint/no-explicit-any */
import Link from "next/link";
import { revalidatePath } from "next/cache";
import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getCurrentWorkspace } from "@/lib/workspaces/service";
import { addFollowUp, addNote, addTask, listActivityTimeline } from "@/lib/crm/activity-service";
import { archiveCrmRecord, createCompany, createContact, createLead, createOpportunity, getCompanyDetail, getContactDetail, getLeadDetail, getOpportunityDetail, listCompanies, listContacts, listLeads, listOpportunities, updateCompany, updateContact, updateLead, updateOpportunity, type RelatedType } from "@/lib/crm/service";
import { listDiagnostics, startDiagnosticFromRecord } from "@/lib/diagnostics/service";

type Module = "companies" | "contacts" | "leads" | "opportunities";
const labels = { companies: ["Company", "Companies"], contacts: ["Contact", "Contacts"], leads: ["Lead", "Leads"], opportunities: ["Opportunity", "Opportunities"] } as const;
const relatedTypes = { companies: "Company", contacts: "Contact", leads: "Lead", opportunities: "Opportunity" } as const;

function value(v: unknown) { return v == null || v === "" ? "—" : String(v); }
async function requireWorkspace() { const workspace = await getCurrentWorkspace(); if (!workspace) return null; return workspace; }

export async function CrmListPage({ module }: { module: Module }) {
  const workspace = await requireWorkspace();
  if (!workspace) return <EmptyWorkspace />;
  const records = module === "companies" ? await listCompanies(workspace.id) : module === "contacts" ? await listContacts(workspace.id) : module === "leads" ? await listLeads(workspace.id) : await listOpportunities(workspace.id);
  async function createAction(formData: FormData) { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; const input = Object.fromEntries(formData.entries()); if (module === "companies") await createCompany(workspace.id, input); if (module === "contacts") await createContact(workspace.id, input); if (module === "leads") await createLead(workspace.id, input); if (module === "opportunities") await createOpportunity(workspace.id, input); revalidatePath(`/dashboard/${module}`); }
  return <div className="space-y-6"><header className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-sm text-slate-500">Workspace-scoped CRM</p><h1 className="text-3xl font-semibold">{labels[module][1]}</h1><p className="mt-2 max-w-3xl text-slate-600">Create, review, update, archive, and connect records to diagnostics without exposing cross-workspace data.</p></div></header><Card><CardHeader><CardTitle>Create {labels[module][0].toLowerCase()}</CardTitle><CardDescription>New records are attached to {workspace.name} and stamped with the creating user.</CardDescription></CardHeader><form action={createAction} className="grid gap-3 p-6 pt-0 md:grid-cols-4"><Fields module={module} /><Button type="submit">Create record</Button></form></Card><Card><CardHeader><CardTitle>{records.length} records</CardTitle><CardDescription>Archived records remain visible with status for auditability; no destructive deletes are performed.</CardDescription></CardHeader><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="border-y bg-slate-50 text-slate-500"><tr><th className="p-3">Name</th><th className="p-3">Status</th><th className="p-3">Related</th><th className="p-3">Updated</th></tr></thead><tbody>{records.map((record: any) => <tr key={record.id} className="border-b"><td className="p-3 font-medium"><Link className="text-slate-900 hover:underline" href={`/dashboard/${module}/${record.id}`}>{record.name ?? `${record.firstName} ${record.lastName}`}</Link></td><td className="p-3">{record.status}</td><td className="p-3 text-slate-600">{record.company?.name ?? `${record.contacts?.length ?? record.opportunities?.length ?? 0} linked`}</td><td className="p-3 text-slate-500">{record.updatedAt.toLocaleDateString()}</td></tr>)}</tbody></table>{records.length === 0 ? <p className="p-6 text-sm text-slate-500">No records yet. Use the creation form to begin the CRM workflow.</p> : null}</div></Card></div>;
}

export async function CrmDetailPage({ module, id }: { module: Module; id: string }) {
  const workspace = await requireWorkspace();
  if (!workspace) return <EmptyWorkspace />;
  const record: any = module === "companies" ? await getCompanyDetail(workspace.id, id) : module === "contacts" ? await getContactDetail(workspace.id, id) : module === "leads" ? await getLeadDetail(workspace.id, id) : await getOpportunityDetail(workspace.id, id);
  const relatedType = relatedTypes[module] as RelatedType;
  const [timeline, diagnostics] = await Promise.all([listActivityTimeline(workspace.id, relatedType, id), listDiagnostics(workspace.id)]);
  const linkedDiagnostics = diagnostics.filter((item) => item.relatedType === relatedType && item.relatedId === id);
  async function updateAction(formData: FormData) { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; const input = Object.fromEntries(formData.entries()); if (module === "companies") await updateCompany(workspace.id, id, input); if (module === "contacts") await updateContact(workspace.id, id, input); if (module === "leads") await updateLead(workspace.id, id, input); if (module === "opportunities") await updateOpportunity(workspace.id, id, input); revalidatePath(`/dashboard/${module}/${id}`); }
  async function archiveAction() { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; await archiveCrmRecord(workspace.id, module, id); }
  async function diagnosticAction() { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; await startDiagnosticFromRecord(workspace.id, relatedType, id, `${labels[module][0]} diagnostic: ${record.name ?? `${record.firstName} ${record.lastName}`}`); }
  async function noteAction(formData: FormData) { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; await addNote(workspace.id, relatedType, id, Object.fromEntries(formData.entries())); revalidatePath(`/dashboard/${module}/${id}`); }
  async function taskAction(formData: FormData) { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; await addTask(workspace.id, relatedType, id, Object.fromEntries(formData.entries())); revalidatePath(`/dashboard/${module}/${id}`); }
  async function followUpAction(formData: FormData) { "use server"; const workspace = await requireWorkspace(); if (!workspace) return; await addFollowUp(workspace.id, relatedType, id, Object.fromEntries(formData.entries())); revalidatePath(`/dashboard/${module}/${id}`); }
  return <div className="space-y-6"><div><Link className="text-sm text-slate-500 hover:underline" href={`/dashboard/${module}`}>← Back to {labels[module][1]}</Link><h1 className="mt-2 text-3xl font-semibold">{record.name ?? `${record.firstName} ${record.lastName}`}</h1><p className="mt-2 text-slate-600">Executive-grade record view with scoped related records, activity, diagnostics, and archive-safe actions.</p></div><div className="grid gap-4 lg:grid-cols-3"><Card><CardHeader><CardTitle>Overview</CardTitle><CardDescription>Status: {record.status}. Created {record.createdAt.toLocaleDateString()}.</CardDescription></CardHeader><div className="space-y-2 p-6 pt-0 text-sm"><p>Workspace: {workspace.name}</p><p>Email/domain: {value(record.email ?? record.domain)}</p><p>Company: {value(record.company?.name)}</p><p>Amount: {value(record.amount)}</p></div></Card><Card><CardHeader><CardTitle>Related records</CardTitle><CardDescription>Only records from this workspace are shown.</CardDescription></CardHeader><div className="space-y-2 p-6 pt-0 text-sm text-slate-600"><p>Contacts: {record.contacts?.length ?? "—"}</p><p>Opportunities: {record.opportunities?.length ?? "—"}</p><p>Diagnostics: {linkedDiagnostics.length}</p></div></Card><Card><CardHeader><CardTitle>Actions</CardTitle><CardDescription>Archive requires explicit confirmation.</CardDescription></CardHeader><div className="space-y-3 p-6 pt-0"><form action={diagnosticAction}><Button type="submit">Start diagnostic</Button></form><form action={archiveAction}><Button type="submit" variant="outline">Archive record</Button></form></div></Card></div><Card><CardHeader><CardTitle>Edit overview</CardTitle><CardDescription>Updates are validated and audited before saving.</CardDescription></CardHeader><form action={updateAction} className="grid gap-3 p-6 pt-0 md:grid-cols-4"><Fields module={module} record={record} /><Button type="submit">Save changes</Button></form></Card><div className="grid gap-4 lg:grid-cols-3"><ActivityForm title="Add note" action={noteAction} field="body" /><ActivityForm title="Create task" action={taskAction} field="title" /><ActivityForm title="Create follow-up" action={followUpAction} field="title" /></div><Card><CardHeader><CardTitle>Activity timeline</CardTitle><CardDescription>Reverse chronological notes, tasks, follow-ups, diagnostic, and audit-facing CRM events.</CardDescription></CardHeader><div className="space-y-3 p-6 pt-0">{timeline.map((item) => <div key={`${item.kind}-${item.id}`} className="rounded-xl border p-4"><div className="flex justify-between gap-4"><p className="font-medium">{item.title}</p><p className="text-xs text-slate-500">{item.occurredAt.toLocaleString()}</p></div><p className="text-sm text-slate-600">{item.description ?? item.status ?? "Recorded activity"}</p></div>)}{timeline.length === 0 ? <p className="text-sm text-slate-500">No activity yet. Add a note, task, or follow-up to begin the operating history.</p> : null}</div></Card></div>;
}
function Fields({ module, record }: { module: Module; record?: any }) { if (module === "companies") return <><Input name="name" placeholder="Company name" defaultValue={record?.name} required /><Input name="domain" placeholder="Domain" defaultValue={record?.domain ?? ""} /><Input name="industry" placeholder="Industry" defaultValue={record?.industry ?? ""} /><Input name="employeeCount" placeholder="Employees" defaultValue={record?.employeeCount ?? ""} /></>; if (module === "contacts") return <><Input name="firstName" placeholder="First name" defaultValue={record?.firstName} required /><Input name="lastName" placeholder="Last name" defaultValue={record?.lastName} required /><Input name="email" placeholder="Email" defaultValue={record?.email ?? ""} /><Input name="title" placeholder="Title" defaultValue={record?.title ?? ""} /></>; if (module === "leads") return <><Input name="name" placeholder="Lead name" defaultValue={record?.name} required /><Input name="email" placeholder="Email" defaultValue={record?.email ?? ""} /><Input name="source" placeholder="Source" defaultValue={record?.source ?? ""} /><Input name="score" placeholder="Score" defaultValue={record?.score ?? ""} /></>; return <><Input name="name" placeholder="Opportunity name" defaultValue={record?.name} required /><Input name="amount" placeholder="Amount" defaultValue={record?.amount ?? ""} /><Input name="closeDate" placeholder="Close date YYYY-MM-DD" defaultValue={record?.closeDate?.toISOString().slice(0,10) ?? ""} /><Input name="companyId" placeholder="Company ID" defaultValue={record?.companyId ?? ""} /></>; }
function ActivityForm({ title, action, field }: { title: string; action: (formData: FormData) => Promise<void>; field: string }) { return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>Attached to this record and workspace.</CardDescription></CardHeader><form action={action} className="space-y-3 p-6 pt-0"><Input name={field} placeholder={title} required /><Input name="dueAt" placeholder="Due date (optional)" /><Button type="submit">Save</Button></form></Card>; }
function EmptyWorkspace() { return <Card><CardHeader><CardTitle>No active workspace</CardTitle><CardDescription>Create or join a workspace before using CRM workflows.</CardDescription></CardHeader></Card>; }
