import { Card, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { EmptyState } from "@/components/dashboard/empty-state";

export type Metric = { label: string; value: string; detail: string };
export type ModuleEmptyState = { title: string; description: string; nextAction: string; href: string; cta: string; flow: string };
export function ModulePage({ title, description, metrics, workflows, cta = "Create record", emptyState }: { title: string; description: string; metrics: Metric[]; workflows: string[]; cta?: string; emptyState?: ModuleEmptyState }) {
  return <div className="space-y-6"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><h1 className="text-3xl font-semibold tracking-tight">{title}</h1><p className="mt-2 max-w-3xl text-slate-600 dark:text-slate-300">{description}</p></div><Button>{cta}</Button></div><div className="grid gap-4 md:grid-cols-3">{metrics.map((metric) => <Card key={metric.label}><CardHeader><CardDescription>{metric.label}</CardDescription><CardTitle className="text-3xl">{metric.value}</CardTitle><CardDescription>{metric.detail}</CardDescription></CardHeader></Card>)}</div><Card><CardHeader><CardTitle>Operational workflow</CardTitle><CardDescription>Foundation actions available in this module.</CardDescription></CardHeader><div className="grid gap-3 p-6 pt-0 md:grid-cols-2">{workflows.map((workflow, index) => <div key={workflow} className="rounded-xl border bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-900"><div className="text-sm font-semibold text-slate-400">Step {index + 1}</div><div className="font-medium text-slate-800 dark:text-slate-100">{workflow}</div></div>)}</div></Card>{emptyState ? <EmptyState {...emptyState} /> : <Card className="border-dashed"><CardHeader><CardTitle>Empty state</CardTitle><CardDescription>No workspace records are loaded until a Clerk-authenticated member creates data through server-side workspace-scoped services.</CardDescription></CardHeader></Card>}</div>;
}
