import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import { BarChart3, Brain, Briefcase, ClipboardList, FileText, Home, Kanban, Settings, Users } from "lucide-react";
import { hasClerkPublishableKey } from "@/lib/auth/clerk-build";

const nav = [
  ["Dashboard", "/dashboard", Home], ["CRM", "/dashboard/crm", Users], ["Leads", "/dashboard/leads", Users], ["Contacts", "/dashboard/contacts", Users], ["Companies", "/dashboard/companies", Briefcase], ["Opportunities", "/dashboard/opportunities", Kanban], ["Pipeline", "/dashboard/pipeline", Kanban], ["Tasks", "/dashboard/tasks", ClipboardList], ["Diagnostics", "/dashboard/diagnostics", Brain], ["Analysis", "/dashboard/analysis", BarChart3], ["ROI", "/dashboard/roi", BarChart3], ["Reports", "/dashboard/reports", FileText], ["Roadmaps", "/dashboard/roadmaps", Kanban], ["Proposals", "/dashboard/proposals", FileText], ["Projects", "/dashboard/projects", ClipboardList], ["Knowledge", "/dashboard/knowledge", Brain], ["AI Logs", "/dashboard/ai-executions", Brain], ["Audit", "/dashboard/audit", FileText], ["Admin", "/dashboard/admin", Settings]
] as const;
export function DashboardShell({ children }: { children: React.ReactNode }) {
  return <div className="flex min-h-screen bg-slate-50"><aside className="hidden w-72 border-r bg-white p-5 lg:block"><Link href="/dashboard" className="mb-6 block text-xl font-semibold">Quantum Reach</Link><div className="mb-4 rounded-2xl border bg-slate-50 p-3 text-sm"><div className="font-medium">Workspace</div><div className="text-slate-500">Select and scope records</div></div><nav className="space-y-1">{nav.map(([label, href, Icon]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2 text-sm text-slate-700 hover:bg-slate-100"><Icon className="h-4 w-4" />{label}</Link>)}</nav></aside><div className="flex flex-1 flex-col"><header className="flex h-16 items-center justify-between border-b bg-white px-6"><div><p className="text-sm text-slate-500">Enterprise operating system</p><p className="font-medium">CRM → Diagnostic → Analysis → Execution</p></div>{hasClerkPublishableKey ? <UserButton /> : <Link href="/sign-in" className="text-sm text-slate-600">Sign in</Link>}</header><main className="flex-1 p-6">{children}</main></div></div>;
}
