import Link from "next/link";
import { UserButton } from "@clerk/nextjs";
import { BarChart3, Brain, Briefcase, ClipboardList, FileText, Home, Kanban, CreditCard, Settings, ShieldCheck, Users, Video } from "lucide-react";
import { hasClerkPublishableKey } from "@/lib/auth/clerk-build";
import { ThemeToggle } from "@/components/dashboard/theme-toggle";

const nav = [
  ["Dashboard", "/dashboard", Home], ["CRM", "/dashboard/crm", Users], ["Leads", "/dashboard/leads", Users], ["Contacts", "/dashboard/contacts", Users], ["Companies", "/dashboard/companies", Briefcase], ["Opportunities", "/dashboard/opportunities", Kanban], ["Pipeline", "/dashboard/pipeline", Kanban], ["Tasks", "/dashboard/tasks", ClipboardList], ["Outreach", "/dashboard/outreach", Users], ["Calls", "/dashboard/calls", Brain], ["Meetings", "/dashboard/meetings", Video], ["Diagnostics", "/dashboard/diagnostics", Brain], ["Analysis", "/dashboard/analysis", BarChart3], ["ROI", "/dashboard/roi", BarChart3], ["Reports", "/dashboard/reports", FileText], ["Roadmaps", "/dashboard/roadmaps", Kanban], ["Proposals", "/dashboard/proposals", FileText], ["Projects", "/dashboard/projects", ClipboardList], ["Knowledge", "/dashboard/knowledge", Brain], ["AI Logs", "/dashboard/ai-executions", Brain], ["Audit", "/dashboard/audit", FileText], ["Billing", "/dashboard/billing", CreditCard], ["Settings", "/dashboard/settings", Settings], ["Admin", "/dashboard/admin", Settings], ["Operator", "/dashboard/operator", ShieldCheck]
] as const;
export function DashboardShell({ children }: { children: React.ReactNode }) {
  return <div className="flex min-h-screen bg-slate-50 dark:bg-slate-950"><aside className="hidden w-72 border-r bg-white p-5 dark:border-slate-800 dark:bg-slate-950 lg:block"><Link href="/dashboard" className="mb-6 block text-xl font-semibold">Quantum Reach</Link><div className="mb-4 rounded-2xl border bg-slate-50 p-3 text-sm dark:border-slate-800 dark:bg-slate-900"><div className="font-medium">Workspace</div><div className="text-slate-500 dark:text-slate-400">Select and scope records</div></div><nav className="space-y-1">{nav.map(([label, href, Icon]) => <Link key={href} href={href} className="flex items-center gap-3 rounded-xl px-3 py-2 text-sm text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-900"><Icon className="h-4 w-4" />{label}</Link>)}</nav></aside><div className="flex flex-1 flex-col"><header className="flex h-16 items-center justify-between border-b bg-white px-6 dark:border-slate-800 dark:bg-slate-950/95"><div><p className="text-sm text-slate-500 dark:text-slate-400">Enterprise operating system</p><p className="font-medium">CRM → Diagnostic → Analysis → Execution</p></div><div className="flex items-center gap-3"><ThemeToggle />{hasClerkPublishableKey ? <UserButton /> : <Link href="/sign-in" className="text-sm text-slate-600 dark:text-slate-300">Sign in</Link>}</div></header><main className="flex-1 p-6">{children}</main></div></div>;
}
