import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {normalizeAffiliateCode,validateAffiliateCode,canTransitionCode} from "@/lib/affiliates/service";
const source=(path:string)=>readFileSync(path,"utf8");
describe("affiliate membership period foundation",()=>{
 it("normalizes codes case-insensitively and rejects malformed values",()=>{expect(normalizeAffiliateCode("  Partner-One ")).toBe("PARTNER-ONE");expect(()=>validateAffiliateCode("!!")).toThrow("AFFILIATE_CODE_INVALID")});
 it("makes retirement irreversible",()=>{expect(canTransitionCode("RETIRED","ACTIVE")).toBe(false);expect(canTransitionCode("SUSPENDED","ACTIVE")).toBe(true)});
 it("keeps affiliate models separate from coupons and payment economics",()=>{const schema=source("prisma/schema.prisma");const block=schema.slice(schema.indexOf("model AffiliateParticipant"),schema.indexOf("model AffiliateClick"));expect(block).not.toMatch(/CommercialCoupon|CouponRedemption|stripeCustomerId|payoutMethod/i);expect(block).toContain("AffiliateReferralAttribution");expect(block).toContain("partnerVisible")});
 it("uses exact membership periods and codes for attribution",()=>{const schema=source("prisma/schema.prisma");expect(schema).toContain("affiliateMembershipPeriodId");expect(schema).toContain("affiliateCodeId");expect(schema).toMatch(/normalizedCode\s+String/);});
 it("locks attribution during canonical order finalization",()=>{const journey=source("lib/customer-journey/service.ts");expect(journey).toContain("lockAffiliateAttribution");expect(journey).toContain("customerUserId: userId")});
 it("public referral capture is opaque, safe, and does not create coupons",()=>{const route=source("app/r/[affiliateCode]/page.tsx");expect(route).toContain("captureAffiliateAttribution");expect(route).toContain('redirect("/start?referral=captured")');expect(route).toContain("saveDraftSelection");expect(route).not.toMatch(/applyCoupon|CouponRedemption|commission|payout/i);expect(route).not.toContain("membershipPeriodId")});
 it("operator management is protected and never reactivates ended periods",()=>{const actions=source("app/platform/affiliates/actions.ts"),page=source("app/platform/affiliates/page.tsx");expect(actions).toContain("requireOperatorAccess");expect(actions).toContain("workspaceId:null");expect(page).toContain("Ended memberships and retired codes cannot be reactivated.");expect(page).not.toContain("Reactivate")});
 it("adds database guards for open memberships and locked attribution",()=>{const migration=source("prisma/migrations/20260801000000_affiliate_membership_periods/migration.sql");expect(migration).toContain("AffiliateMembershipPeriod_one_open_idx");expect(migration).toContain("AffiliateReferralAttribution_one_locked_order_idx");expect(migration).toContain("AffiliateMembershipCode_normalizedCode_key")});
 it("preserves coupon pricing and accepted snapshots",()=>{const service=source("lib/affiliates/service.ts");expect(service).not.toMatch(/commercialCoupon|couponRedemption|acceptedCouponSnapshot|chargeLine/i)});
});
