import {describe,expect,it} from "vitest";
import {readFileSync} from "node:fs";
import {generateAffiliateCode} from "@/lib/affiliates/service";
const source=(path:string)=>readFileSync(path,"utf8");
describe("automatic subscriber affiliate enrollment",()=>{
 it("generates opaque cryptographic customer-facing codes",()=>{const codes=new Set(Array.from({length:64},()=>generateAffiliateCode()));expect(codes.size).toBe(64);for(const code of codes)expect(code).toMatch(/^QR-[A-HJ-NP-Z2-9]{8}$/);const service=source("lib/affiliates/service.ts");expect(service).toContain('import { randomBytes } from "node:crypto"');expect(service).not.toContain("Math.random")});
 it("hooks verified fulfillment and authoritative Stripe subscription status",()=>{const fulfillment=source("lib/customer-journey/service.ts"),stripe=source("lib/stripe/webhooks.ts");expect(fulfillment).toContain("ensureAffiliateMembershipForActiveSubscriber");expect(fulfillment).toContain('order.paymentMethod !== "COMPLIMENTARY"');expect(stripe).toContain("reconcileAffiliateMembershipForSubscriptionStatus");expect(stripe).toContain("correlationId: eventId, status")});
 it("does not end access for scheduled cancellation or past due state",()=>{const service=source("lib/affiliates/service.ts");expect(service).toContain('["ACTIVE", "TRIALING"]');expect(service).toContain('["CANCELED", "UNPAID"]');expect(service).not.toMatch(/PAST_DUE.*endAffiliateMembershipForSubscriberAccessEnd/)});
 it("removes manual enrollment and code entry from the operator UI",()=>{const page=source("app/platform/affiliates/page.tsx"),actions=source("app/platform/affiliates/actions.ts");expect(page).toContain("Affiliate accounts are created automatically when customers become active subscribers");expect(page).not.toContain("Create participant");expect(page).not.toContain("New unique code");expect(page).not.toContain('name="code"');expect(actions).not.toContain("createParticipantAction");expect(actions).not.toContain("startMembershipAction");expect(page).toContain("SUSPEND");expect(page).toContain("RESUME")});
 it("provides an ownership-scoped read-only subscriber view without payout data",()=>{const page=source("app/dashboard/partner/referrals/page.tsx");expect(page).toContain("userId: user.id");expect(page).toContain("readOnly");expect(page).toContain("Referral code");expect(page).toContain("https://www.quantumreach.app");expect(page).toContain("/r/");expect(page).toContain("CopyValueButton");expect(page).not.toMatch(/commission|payout|earnings/i);expect(page).not.toContain("participant.id")});
 it("exposes partner hub from automatic membership without legacy partner env gate",()=>{const page=source("app/dashboard/partner/page.tsx");expect(page).toContain("affiliateParticipant.findUnique");expect(page).toContain("/dashboard/partner/referrals");expect(page).not.toContain("requirePartnerAccess");expect(page).not.toMatch(/process\.env\.AFFILIATE_ENABLED/)});
 it("keeps coupon and affiliate systems separate",()=>{const service=source("lib/affiliates/service.ts");expect(service).not.toMatch(/CommercialCoupon|CouponRedemption|acceptedCouponSnapshot|charge-lines/)});
});
