import { describe,expect,it } from "vitest";import { readFileSync } from "node:fs";import { buildAcquisitionChargeSummary } from "@/lib/commercial/charge-lines";import { applyCouponToSummary,couponEligibility,normalizeCouponCode,validateCouponConfiguration } from "@/lib/commercial/coupons";
const base=buildAcquisitionChargeSummary("GROWTH_SENDER_PACKAGE",{productKey:"PRIORITY_SETUP",displayName:"Head of the line",amountCents:25000});
const rule=(overrides:any={})=>({id:"c1",code:"SAVE",normalizedCode:"SAVE",displayName:"Save",active:true,validFrom:null,expiresAt:null,retiredAt:null,percentageOff:100,recurringDiscountMonths:null,trialDays:null,minimumOrderAmountCents:0,maximumTotalRedemptions:null,maximumRedemptionsPerCustomer:null,stripeCouponId:null,stripePromotionCodeId:null,version:1,eligiblePackageKeys:[],eligibleProductKeys:[],eligibleChargeTypes:["IMPLEMENTATION_FEE"],...overrides});
describe("commercial coupons",()=>{
 it("normalizes codes case-insensitively",()=>expect(normalizeCouponCode(" free Setup ")).toBe("FREESETUP"));
 it("validates percentages, durations, trials, and money",()=>{expect(()=>validateCouponConfiguration({code:"X",percentageOff:0})).toThrow("COUPON_PERCENTAGE_INVALID");expect(()=>validateCouponConfiguration({code:"X",percentageOff:101})).toThrow();expect(()=>validateCouponConfiguration({code:"X",percentageOff:10,recurringDiscountMonths:0})).toThrow("COUPON_RECURRING_DURATION_INVALID");expect(()=>validateCouponConfiguration({code:"X",percentageOff:10,trialDays:0})).toThrow("COUPON_TRIAL_DAYS_INVALID");});
 it.each([[{active:false},"Code is invalid."],[{validFrom:new Date("2099-01-01")},"Code is not active yet."],[{expiresAt:new Date("2020-01-01")},"Code has expired."],[{eligiblePackageKeys:["LAUNCH_SENDER_PACKAGE"]},"Code is not valid for this package."],[{minimumOrderAmountCents:999999},"This code no longer applies to the selected order."],[{maximumTotalRedemptions:1},"Code has reached its redemption limit."]])("rejects ineligible coupon %#",(change,message)=>expect(couponEligibility(rule(change),base,new Date(),{total:1,customer:0})).toBe(message));
 it("enforces per-customer redemption limits",()=>expect(couponEligibility(rule({maximumRedemptionsPerCustomer:1}),base,new Date(),{total:0,customer:1})).toBe("This code has already been used for this account."));
 it("makes Growth FREESETUP total $847 without discounting priority",()=>{const out=applyCouponToSummary(base,rule());expect(out.todaySubtotalCents).toBe(234700);expect(out.totalCouponSavingsCents).toBe(150000);expect(out.todayTotalCents).toBe(84700);expect(out.lines.find(x=>x.chargeType==="SETUP_PRIORITY_SURCHARGE")?.netAmountCents).toBe(25000);});
 it("makes FREEMONTH total $1,750 with priority and resumes after one period",()=>{const out=applyCouponToSummary(base,rule({eligibleChargeTypes:["PACKAGE_FIRST_MONTH","PACKAGE_RECURRING"],recurringDiscountMonths:1}));expect(out.todayTotalCents).toBe(175000);expect(out.promotionalRecurringCents).toBe(0);expect(out.fullPriceResumesAfterPeriods).toBe(1);});
 it("makes FREESETUP30 total $250 and supports an explicit 30 day trial",()=>{const out=applyCouponToSummary(base,rule({eligibleChargeTypes:["IMPLEMENTATION_FEE","PACKAGE_FIRST_MONTH"],recurringDiscountMonths:1,trialDays:30}));expect(out.todayTotalCents).toBe(25000);expect(out.trialEndsAt).toBeTruthy();});
 it("applies SAVE20X3 deterministically to first and recurring package lines",()=>{const out=applyCouponToSummary(base,rule({percentageOff:20,eligibleChargeTypes:["PACKAGE_FIRST_MONTH","PACKAGE_RECURRING"],recurringDiscountMonths:3}));expect(out.todayTotalCents).toBe(222760);expect(out.promotionalRecurringCents).toBe(47760);expect(out.fullPriceResumesAfterPeriods).toBe(3);});
 it("supports 10 percent recurring for 12 months and nearest-cent rounding",()=>{const out=applyCouponToSummary(base,rule({percentageOff:10,eligibleChargeTypes:["PACKAGE_FIRST_MONTH","PACKAGE_RECURRING"],recurringDiscountMonths:12}));expect(out.promotionalRecurringCents).toBe(53730);expect(out.lines.every(x=>x.netAmountCents>=0&&Number.isInteger(x.netAmountCents))).toBe(true);});
 it("discounts Head of the line only when targeted by type and product",()=>{const out=applyCouponToSummary(base,rule({percentageOff:50,eligibleChargeTypes:["SETUP_PRIORITY_SURCHARGE"],eligibleProductKeys:["PRIORITY_SETUP"]}));expect(out.lines.find(x=>x.productKey==="PRIORITY_SETUP")?.netAmountCents).toBe(12500);});
 it("keeps coupons separate from affiliates and protects operator mutations",()=>{const schema=readFileSync("prisma/schema.prisma","utf8");const models=schema.slice(schema.indexOf("model CommercialCoupon"),schema.indexOf("model CouponRedemption")+800);expect(models).not.toMatch(/affiliate|commission|payout/i);const actions=readFileSync("app/platform/coupons/actions.ts","utf8");expect(actions).toContain("requireOperatorAccess");expect(actions).toContain("auditLog.create");});
 it("persists one active coupon, explicit replacement, removal and immutable snapshots",()=>{const service=readFileSync("lib/commercial/coupons.ts","utf8");expect(service).toContain("A coupon is already applied. Remove it or explicitly replace it.");expect(service).toContain('status:"RELEASED"');expect(service).toContain("acceptedCouponSnapshot");expect(service).not.toContain("affiliateAttribution");});
 it("prevents Stripe divergence without an explicit mapping",()=>{const stripe=readFileSync("lib/stripe/commerce.ts","utf8");expect(stripe).toContain("Accepted coupon requires an explicit Stripe mapping before checkout.");expect(stripe).toContain("promotion_code");expect(stripe).toContain("trial_period_days");});
});
