import { beforeEach, describe, expect, it } from "vitest";
import { DEFAULT_ADDONS, DEFAULT_COMMERCIAL_PLANS, FULL_PLATFORM_MODULES, planEntitlements, projectedEconomics, snapshotAcceptedTerms } from "@/lib/commercial/packages";
import { DEFAULT_WARMUP_POLICY, enforceLiveSend, evaluateWarmup, warmupDailyLimit, type HealthInput } from "@/lib/sending-infrastructure/warmup";
import { authorizeAISelection, credentialResponse, decryptAICredential, encryptAICredential, maskedCredential } from "@/lib/ai/workspace-providers";

const healthy: HealthInput = { state: "WARMING", elapsedDays: 21, delivered: 190, sent: 195, hardBounces: 1, complaints: 0, consecutiveHealthyDays: 7, spf: true, dkim: true, dmarc: true, outboundTest: true, inboundTest: true, bouncePipeline: true, complaintPipeline: true, suppressionPipeline: true, providerHealthy: true };

describe("commercial package control plane", () => {
  it("ships three full-platform plans with Growth recommended and configurable launch defaults", () => { expect(DEFAULT_COMMERCIAL_PLANS.map(p => p.name)).toEqual(["Launch", "Growth", "Scale"]); expect(DEFAULT_COMMERCIAL_PLANS.find(p => p.recommended)?.name).toBe("Growth"); expect(FULL_PLATFORM_MODULES).toContain("CRM"); expect(DEFAULT_COMMERCIAL_PLANS.map(p => [p.monthlyCents, p.setupCents])).toEqual([[29700,75000],[59700,150000],[99700,250000]]); expect(planEntitlements(DEFAULT_COMMERCIAL_PLANS[0]).COMPLETE_PLATFORM_INCLUDED).toBe(true); });
  it("provides all configurable add-ons and immutable historical snapshots", () => { expect(DEFAULT_ADDONS).toHaveLength(10); const accepted = snapshotAcceptedTerms(DEFAULT_COMMERCIAL_PLANS[0]); DEFAULT_COMMERCIAL_PLANS[0].monthlyCents = 30000; expect(accepted.monthlyCents).toBe(29700); DEFAULT_COMMERCIAL_PLANS[0].monthlyCents = 29700; });
  it("keeps planning economics clearly labeled", () => expect(projectedEconomics(DEFAULT_COMMERCIAL_PLANS[1])).toMatchObject({ label: "Planning estimate", projectedCogsCents: 14300 }));
});

describe("deterministic warm-up and live-send enforcement", () => {
  it("requires duration, samples, healthy days, authentication and deterministic score", () => { expect(evaluateWarmup(healthy).action).toBe("PROMOTE_LIVE"); expect(evaluateWarmup({ ...healthy, elapsedDays: 30, delivered: 10, sent: 10 }).reasons).toContain("MINIMUM_SAMPLE_NOT_MET"); expect(evaluateWarmup({ ...healthy, dkim: false })).toMatchObject({ action: "PAUSE", eligible: false }); });
  it("holds or pauses for bounce, complaint and provider health and demotes live mailboxes", () => { expect(evaluateWarmup({ ...healthy, state: "LIVE_READY", hardBounces: 10 }).action).toBe("DEMOTE_LIVE"); expect(evaluateWarmup({ ...healthy, complaints: 1 }).reasons).toContain("COMPLAINT_EMERGENCY_THRESHOLD"); expect(evaluateWarmup({ ...healthy, providerHealthy: false }).reasons).toContain("PROVIDER_UNHEALTHY"); });
  it("keeps scores explainable, simulation labeled and schedule bounded", () => { const result = evaluateWarmup({ ...healthy, isSimulated: true, scenarioId: "QUANTUM_REACH_WARMUP_VALIDATION" }); expect(result.score).toBeGreaterThanOrEqual(DEFAULT_WARMUP_POLICY.promotionScore); expect(result.components.authentication.explanation).toContain("SPF"); expect(result.isSimulated).toBe(true); expect([warmupDailyLimit(1), warmupDailyLimit(29)]).toEqual([5,35]); });
  it("technically blocks pre-readiness, capacity exhaustion and Preview", () => { const base = { mailboxState: "LIVE_READY", domainState: "LIVE_READY", providerHealthy: true, campaignApproved: true, suppressed: false, subscriptionActive: true, monthlyRemaining: 10, mailboxRemaining: 10, domainRemaining: 10, liveSendingEnabled: true, preview: false } as const; expect(enforceLiveSend(base).allowed).toBe(true); expect(enforceLiveSend({ ...base, mailboxState: "WARMING" }).code).toBe("MAILBOX_NOT_LIVE_READY"); expect(enforceLiveSend({ ...base, preview: true }).reasons).toContain("LIVE_SENDING_DISABLED"); expect(enforceLiveSend({ ...base, domainRemaining: 0 }).reasons).toContain("WARMUP_CAPACITY_EXHAUSTED"); });
});

describe("BYO AI security and authorization", () => { beforeEach(() => { process.env.AI_CREDENTIAL_ENCRYPTION_KEY = Buffer.alloc(32, 7).toString("base64"); }); it("uses authenticated encryption and never returns plaintext", () => { const plaintext = "sk-workspace-secret", encrypted = encryptAICredential(plaintext); expect(encrypted).not.toContain(plaintext); expect(decryptAICredential(encrypted)).toBe(plaintext); expect(credentialResponse({ id: "1", provider: "OPENAI", maskedKey: maskedCredential(plaintext), enabled: true, encryptedSecret: encrypted })).not.toHaveProperty("encryptedSecret"); }); it("allows only enabled administrator-approved provider/model choices", () => { expect(authorizeAISelection({ provider: "OPENAI", model: "gpt-4.1-mini", enabled: true, allowedModels: ["gpt-4.1-mini"], clientAuthorized: true }).subscriberPaid).toBe(true); expect(() => authorizeAISelection({ provider: "OPENAI", model: "gpt-4.1", enabled: true, allowedModels: ["gpt-4.1-mini"], clientAuthorized: true })).toThrow("AI_MODEL_NOT_ALLOWED"); expect(() => authorizeAISelection({ provider: "GEMINI", model: "gemini-2.5-flash", enabled: true, allowedModels: ["gemini-2.5-flash"], clientAuthorized: false })).toThrow("AI_CLIENT_NOT_AUTHORIZED"); }); });
