import { describe, expect, it } from "vitest";
import { readFileSync } from "node:fs";
const source = (path: string) => readFileSync(path, "utf8");
describe("phase 9A native meeting MVP", () => {
  it("adds workspace-scoped meeting models, enums, and a non-destructive migration", () => { const schema=source("prisma/schema.prisma"), migration=source("prisma/migrations/20260613152000_native_meetings/migration.sql"); expect(schema).toContain("model MeetingRoom"); expect(schema).toContain("workspaceId"); expect(schema).toContain("model MeetingParticipant"); expect(schema).toContain("model MeetingInvitation"); expect(schema).toContain("model MeetingEvent"); expect(migration).toContain("CREATE TABLE \"MeetingRoom\""); expect(migration).toContain("ALTER TYPE \"CallProvider\" ADD VALUE IF NOT EXISTS 'QUANTUM_REACH_MEETINGS'"); });
  it("keeps LiveKit token generation server-only and protects secrets", () => { const lk=source("lib/meetings/livekit.ts"), client=source("components/meetings/meeting-room-client.tsx"); expect(lk).toContain('import "server-only"'); expect(lk).toContain("LIVEKIT_API_SECRET"); expect(lk).toContain("roomAdmin: isHost"); expect(lk).toContain("exp = now + 60 * 20"); expect(client).not.toContain("LIVEKIT_API_SECRET"); expect(client).not.toContain("JSON.stringify(data)"); });
  it("validates workspace scoped meeting list/detail and CRM links", () => { const svc=source("lib/meetings/service.ts"); expect(svc).toContain("export async function listMeetingRooms(workspaceId: string)"); expect(svc).toContain("where: { workspaceId }"); expect(svc).toContain("export async function getMeetingRoom(workspaceId: string, id: string)"); expect(svc).toContain("where: { id, workspaceId }"); expect(svc).toContain("Linked CRM or call record is not available in this workspace."); });
  it("implements invitation hash validation, revocation, expiration, and guest-only join", () => { const svc=source("lib/meetings/service.ts"), pub=source("app/meet/[slug]/page.tsx"); expect(svc).toContain("generateInvitationToken()"); expect(svc).toContain("hashInvitationToken(token)"); expect(svc).toContain("revokedAt: null"); expect(svc).toContain("expiresAt: { gt: new Date() }"); expect(pub).toContain("Guests only receive meeting access"); });
  it("provides dashboard routes, navigation, prejoin controls, lifecycle, and event tracking", () => { const nav=source("components/dashboard/shell.tsx"), page=source("components/dashboard/meeting-pages.tsx"), client=source("components/meetings/meeting-room-client.tsx"); expect(nav).toContain("/dashboard/meetings"); expect(page).toContain("Open room"); expect(page).toContain("End meeting"); expect(page).toContain("Create guest invitation"); expect(client).toContain("Microphone"); expect(client).toContain("Camera"); expect(client).toContain("Share screen"); expect(client).toContain("participant count".replace("participant count", "Participants:")); });
  it("documents environment and deployment", () => { const env=source(".env.example"), docs=source("docs/phase-9a-native-meeting-mvp.md"); expect(env).toContain('LIVEKIT_URL=""'); expect(env).toContain('LIVEKIT_API_KEY=""'); expect(env).toContain('LIVEKIT_API_SECRET=""'); expect(docs).toContain("npm run prisma:deploy"); expect(docs).toContain("defers automatic CallSession creation"); });
});
