import { beforeEach, describe, expect, it, vi } from "vitest";
const prisma = {
  suppressionListEntry: { count: vi.fn(), upsert: vi.fn(), findMany: vi.fn() }, emailSend: { count: vi.fn(), create: vi.fn(), update: vi.fn() }, emailRecipient: { findUnique: vi.fn(), create: vi.fn() }, emailEvent: { create: vi.fn() }, contact: { count: vi.fn(), create: vi.fn(), findFirst: vi.fn(), findMany: vi.fn(), update: vi.fn() }, contactImportBatch: { create: vi.fn(), findFirst: vi.fn(), update: vi.fn() }, contactImportRow: { update: vi.fn() }, company: { create: vi.fn(), upsert: vi.fn(), findFirst: vi.fn(), update: vi.fn() }, workspace: { findUnique: vi.fn() }, outboundCampaignJob: { findUnique: vi.fn(), updateMany: vi.fn() }, emailCampaign: { findFirst: vi.fn(), update: vi.fn() }, schedulingPage: { findUnique: vi.fn() }, booking: { count: vi.fn(), create: vi.fn() }, activity: { create: vi.fn() }, researchRun: { create: vi.fn(), count: vi.fn() }, interviewQuestionSet: { create: vi.fn() }, proposal: { create: vi.fn(), findFirst: vi.fn(), update: vi.fn() }, contract: { create: vi.fn(), update: vi.fn() }, contractSigner: { create: vi.fn(), findUnique: vi.fn() }, contractSignature: { count: vi.fn(), create: vi.fn() }, contractAuditEvent: { create: vi.fn() }, contractDocumentArtifact: { create: vi.fn() }, clientWorkspaceProvisioningRequest: { create: vi.fn() }, workspaceSubscription: { findUnique: vi.fn() }, emailCampaign_count: { count: vi.fn() }
};
vi.mock("@/lib/db/prisma", () => ({ prisma }));

describe("Revenue OS foundation", () => {
  beforeEach(() => { vi.clearAllMocks(); delete process.env.EMAIL_SENDING_ENABLED; delete process.env.EMAIL_SANDBOX_MODE; delete process.env.RESEARCH_ENABLED; delete process.env.BILLING_ENABLED; prisma.suppressionListEntry.count.mockResolvedValue(0); prisma.suppressionListEntry.findMany.mockResolvedValue([]); prisma.emailSend.count.mockResolvedValue(0); prisma.emailSend.create.mockResolvedValue({ id: "send_1" }); prisma.emailSend.update.mockImplementation(async ({ data }) => ({ id: "send_1", ...data })); prisma.emailEvent.create.mockResolvedValue({ id: "event_1" }); prisma.activity.create.mockResolvedValue({ id: "act_1" }); prisma.contract.update.mockResolvedValue({ id: "ct1" }); prisma.clientWorkspaceProvisioningRequest.create.mockResolvedValue({ id: "pr1" }); prisma.contractDocumentArtifact.create.mockResolvedValue({ id: "art1" }); prisma.contractAuditEvent.create.mockResolvedValue({ id: "audit1" }); prisma.contact.findMany.mockResolvedValue([]); prisma.contact.update.mockResolvedValue({ id: "c1" }); prisma.workspace.findUnique.mockResolvedValue({ settings: {} }); prisma.company.findFirst.mockResolvedValue(null); prisma.outboundCampaignJob.findUnique.mockResolvedValue(null); prisma.outboundCampaignJob.updateMany.mockResolvedValue({ count: 0 }); });
  it("disabled provider never sends live email", async () => { const { getEmailProvider } = await import("@/lib/revenue-os/email"); const provider = getEmailProvider(); expect(provider.isReady()).toBe(false); await expect(provider.send({ workspaceId: "w1", to: "a@example.com", subject: "x", html: "y" })).resolves.toMatchObject({ sent: false }); });
  it("suppression blocks sends", async () => { prisma.suppressionListEntry.count.mockResolvedValue(1); const { queueOrSendEmail } = await import("@/lib/revenue-os/email"); await queueOrSendEmail({ workspaceId: "w1", to: "a@example.com", subject: "Hi", html: "Body" }); expect(prisma.emailSend.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: "BLOCKED_SUPPRESSED" }) })); });
  it("unsubscribe creates suppression and safe event", async () => { prisma.emailRecipient.findUnique.mockResolvedValue({ workspaceId: "w1", email: "A@Example.com", contactId: "c1" }); const { unsubscribeByToken } = await import("@/lib/revenue-os/email"); await unsubscribeByToken("tok"); expect(prisma.suppressionListEntry.upsert).toHaveBeenCalledWith(expect.objectContaining({ create: expect.objectContaining({ reason: "UNSUBSCRIBED", email: "a@example.com" }) })); });
  it("Instantly unsubscribe token suppresses and skips queued jobs", async () => { prisma.outboundCampaignJob.findUnique.mockResolvedValue({ workspaceId: "w1", email: "one@x.com", contactId: "c1" }); const { unsubscribeByToken } = await import("@/lib/revenue-os/email"); await unsubscribeByToken("instantly-tok"); expect(prisma.suppressionListEntry.upsert).toHaveBeenCalledWith(expect.objectContaining({ create: expect.objectContaining({ reason: "UNSUBSCRIBED", email: "one@x.com" }) })); expect(prisma.outboundCampaignJob.updateMany).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ status: "skipped", skipReason: "UNSUBSCRIBED" }) })); expect(prisma.emailRecipient.findUnique).not.toHaveBeenCalled(); });
  it("bounce and complaint events suppress contacts", async () => { const { handleSesEvent } = await import("@/lib/revenue-os/email"); await handleSesEvent({ workspaceId: "w1", type: "complaint", email: "b@example.com" }); expect(prisma.suppressionListEntry.upsert).toHaveBeenCalledWith(expect.objectContaining({ create: expect.objectContaining({ reason: "COMPLAINT" }) })); });
  it("contact import validates email, dedupe, suppression, and attestation", async () => { const { validateImportRows, commitImportBatch } = await import("@/lib/revenue-os/imports"); const rows = await validateImportRows("w1", [{ email: "bad" }, { email: "dup@example.com", firstName: "A" }, { email: "dup@example.com", firstName: "B" }]); expect(rows[0].issues).toContain("invalid_email"); expect(rows[2].issues).toContain("duplicate_in_upload"); await expect(commitImportBatch("w1", "batch", false)).rejects.toThrow("Compliance attestation"); });
  it("campaign compliance gate requires sender, address, unsubscribe, and clean list", async () => { const { evaluateCampaignCompliance } = await import("@/lib/revenue-os/campaigns"); prisma.emailCampaign.findFirst.mockResolvedValue({ recipients: [], steps: [{ body: "hello" }] }); const result = await evaluateCampaignCompliance("w1", "camp"); expect(result.approved).toBe(false); expect(result.failures).toContain("sender_identity_required"); expect(result.failures).toContain("unsubscribe_token_required"); });
  it("public booking creates contact and blocks unavailable slots", async () => { const { createPublicBooking } = await import("@/lib/revenue-os/scheduling"); prisma.schedulingPage.findUnique.mockResolvedValue({ id: "p1", workspaceId: "w1", status: "ACTIVE", durationMinutes: 30 }); prisma.booking.count.mockResolvedValueOnce(0).mockResolvedValueOnce(1); prisma.contact.create.mockResolvedValue({ id: "c1", companyId: null }); prisma.booking.create.mockResolvedValue({ id: "b1" }); await expect(createPublicBooking("slug", { name: "Jane Buyer", email: "jane@example.com", startsAt: new Date() })).resolves.toMatchObject({ id: "b1" }); await expect(createPublicBooking("slug", { name: "Jane Buyer", email: "jane@example.com", startsAt: new Date() })).rejects.toThrow("unavailable"); });
  it("research disabled state and question generation are review-required", async () => { const { createResearchRun, generateInterviewQuestions } = await import("@/lib/revenue-os/research"); prisma.researchRun.create.mockResolvedValue({ status: "DISABLED" }); prisma.interviewQuestionSet.create.mockImplementation(async ({ data }) => data); await expect(createResearchRun("w1", "CONTACT", "c1")).resolves.toMatchObject({ status: "DISABLED" }); const qs = await generateInterviewQuestions("w1", "DEAL", "d1", { companyName: "Acme" }); expect(qs.reviewRequired).toBe(true); expect(qs.questions[0]).toContain("Acme"); });
  it("proposal acceptance creates contract and signer token flow is immutable", async () => { const { acceptProposalAndGenerateContract, signContract } = await import("@/lib/revenue-os/proposals-contracts"); prisma.proposal.findFirst.mockResolvedValue({ id: "p1", title: "Proposal", content: {} }); prisma.contract.create.mockResolvedValue({ id: "ct1" }); await expect(acceptProposalAndGenerateContract("w1", "p1")).resolves.toMatchObject({ id: "ct1" }); prisma.contractSigner.findUnique.mockResolvedValue({ id: "s1", workspaceId: "w1", contractId: "ct1", email: "buyer@example.com", tokenExpiresAt: new Date(Date.now()+10000) }); prisma.contractSignature.count.mockResolvedValue(0); prisma.contractSignature.create.mockResolvedValue({ id: "sig1", signedAt: new Date() }); await expect(signContract("tok", { typedName: "Buyer", acceptDisclosure: true })).resolves.toMatchObject({ id: "sig1" }); prisma.contractSignature.count.mockResolvedValue(1); await expect(signContract("tok", { typedName: "Buyer", acceptDisclosure: true })).rejects.toThrow("immutable"); });
  it("Stripe hard gate supports billing disabled, public route, subscription requirement, and admin bypass", async () => { const { getWorkspaceAccessDecision } = await import("@/lib/revenue-os/billing"); await expect(getWorkspaceAccessDecision("w1", "u@example.com", "/api/health")).resolves.toMatchObject({ allowed: true, reason: "public_route" }); process.env.BILLING_ENABLED = "true"; process.env.ADMIN_EMAILS = "admin@example.com"; await expect(getWorkspaceAccessDecision("w1", "admin@example.com", "/dashboard")).resolves.toMatchObject({ allowed: true, reason: "admin_bypass" }); await expect(getWorkspaceAccessDecision("w1", "user@example.com", "/dashboard")).resolves.toMatchObject({ allowed: false }); });
});
