"use client";

import { useRef, useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";

const ACCEPTED = [".mp4", ".m4a", ".mp3", ".wav", ".webm", ".mov"];
const MAX_BYTES = 5 * 1024 * 1024 * 1024;
type UploadState = "idle" | "selected" | "initiating" | "uploading" | "verifying" | "available" | "failed" | "cancelled";
function fmt(bytes:number){ if(!bytes) return "0 B"; const u=["B","KB","MB","GB"]; const i=Math.min(Math.floor(Math.log(bytes)/Math.log(1024)),u.length-1); return `${(bytes/1024**i).toFixed(i?1:0)} ${u[i]}`; }
function safeMessage(value:unknown){ const msg = value instanceof Error ? value.message : String(value || "Upload failed."); return /secret|credential|token|bucket|key|signature/i.test(msg) ? "Upload failed. Please retry." : msg.slice(0,240); }
function valid(file:File){ const lower=file.name.toLowerCase(); if(!ACCEPTED.some(ext=>lower.endsWith(ext))) return "Unsupported file type. Upload MP4, M4A, MP3, WAV, WebM, or MOV."; if(file.size>MAX_BYTES) return "Recording file is larger than the 5 GiB upload limit."; if(file.size<=0) return "Recording file is empty."; return null; }

export function LocalRecordingUpload({ meetingId, workspaceId }: { meetingId: string; workspaceId: string }) {
  const router = useRouter(); const inputRef = useRef<HTMLInputElement>(null); const xhrRef = useRef<XMLHttpRequest | null>(null);
  const [state,setState]=useState<UploadState>("idle"); const [file,setFile]=useState<File|null>(null); const [progress,setProgress]=useState(0); const [error,setError]=useState(""); const [recordingId,setRecordingId]=useState(""); const [drag,setDrag]=useState(false); const [isPending,startTransition]=useTransition();
  function choose(next:File|null){ setError(""); setProgress(0); setRecordingId(""); if(!next){setFile(null); setState("idle"); return;} const err=valid(next); setFile(next); if(err){ setState("failed"); setError(err); return;} setState("selected"); }
  async function abortSession(id:string){ if(!id) return; await fetch(`/api/meetings/${meetingId}/recording-uploads/${id}/abort?workspaceId=${workspaceId}`,{method:"POST"}).catch(()=>undefined); }
  async function upload(){ if(!file || ["initiating","uploading","verifying"].includes(state)) return; const err=valid(file); if(err){setError(err); setState("failed"); return;} setError(""); setProgress(0); setState("initiating"); let id=""; try{
      const res=await fetch(`/api/meetings/${meetingId}/recording-uploads/initiate?workspaceId=${workspaceId}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({originalFileName:file.name,mimeType:file.type || "application/octet-stream",fileSizeBytes:file.size})});
      const init=await res.json(); if(!res.ok) throw new Error(init.error || "Upload could not be initiated."); id=String(init.recordingId); setRecordingId(id);
      await new Promise<void>((resolve,reject)=>{ const xhr=new XMLHttpRequest(); xhrRef.current=xhr; xhr.open(init.upload.method || "PUT", init.upload.url); Object.entries(init.upload.headers || {}).forEach(([k,v])=>xhr.setRequestHeader(k,String(v))); xhr.upload.onprogress=(e)=>{ if(e.lengthComputable) setProgress(Math.round((e.loaded/e.total)*100)); }; xhr.onload=()=> xhr.status>=200&&xhr.status<300 ? resolve() : reject(new Error(xhr.status===403 ? "Upload URL expired. Please retry." : "Upload was interrupted. Please retry.")); xhr.onerror=()=>reject(new Error("Upload was interrupted. Please retry.")); xhr.onabort=()=>reject(new DOMException("Upload cancelled.","AbortError")); setState("uploading"); xhr.send(file); });
      setState("verifying"); const done=await fetch(`/api/meetings/${meetingId}/recording-uploads/${id}/complete?workspaceId=${workspaceId}`,{method:"POST"}); const body=await done.json(); if(!done.ok) throw new Error(body.error || "Upload could not be verified."); setProgress(100); setState("available"); startTransition(()=>router.refresh());
    }catch(e){ if(e instanceof DOMException && e.name==="AbortError"){ setState("cancelled"); setError("Upload cancelled."); await abortSession(id || recordingId); } else { setState("failed"); setError(safeMessage(e)); } } finally { xhrRef.current=null; }
  }
  async function cancel(){ xhrRef.current?.abort(); await abortSession(recordingId); setState("cancelled"); setError("Upload cancelled."); }
  const busy=["initiating","uploading","verifying"].includes(state);
  return <div className="space-y-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950 dark:border-emerald-500/40 dark:bg-emerald-950 dark:text-emerald-50">
    <div><p className="font-semibold">Local Zoom recording workflow</p><ol className="ml-5 mt-2 list-decimal space-y-1"><li>Record to this computer in Zoom.</li><li>End the Zoom meeting.</li><li>Wait for Zoom’s local processing to finish.</li><li>Upload the MP4 or M4A file here.</li><li>Start transcription.</li><li>Review and approve the transcript.</li></ol><p className="mt-2 text-xs">Quantum Reach does not automatically receive locally recorded files.</p></div>
    <div onDragOver={(e)=>{e.preventDefault(); setDrag(true);}} onDragLeave={()=>setDrag(false)} onDrop={(e)=>{e.preventDefault(); setDrag(false); choose(e.dataTransfer.files?.[0] ?? null);}} className={`rounded-xl border-2 border-dashed bg-white/70 p-5 text-center dark:bg-slate-950/40 ${drag?"border-emerald-600":"border-emerald-300"}`}><input ref={inputRef} aria-label="Choose local recording file" type="file" accept={ACCEPTED.join(",")} className="sr-only" onChange={(e)=>choose(e.target.files?.[0] ?? null)} /><p className="font-medium">Drag and drop a recording here</p><p className="mt-1 text-xs">Supported formats: MP4, M4A, MP3, WAV, WebM, MOV. Maximum file size: 5 GiB.</p><Button type="button" variant="outline" className="mt-3" onClick={()=>inputRef.current?.click()} disabled={busy}>Choose file</Button></div>
    {file ? <div className="rounded-lg bg-white/80 p-3 text-xs dark:bg-slate-900"><p><span className="font-medium">Selected:</span> {file.name}</p><p><span className="font-medium">Size:</span> {fmt(file.size)}</p><p><span className="font-medium">State:</span> {state}</p></div> : null}
    {busy || state==="available" ? <div><div className="flex justify-between text-xs"><span>{state==="verifying"?"Verifying upload":state==="available"?"Upload complete":"Uploading"}</span><span>{progress}%</span></div><div className="mt-1 h-2 overflow-hidden rounded bg-emerald-100 dark:bg-emerald-900"><div className="h-full bg-emerald-600 transition-all" style={{width:`${progress}%`}} /></div></div> : null}
    {error ? <p role="alert" className="rounded-lg bg-amber-50 p-2 text-amber-800 dark:bg-amber-900 dark:text-amber-100">{error}</p> : null}{state==="available" ? <p className="rounded-lg bg-green-100 p-2 text-green-800 dark:bg-green-900 dark:text-green-100">Recording uploaded and available. {isPending ? "Refreshing recording list…" : "The recording list is refreshed below."}</p> : null}
    <div className="flex flex-wrap gap-2"><Button type="button" onClick={upload} disabled={!file || busy || state==="available"}>{state==="failed"||state==="cancelled"?"Retry upload":"Upload recording"}</Button>{busy ? <Button type="button" variant="outline" onClick={cancel}>Cancel upload</Button> : null}</div>
  </div>;
}
