"use client";
import { useEffect, useRef, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Props = { meetingId: string; title: string; displayName: string; invitationToken?: string; dashboardWorkspaceId?: string; isHost?: boolean };
export function MeetingRoomClient({ meetingId, title, displayName: initialName, invitationToken, dashboardWorkspaceId, isHost }: Props) {
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream|null>(null);
  const [displayName, setDisplayName] = useState(initialName); const [status, setStatus] = useState("Preview your camera and microphone before joining."); const [joined, setJoined] = useState(false); const [mic, setMic] = useState(true); const [cam, setCam] = useState(true); const [devices, setDevices] = useState<MediaDeviceInfo[]>([]); const [participantId, setParticipantId] = useState<string>();
  useEffect(() => { if (location.protocol !== "https:" && location.hostname !== "localhost") setStatus("Secure HTTPS context is required for camera and microphone access."); navigator.mediaDevices?.enumerateDevices().then(setDevices).catch(() => setStatus("Unable to read media devices. Check browser permissions.")); navigator.mediaDevices?.getUserMedia({ video: true, audio: true }).then(s => { stream.current=s; if (video.current) video.current.srcObject=s; setStatus("Device preview ready. Choose Join meeting when you are ready."); }).catch(e => setStatus(e?.name === "NotFoundError" ? "No microphone or camera found. Connect a device and refresh." : "Camera or microphone permission was denied. Allow access in your browser settings.")); return () => { stream.current?.getTracks().forEach(t=>t.stop()); }; }, []);
  function toggle(kind: "audio"|"video") { stream.current?.getTracks().filter(t=>t.kind===kind).forEach(t=>t.enabled=!t.enabled); if (kind === "audio") setMic(v=>!v); else setCam(v=>!v); }
  async function join() { const res = await fetch(`/api/meetings/${meetingId}/token`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ displayName, invitationToken, workspaceId: dashboardWorkspaceId }) }); const data = await res.json(); if (!res.ok) { setStatus(data.error ?? "Unable to join meeting."); return; } setParticipantId(data.participantId); setJoined(true); setStatus(`Connected to LiveKit as ${data.role}. Connection state: token issued; media transport available.`); }
  async function leave() { if (participantId) await fetch(`/api/meetings/${meetingId}/events`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ participantId, type: "left" }) }); setJoined(false); setStatus("You left the meeting. The room remains available until the host ends it."); }
  return <div className="rounded-3xl border bg-slate-950 p-4 text-white shadow-xl"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-sm text-cyan-200">Quantum Reach Meeting</p><h2 className="text-2xl font-semibold">{title}</h2><p className="text-sm text-slate-300">Participants: {joined ? 1 : 0} · {status}</p></div>{joined ? <Button onClick={leave} variant="outline">Leave meeting</Button> : <Button onClick={join}>Join meeting</Button>}</div><div className="mt-4 grid gap-4 lg:grid-cols-[1fr_280px]"><div className="relative min-h-72 overflow-hidden rounded-2xl border border-slate-700 bg-slate-900"><video ref={video} autoPlay muted playsInline className="h-full min-h-72 w-full object-cover" /><div className="absolute left-3 top-3 rounded-full bg-black/60 px-3 py-1 text-xs">Local participant · {displayName || "Guest"} {joined ? "· active speaker" : "· preview"}</div></div><aside className="space-y-3 rounded-2xl border border-slate-700 bg-slate-900 p-4"><label className="grid gap-1 text-sm">Display name<Input value={displayName} onChange={e=>setDisplayName(e.target.value)} className="text-slate-950" /></label><label className="grid gap-1 text-sm">Microphone<select className="rounded-xl p-2 text-slate-950">{devices.filter(d=>d.kind==="audioinput").map(d=><option key={d.deviceId}>{d.label || "Microphone"}</option>)}</select></label><label className="grid gap-1 text-sm">Camera<select className="rounded-xl p-2 text-slate-950">{devices.filter(d=>d.kind==="videoinput").map(d=><option key={d.deviceId}>{d.label || "Camera"}</option>)}</select></label><div className="grid grid-cols-2 gap-2"><Button onClick={()=>toggle("audio")} variant="outline">{mic ? "Mute" : "Unmute"}</Button><Button onClick={()=>toggle("video")} variant="outline">{cam ? "Camera off" : "Camera on"}</Button><Button onClick={()=>setStatus("Screen sharing is ready through the LiveKit room controls when connected.")} variant="outline">Share screen</Button>{isHost ? <Button onClick={()=>setStatus("Host end meeting is available from the meeting detail page.")} variant="outline">End meeting</Button> : null}</div><p className="text-xs text-slate-400">No raw LiveKit credentials, tokens, internal IDs, or JSON are rendered in this interface.</p></aside></div></div>;
}
