import { KnowledgeAuthorityLevel, KnowledgePriority, PrismaClient, WorkspaceRoleKey } from "@prisma/client";
const prisma = new PrismaClient();

const knowledgeManifest: Array<{ title: string; documentType: KnowledgeAuthorityLevel; authorityLevel: KnowledgeAuthorityLevel; priority: KnowledgePriority; workflowStages: string[]; useFor: string }> = [
  { title: "Master System Operating Doctrine", documentType: "SYSTEM_DOCTRINE", authorityLevel: "SYSTEM_DOCTRINE", priority: "GLOBAL", workflowStages: ["DISCOVERY_CALL", "TRANSCRIPT_ANALYSIS", "DIAGNOSTIC_REVIEW", "REPORT_GENERATION", "ROADMAP_GENERATION", "PROPOSAL_GENERATION", "IMPLEMENTATION_HANDOFF"], useFor: "global AI behavior, analyzer logic, report/proposal tone, compliance and risk discipline" },
  { title: "Master System Rollout Directive — Best-in-Class Expanded Edition", documentType: "PRODUCT_DOCTRINE", authorityLevel: "PRODUCT_DOCTRINE", priority: "GLOBAL", workflowStages: ["LEAD_CAPTURE", "DISCOVERY_CALL", "TRANSCRIPT_ANALYSIS", "DIAGNOSTIC_REVIEW", "REPORT_GENERATION", "ROADMAP_GENERATION", "PROPOSAL_GENERATION"], useFor: "product behavior and rollout logic" },
  { title: "Consulting-First Copy, UX, and Decision Architecture Standard", documentType: "UX_COPY_DOCTRINE", authorityLevel: "UX_COPY_DOCTRINE", priority: "GLOBAL", workflowStages: ["APP_UX", "TRANSCRIPT_ANALYSIS", "REPORT_GENERATION", "ROADMAP_GENERATION", "PROPOSAL_GENERATION"], useFor: "UI language, app copy, report/proposal narrative structure" },
  { title: "Authority-Led Framework, Academy Positioning, and Operating Doctrine", documentType: "STRATEGY_FRAMEWORK", authorityLevel: "STRATEGY_FRAMEWORK", priority: "HIGH", workflowStages: ["OUTREACH", "DISCOVERY_CALL", "DIAGNOSTIC_REVIEW", "REPORT_GENERATION"], useFor: "authority-led sales philosophy and diagnostic framing" },
  { title: "Business Strategy, Scale, Integration & Exit Architecture", documentType: "STRATEGY_FRAMEWORK", authorityLevel: "STRATEGY_FRAMEWORK", priority: "HIGH", workflowStages: ["TRANSCRIPT_ANALYSIS", "REPORT_GENERATION", "ROADMAP_GENERATION", "ROI_MODELING"], useFor: "scale planning, exit readiness, roadmap and ROI logic" },
  { title: "AI Solution Integration & Execution Handoff", documentType: "EXECUTION_HANDOFF", authorityLevel: "EXECUTION_HANDOFF", priority: "HIGH", workflowStages: ["PROPOSAL_GENERATION", "ROADMAP_GENERATION", "IMPLEMENTATION_HANDOFF"], useFor: "solution validation, proposal assembly, implementation handoff" },
  { title: "Finesse IT Layer Master Prompt", documentType: "REPORT_FRAMEWORK", authorityLevel: "STRATEGY_FRAMEWORK", priority: "HIGH", workflowStages: ["DIAGNOSTIC_REVIEW", "REPORT_GENERATION", "ROADMAP_GENERATION", "PROPOSAL_GENERATION"], useFor: "final refinement and logic tightening" },
  { title: "26-Week Master Curriculum Detailed Instructional Build", documentType: "TRAINING_CURRICULUM", authorityLevel: "TRAINING_CURRICULUM", priority: "MEDIUM", workflowStages: ["ACADEMY_TRAINING", "DISCOVERY_CALL", "TRANSCRIPT_ANALYSIS", "ROI_MODELING", "OFFER_CREATION"], useFor: "academy/training and internal methodology reference" },
  { title: "Mastery Template of Each Section of the Course", documentType: "COURSE_TEMPLATE", authorityLevel: "COURSE_TEMPLATE", priority: "MEDIUM", workflowStages: ["ACADEMY_TRAINING"], useFor: "course/module generation" },
  { title: "Authority Figure Prompt for Any Niche", documentType: "AUTHORITY_TEMPLATE", authorityLevel: "AUTHORITY_TEMPLATE", priority: "MEDIUM", workflowStages: ["AUTHORITY_ASSET_GENERATION", "OUTREACH", "POSITIONING"], useFor: "authority blueprint generation" },
  { title: "Any Niche Ultimate Authority Dominance Blueprint", documentType: "AUTHORITY_TEMPLATE", authorityLevel: "AUTHORITY_TEMPLATE", priority: "MEDIUM", workflowStages: ["AUTHORITY_ASSET_GENERATION", "POSITIONING", "REPORT_GENERATION"], useFor: "boardroom authority package and competitive positioning" }
];

async function main() {
  const systemUser = await prisma.userProfile.upsert({ where: { clerkUserId: "seed-user" }, update: {}, create: { clerkUserId: "seed-user", email: "seed@example.com", firstName: "Seed", lastName: "User" } });
  const workspace = await prisma.workspace.upsert({ where: { slug: "demo-workspace" }, update: {}, create: { name: "Demo Workspace", slug: "demo-workspace", ownerId: systemUser.id, members: { create: { userId: systemUser.id, roleKey: WorkspaceRoleKey.WORKSPACE_OWNER } } } });
  await prisma.pipeline.upsert({ where: { id: "demo-pipeline" }, update: {}, create: { id: "demo-pipeline", workspaceId: workspace.id, name: "Advisory Pipeline", isDefault: true, stages: { create: [{ workspaceId: workspace.id, name: "Qualified", position: 1, probability: 20 }, { workspaceId: workspace.id, name: "Diagnostic", position: 2, probability: 40 }, { workspaceId: workspace.id, name: "Proposal", position: 3, probability: 70 }, { workspaceId: workspace.id, name: "Won", position: 4, probability: 100 }] } } });
  for (const key of ["diagnostic_summary", "constraint_extraction", "roi_model", "executive_report", "strategic_roadmap"]) await prisma.analyzerDefinition.upsert({ where: { workspaceId_key: { workspaceId: workspace.id, key } }, update: {}, create: { workspaceId: workspace.id, key, name: key.replaceAll("_", " ") } });
  for (const item of knowledgeManifest) {
    const existing = await prisma.knowledgeDocument.findFirst({ where: { workspaceId: workspace.id, title: item.title } });
    if (!existing) await prisma.knowledgeDocument.create({ data: { workspaceId: workspace.id, title: item.title, description: `Seed metadata manifest. Import approved source text before activation. Use for: ${item.useFor}.`, documentType: item.documentType, authorityLevel: item.authorityLevel, priority: item.priority, workflowStages: item.workflowStages, sourceText: `Seed metadata placeholder for ${item.title}. Replace with approved source-of-truth text before activation.`, status: "DRAFT", version: "metadata-manifest" } });
  }
}
main().finally(async () => prisma.$disconnect());
