import Link from "next/link";
import { revalidatePath } from "next/cache";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/input";
import { getCurrentWorkspace } from "@/lib/workspaces/service";
import { prisma } from "@/lib/db/prisma";
import { approveTranscript, processTranscriptionJob, saveTranscriptDraft } from "@/lib/meetings/transcription";
function words(text:string){ return text.trim()?text.trim().split(/\s+/).length:0; }
export default async function Page({params}:{params:{id:string;recordingId:string}}){ const workspace=await getCurrentWorkspace(); if(!workspace) return null; const recording=await prisma.meetingRecording.findFirst({where:{id:params.recordingId,workspaceId:workspace.id,meetingRoomId:params.id},include:{meetingRoom:true,callSession:true}}); if(!recording) return null; const text=recording.transcriptEditedText||recording.transcriptText||""; async function save(formData:FormData){ "use server"; const workspace=await getCurrentWorkspace(); if(!workspace) return; await saveTranscriptDraft(workspace.id,params.id,params.recordingId,String(formData.get("transcript")||"")); revalidatePath(`/dashboard/meetings/${params.id}/recordings/${params.recordingId}/transcript`); } async function approve(){ "use server"; const workspace=await getCurrentWorkspace(); if(!workspace) return; await approveTranscript(workspace.id,params.id,params.recordingId); revalidatePath(`/dashboard/meetings/${params.id}/recordings/${params.recordingId}/transcript`); } async function retry(){ "use server"; const workspace=await getCurrentWorkspace(); if(!workspace) return; await processTranscriptionJob(workspace.id,params.id,params.recordingId); revalidatePath(`/dashboard/meetings/${params.id}/recordings/${params.recordingId}/transcript`); }
 return <div className="space-y-6"><div><Link href={`/dashboard/meetings/${params.id}`} className="text-sm text-slate-500 hover:underline">← Back to meeting</Link><h1 className="mt-2 text-3xl font-semibold">Transcript review</h1><p className="mt-2 text-slate-600 dark:text-slate-300">{recording.meetingRoom.title} · {recording.completedAt?.toLocaleString() ?? "Recording not finalized"}</p></div><Card><CardHeader><CardTitle>Generated transcript</CardTitle><CardDescription>Generated text is not approved until an authorized workspace user reviews it and selects Approve transcript.</CardDescription></CardHeader><CardContent className="space-y-4"><div className="rounded-xl border bg-slate-50 p-4 text-sm whitespace-pre-wrap dark:border-slate-800 dark:bg-slate-900">{recording.transcriptText || "No generated transcript is available yet."}</div><p className="text-sm text-slate-500">Status: {recording.transcriptionStatus.replaceAll("_"," ").toLowerCase()} · {text.length} characters · {words(text)} words</p>{recording.transcriptionStatus === "FAILED" ? <form action={retry}><Button type="submit" variant="outline">Retry transcription</Button></form> : null}</CardContent></Card><Card><CardHeader><CardTitle>Reviewed transcript</CardTitle><CardDescription>Save edits before approval. Approved transcripts are immutable in this Phase 9B workflow.</CardDescription></CardHeader><CardContent><form action={save} className="space-y-4"><Textarea name="transcript" defaultValue={text} rows={18} disabled={Boolean(recording.transcriptApprovedAt)} /><div className="flex flex-wrap gap-2"><Button type="submit" disabled={Boolean(recording.transcriptApprovedAt)}>Save draft</Button></div></form><form action={approve} className="mt-3 flex flex-wrap gap-2"><Button type="submit" disabled={Boolean(recording.transcriptApprovedAt) || !text.trim()}>Approve transcript</Button>{recording.callSessionId ? <Button href={`/dashboard/calls/${recording.callSessionId}`} variant="outline">Open linked CallSession</Button> : null}</form></CardContent></Card></div>; }
