import { createHmac, createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { markWebhookRecordingAvailable, markWebhookRecordingStarted } from "@/lib/meetings/recordings";
export const runtime="nodejs";
function b64json(part:string){ return JSON.parse(Buffer.from(part,"base64url").toString("utf8")); }
function verify(token:string, body:string){ const secret=process.env.LIVEKIT_API_SECRET; const key=process.env.LIVEKIT_API_KEY; if(!secret||!key) return false; const [h,p,s]=token.split("."); if(!h||!p||!s) return false; const sig=createHmac("sha256",secret).update(`${h}.${p}`).digest("base64url"); if(sig!==s) return false; const payload=b64json(p) as {iss?:string;exp?:number;sha256?:string}; if(payload.iss!==key) return false; if(payload.exp && payload.exp < Math.floor(Date.now()/1000)) return false; if(payload.sha256 && payload.sha256!==createHash("sha256").update(body).digest("base64")) return false; return true; }
function egressId(event:Record<string,unknown>){ const e=(event.egressInfo||event.egress_info||event.egress) as Record<string,unknown>|undefined; return String(e?.egressId||e?.egress_id||event.egressId||event.egress_id||""); }
export async function POST(request:Request){ const body=await request.text(); const auth=request.headers.get("authorization")||""; const token=auth.replace(/^Bearer\s+/i,""); if(!verify(token,body)) return NextResponse.json({error:"Invalid LiveKit webhook."},{status:401}); const event=JSON.parse(body) as Record<string,unknown>; const type=String(event.event||event.type||""); const id=egressId(event); if(!id) return NextResponse.json({ok:true,ignored:"no egress id"}); if(type.includes("egress_started")){ await markWebhookRecordingStarted(id,`livekit:${type}:${id}:${String(event.id||event.createdAt||Date.now())}`); }
 if(type.includes("egress_ended")||type.includes("egress_updated")){ const info=(event.egressInfo||event.egress_info||{}) as Record<string,unknown>; const file=((info.fileResults as unknown[])?.[0]|| (info.file as Record<string,unknown>) || {}) as Record<string,unknown>; await markWebhookRecordingAvailable(id,{sizeBytes:Number(file.size||file.sizeBytes||0)||undefined,durationSeconds:Number(info.duration||0)||undefined},`livekit:${type}:${id}:${String(event.id||event.createdAt||Date.now())}`); } return NextResponse.json({ok:true}); }
