import { createHmac, createHash } from "node:crypto";
import { NextResponse } from "next/server";
import { parseLiveKitEgress } from "@/lib/meetings/egress";
import { markWebhookRecordingAvailable, markWebhookRecordingFailed, markWebhookRecordingStarted } from "@/lib/meetings/recordings";
export const runtime="nodejs";
function b64json(part:string){ return JSON.parse(Buffer.from(part,"base64url").toString("utf8")); }
function verify(token:string, body:string){ const secret=process.env.LIVEKIT_API_SECRET; const key=process.env.LIVEKIT_API_KEY; if(!secret||!key) return false; const [h,p,s]=token.split("."); if(!h||!p||!s) return false; const sig=createHmac("sha256",secret).update(`${h}.${p}`).digest("base64url"); if(sig!==s) return false; const payload=b64json(p) as {iss?:string;exp?:number;sha256?:string}; if(payload.iss!==key) return false; if(payload.exp && payload.exp < Math.floor(Date.now()/1000)) return false; if(payload.sha256 && payload.sha256!==createHash("sha256").update(body).digest("base64")) return false; return true; }
function egressInfo(event:Record<string,unknown>){ return (event.egressInfo||event.egress_info||event.egress||{}) as Record<string,unknown>; }
function egressId(event:Record<string,unknown>){ const e=egressInfo(event); return String(e.egressId||e.egress_id||event.egressId||event.egress_id||""); }
export async function POST(request:Request){ const body=await request.text(); const auth=request.headers.get("authorization")||""; const token=auth.replace(/^Bearer\s+/i,""); if(!verify(token,body)) return NextResponse.json({error:"Invalid LiveKit webhook."},{status:401}); const event=JSON.parse(body) as Record<string,unknown>; const type=String(event.event||event.type||""); const id=egressId(event); if(!id) return NextResponse.json({ok:true,ignored:"no egress id"}); const info=egressInfo(event); const parsed=parseLiveKitEgress(info); const eventKey=`livekit:${type}:${id}:${String(event.id||event.createdAt||event.created_at||Date.now())}`; if(type.includes("egress_started")){ await markWebhookRecordingStarted(id,eventKey,parsed.startedAt); }
 else if(type.includes("egress_ended")||type.includes("egress_updated")){ if(parsed.status==="AVAILABLE") await markWebhookRecordingAvailable(id,{sizeBytes:parsed.sizeBytes,durationSeconds:parsed.durationSeconds,completedAt:parsed.endedAt},eventKey); else if(parsed.status==="FAILED") await markWebhookRecordingFailed(id,parsed.safeFailureMessage??"Recording provider reported failure.",eventKey); else if(parsed.status==="RECORDING") await markWebhookRecordingStarted(id,eventKey,parsed.startedAt); } return NextResponse.json({ok:true}); }
