import { revalidatePath } from "next/cache";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { getCurrentWorkspace } from "@/lib/workspaces/service";
import { prisma } from "@/lib/db/prisma";

function label(value?: string | null) { return value ? value.replaceAll("_", " ").toLowerCase().replace(/\b\w/g, (l) => l.toUpperCase()) : "Not connected"; }

export default async function MeetingIntegrationsPage() {
  const workspace = await getCurrentWorkspace();
  if (!workspace) return null;
  const zoom = await prisma.workspaceMeetingIntegration.findUnique({ where: { workspaceId_provider: { workspaceId: workspace.id, provider: "ZOOM" } }, select: { status:true, providerAccountId:true, providerAccountName:true, connectedAt:true, lastRefreshedAt:true, safeFailureMessage:true } });
  async function disconnect() { "use server"; const workspace = await getCurrentWorkspace(); if(!workspace) return; await prisma.workspaceMeetingIntegration.updateMany({ where:{ workspaceId:workspace.id, provider:"ZOOM" }, data:{ status:"REVOKED", disconnectedAt:new Date(), safeFailureMessage:"Disconnected by workspace admin." }}); revalidatePath("/dashboard/settings/integrations/meetings"); }
  return <div className="space-y-6"><div><h1 className="text-3xl font-semibold">Meeting integrations</h1><p className="mt-2 text-slate-600 dark:text-slate-300">Connect provider accounts used for workspace meetings. Secrets, OAuth tokens, webhook signatures, and raw provider payloads are never displayed.</p></div><Card><CardHeader><CardTitle>Zoom</CardTitle><CardDescription>Active provider for new meetings when connected. Quantum Reach supports the production Zoom path: create the Zoom meeting, start and end it from Quantum Reach, then upload the local recording for transcript and analysis. Zoom cloud recording import remains code-ready but unavailable unless the Zoom account plan includes cloud recordings.</CardDescription></CardHeader><CardContent className="space-y-3 text-sm"><p><span className="font-medium">Status:</span> {label(zoom?.status)}</p><p><span className="font-medium">Account:</span> {zoom?.providerAccountName || "—"} {zoom?.providerAccountId ? `(${zoom.providerAccountId})` : ""}</p><p><span className="font-medium">Connected:</span> {zoom?.connectedAt?.toLocaleString() || "—"}</p><p><span className="font-medium">Last refreshed:</span> {zoom?.lastRefreshedAt?.toLocaleString() || "—"}</p>{zoom?.safeFailureMessage ? <p className="rounded-xl bg-amber-50 p-3 text-amber-800 dark:bg-amber-950 dark:text-amber-100">{zoom.safeFailureMessage}</p> : null}<div className="flex flex-wrap gap-2"><Button href={`/api/integrations/zoom/connect?workspaceId=${workspace.id}`}>{zoom ? "Reconnect Zoom" : "Connect Zoom"}</Button>{zoom ? <form action={disconnect}><Button type="submit" variant="outline">Disconnect Zoom</Button></form> : null}</div></CardContent></Card><div className="grid gap-4 md:grid-cols-3"><Card><CardHeader><CardTitle>Local recording upload</CardTitle><CardDescription>Supported production workflow. Upload Zoom local recordings after the meeting ends; M4A files are accepted and sent through the existing recording-to-analysis handoff.</CardDescription></CardHeader></Card><Card><CardHeader><CardTitle>Storage and AI health</CardTitle><CardDescription>R2 and OpenAI are reported only as configured or missing in diagnostics. Secret values are never rendered in the browser.</CardDescription></CardHeader></Card><Card><CardHeader><CardTitle>Zoom cloud recordings</CardTitle><CardDescription>Deferred for the current private beta account unless the Zoom plan includes cloud recording. The import path remains preserved for future enablement.</CardDescription></CardHeader></Card></div><div className="grid gap-4 md:grid-cols-2"><Card><CardHeader><CardTitle>Google Meet</CardTitle><CardDescription>Coming later through the provider adapter interface.</CardDescription></CardHeader></Card><Card><CardHeader><CardTitle>Microsoft Teams</CardTitle><CardDescription>Coming later through the provider adapter interface.</CardDescription></CardHeader></Card></div></div>;
}
