/* eslint-disable @typescript-eslint/no-explicit-any */
import { Prisma, type CommercialCoupon } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
import type { AcquisitionChargeSummary, CommercialChargeLine } from "./charge-lines";

export const normalizeCouponCode = (code: string) => code.trim().toUpperCase().replace(/\s+/g, "");
export type CouponRule = Pick<CommercialCoupon, "id"|"code"|"normalizedCode"|"displayName"|"active"|"validFrom"|"expiresAt"|"retiredAt"|"percentageOff"|"recurringDiscountMonths"|"trialDays"|"minimumOrderAmountCents"|"maximumTotalRedemptions"|"maximumRedemptionsPerCustomer"|"stripeCouponId"|"stripePromotionCodeId"|"version"|"eligiblePackageKeys"|"eligibleProductKeys"|"eligibleChargeTypes">;
export type CouponCalculation = AcquisitionChargeSummary & { coupon: { id:string; code:string; normalizedCode:string; displayName:string; version:number; percentageOff:number; recurringDiscountMonths:number|null; trialDays:number|null; stripeCouponId:string|null; stripePromotionCodeId:string|null }; totalCouponSavingsCents:number; promotionalRecurringCents:number; fullPriceResumesAfterPeriods:number|null; trialEndsAt:string|null };

export function validateCouponConfiguration(input:{code:string;percentageOff:number;recurringDiscountMonths?:number|null;trialDays?:number|null;minimumOrderAmountCents?:number}) {
  if (!normalizeCouponCode(input.code)) throw new Error("COUPON_CODE_REQUIRED");
  if (!Number.isInteger(input.percentageOff)||input.percentageOff<1||input.percentageOff>100) throw new Error("COUPON_PERCENTAGE_INVALID");
  if (input.recurringDiscountMonths != null && (!Number.isInteger(input.recurringDiscountMonths)||input.recurringDiscountMonths<1)) throw new Error("COUPON_RECURRING_DURATION_INVALID");
  if (input.trialDays != null && (!Number.isInteger(input.trialDays)||input.trialDays<1)) throw new Error("COUPON_TRIAL_DAYS_INVALID");
  if (!Number.isInteger(input.minimumOrderAmountCents??0)||(input.minimumOrderAmountCents??0)<0) throw new Error("COUPON_MINIMUM_INVALID");
}

export function couponEligibility(rule:CouponRule, summary:AcquisitionChargeSummary, now=new Date(), counts={total:0,customer:0}) {
  if (!rule.active||rule.retiredAt) return "Code is invalid.";
  if (rule.validFrom&&rule.validFrom>now) return "Code is not active yet.";
  if (rule.expiresAt&&rule.expiresAt<=now) return "Code has expired.";
  if (rule.eligiblePackageKeys.length&&!rule.eligiblePackageKeys.includes(summary.plan.key)) return "Code is not valid for this package.";
  if (summary.todaySubtotalCents<rule.minimumOrderAmountCents) return "This code no longer applies to the selected order.";
  if (rule.maximumTotalRedemptions!=null&&counts.total>=rule.maximumTotalRedemptions) return "Code has reached its redemption limit.";
  if (rule.maximumRedemptionsPerCustomer!=null&&counts.customer>=rule.maximumRedemptionsPerCustomer) return "This code has already been used for this account.";
  return null;
}

const discountable=(line:CommercialChargeLine,rule:CouponRule)=>!["TAX","PASS_THROUGH_FEE"].includes(line.chargeType)&&rule.eligibleChargeTypes.includes(line.chargeType)&&(!rule.eligibleProductKeys.length||rule.eligibleProductKeys.includes(line.productKey));
export function applyCouponToSummary(summary:AcquisitionChargeSummary, rule:CouponRule, now=new Date()):CouponCalculation {
  const eligibility=couponEligibility(rule,summary,now);if(eligibility)throw new Error(eligibility);
  const lines=summary.lines.map(line=>{const trialFirst=Boolean(rule.trialDays)&&line.chargeType==="PACKAGE_FIRST_MONTH";const eligible=trialFirst||discountable(line,rule);const discountAmountCents=eligible?Math.min(line.grossAmountCents,trialFirst?line.grossAmountCents:Math.round(line.grossAmountCents*rule.percentageOff/100)):0;return{...line,discountAmountCents,netAmountCents:line.grossAmountCents-discountAmountCents};});
  const due=lines.filter(line=>line.dueToday);const todayTotalCents=due.reduce((sum,line)=>sum+line.netAmountCents,0);const totalCouponSavingsCents=due.reduce((sum,line)=>sum+line.discountAmountCents,0);
  const recurring=lines.find(line=>line.chargeType==="PACKAGE_RECURRING");const promotionalRecurringCents=rule.recurringDiscountMonths&&recurring?recurring.netAmountCents:summary.recurringMonthlyCents;
  const trialEndsAt=rule.trialDays?new Date(now.getTime()+rule.trialDays*86400000).toISOString():null;
  return{...summary,lines,todayTotalCents,totalCouponSavingsCents,promotionalRecurringCents,fullPriceResumesAfterPeriods:rule.recurringDiscountMonths,trialEndsAt,coupon:{id:rule.id,code:rule.code,normalizedCode:rule.normalizedCode,displayName:rule.displayName,version:rule.version,percentageOff:rule.percentageOff,recurringDiscountMonths:rule.recurringDiscountMonths,trialDays:rule.trialDays,stripeCouponId:rule.stripeCouponId,stripePromotionCodeId:rule.stripePromotionCodeId}};
}

export async function getAppliedCoupon(acquisitionSessionId:string,db:any=prisma){return db.couponRedemption.findFirst({where:{acquisitionSessionId,status:{in:["APPLIED","RESERVED"]}},include:{coupon:true},orderBy:{appliedAt:"desc"}});}
export async function applyCoupon(input:{acquisitionSessionId:string;code:string;summary:AcquisitionChargeSummary;customerAccountId?:string;replace?:boolean},db:any=prisma){const normalizedCode=normalizeCouponCode(input.code);return db.$transaction(async(tx:any)=>{const existing=await getAppliedCoupon(input.acquisitionSessionId,tx);if(existing&&!input.replace)throw new Error("A coupon is already applied. Remove it or explicitly replace it.");const coupon=await tx.commercialCoupon.findUnique({where:{normalizedCode}});if(!coupon)throw new Error("Code is invalid.");const [total,customer]=await Promise.all([tx.couponRedemption.count({where:{couponId:coupon.id,status:{in:["RESERVED","REDEEMED"]}}}),input.customerAccountId?tx.couponRedemption.count({where:{couponId:coupon.id,customerAccountId:input.customerAccountId,status:{in:["RESERVED","REDEEMED"]}}}):0]);const error=couponEligibility(coupon,input.summary,new Date(),{total,customer});if(error)throw new Error(error);const calculation=applyCouponToSummary(input.summary,coupon);if(existing)await tx.couponRedemption.update({where:{id:existing.id},data:{status:"RELEASED",releasedAt:new Date()}});const idempotencyKey=`coupon:${input.acquisitionSessionId}:${coupon.id}:${coupon.version}`;return tx.couponRedemption.upsert({where:{idempotencyKey},update:{status:"APPLIED",appliedAt:new Date(),releasedAt:null,calculationSnapshot:calculation as unknown as Prisma.InputJsonValue},create:{couponId:coupon.id,acquisitionSessionId:input.acquisitionSessionId,customerAccountId:input.customerAccountId,normalizedCodeSnapshot:coupon.normalizedCode,couponVersion:coupon.version,status:"APPLIED",idempotencyKey,calculationSnapshot:calculation as unknown as Prisma.InputJsonValue},include:{coupon:true}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
export async function removeAppliedCoupon(acquisitionSessionId:string,db:any=prisma){return db.couponRedemption.updateMany({where:{acquisitionSessionId,status:"APPLIED"},data:{status:"RELEASED",releasedAt:new Date()}});}
export async function reserveCouponForOrder(input:{acquisitionSessionId:string;orderId:string;customerAccountId:string},tx:any){const redemption=await getAppliedCoupon(input.acquisitionSessionId,tx);if(!redemption)return null;const [total,customer]=await Promise.all([tx.couponRedemption.count({where:{couponId:redemption.couponId,status:{in:["RESERVED","REDEEMED"]}}}),tx.couponRedemption.count({where:{couponId:redemption.couponId,customerAccountId:input.customerAccountId,status:{in:["RESERVED","REDEEMED"]}}})]);const error=couponEligibility(redemption.coupon,(redemption.calculationSnapshot as unknown as AcquisitionChargeSummary),new Date(),{total,customer});if(error)throw new Error(error);if(redemption.couponVersion!==redemption.coupon.version)throw new Error("This code no longer applies to the selected order.");const snapshot={...(redemption.calculationSnapshot as object),acceptedAt:new Date().toISOString()};await tx.couponRedemption.update({where:{id:redemption.id},data:{status:"RESERVED",orderId:input.orderId,customerAccountId:input.customerAccountId,reservedAt:new Date(),calculationSnapshot:snapshot}});await tx.customerOrder.update({where:{id:input.orderId},data:{acceptedCouponSnapshot:snapshot}});return snapshot;}
export async function transitionCouponRedemption(input:{redemptionId:string;to:"REDEEMED"|"RELEASED"|"REVERSED"|"EXPIRED"},db:any=prisma){const now=new Date();const field={REDEEMED:"redeemedAt",RELEASED:"releasedAt",REVERSED:"reversedAt",EXPIRED:"expiresAt"}[input.to];return db.couponRedemption.update({where:{id:input.redemptionId},data:{status:input.to,[field]:now}});}
