/* eslint-disable @typescript-eslint/no-explicit-any */
import { Prisma } from "@prisma/client";
import { prisma } from "@/lib/db/prisma";
export type AcceptedLimitKind="contact"|"team"|"storage";
const code:Record<AcceptedLimitKind,string>={contact:"PLAN_CONTACT_LIMIT_REACHED",team:"PLAN_TEAM_LIMIT_REACHED",storage:"PLAN_STORAGE_LIMIT_REACHED"};
const obj=(v:any):Record<string,any>=>v&&typeof v==="object"&&!Array.isArray(v)?v:{};
export async function acceptedWorkspaceLimits(workspaceId:string,tx:Prisma.TransactionClient|typeof prisma=prisma){const subscription=await tx.saasSubscription.findFirst({where:{workspaceId,status:{in:["ACTIVE","TRIALING"]}},orderBy:{createdAt:"desc"}});if(!subscription?.acceptedCommercialTerms)throw new Error("ENTITLEMENT_INVALID");const terms=obj(subscription.acceptedCommercialTerms),ent=obj(terms.entitlementSnapshot);const addons=await tx.saasSubscriptionItem.findMany({where:{workspaceId,status:{in:["ACTIVE","TRIALING"]}},include:{commerceProduct:{include:{entitlements:true}}}});const extra=(key:string)=>addons.reduce((sum,i)=>sum+i.quantity*i.commerceProduct.entitlements.filter(e=>e.entitlementKey===key).reduce((n,e)=>n+Number(e.integerValue??0),0),0);return{contacts:Number(terms.includedContacts??ent.ACTIVE_OUTREACH_CONTACT_ALLOWANCE??0)+extra("ACTIVE_OUTREACH_CONTACT_ALLOWANCE"),team:Number(terms.includedTeamUsers??ent.TEAM_USER_ALLOWANCE??0)+extra("TEAM_USER_ALLOWANCE"),storageGb:Number(ent.STORAGE_GB_ALLOWANCE??0)+extra("STORAGE_GB_ALLOWANCE")};}
export async function enforceAcceptedLimit(input:{workspaceId:string;kind:AcceptedLimitKind;additional?:number},tx:Prisma.TransactionClient){const limits=await acceptedWorkspaceLimits(input.workspaceId,tx);const used=input.kind==="contact"?await tx.contact.count({where:{workspaceId:input.workspaceId,status:"ACTIVE"}}):input.kind==="team"?await tx.workspaceMember.count({where:{workspaceId:input.workspaceId,status:"ACTIVE"}}):Number((await tx.knowledgeDocument.aggregate({where:{workspaceId:input.workspaceId},_sum:{sourceFileSizeBytes:true}}))._sum.sourceFileSizeBytes??0)/(1024**3);const limit=input.kind==="storage"?limits.storageGb:input.kind==="team"?limits.team:limits.contacts;if(used+(input.additional??1)>limit)throw new Error(code[input.kind]);return{used,limit,remaining:Math.max(0,limit-used)};}
export async function createWorkspaceMemberWithinPlan(input:{workspaceId:string;userId:string;roleKey?:any},db:any=prisma){return db.$transaction(async(tx:Prisma.TransactionClient)=>{await enforceAcceptedLimit({workspaceId:input.workspaceId,kind:"team"},tx);return tx.workspaceMember.create({data:{workspaceId:input.workspaceId,userId:input.userId,roleKey:input.roleKey??"VIEWER"}});},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable});}
