/* eslint-disable @typescript-eslint/no-explicit-any */
import { safeErrorMessage } from "@/lib/sending-infrastructure/security";import type { AIProviderKey } from "./workspace-providers";
export type AIAdapterRequest={model:string;system?:string;prompt:string;timeoutMs?:number};export type AIAdapterResult={ok:boolean;provider:AIProviderKey;model:string;text?:string;inputTokens?:number;outputTokens?:number;requestId?:string;retryable?:boolean;failureType?:string;safeError?:string};
export interface WorkspaceAIAdapter{provider:AIProviderKey;execute(secret:string,input:AIAdapterRequest):Promise<AIAdapterResult>;test(secret:string,model:string):Promise<AIAdapterResult>}
async function request(provider:AIProviderKey,url:string,secret:string,body:object,headers:Record<string,string>,parse:(j:any)=>Partial<AIAdapterResult>,input:AIAdapterRequest):Promise<AIAdapterResult>{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),Math.min(input.timeoutMs??10000,30000));try{const response=await fetch(url,{method:"POST",headers:{"content-type":"application/json",...headers},body:JSON.stringify(body),signal:controller.signal});const id=response.headers.get("x-request-id")??undefined;const json=await response.json().catch(()=>({}));if(!response.ok)return{ok:false,provider,model:input.model,requestId:id,retryable:response.status===429||response.status>=500,failureType:response.status===401?"INVALID_CREDENTIAL":response.status===429?"QUOTA_OR_RATE_LIMIT":"PROVIDER_ERROR",safeError:`${provider} connection failed (${response.status}).`};return{ok:true,provider,model:input.model,requestId:id,...parse(json)};}catch(e){return{ok:false,provider,model:input.model,retryable:e instanceof Error&&e.name==="AbortError",failureType:e instanceof Error&&e.name==="AbortError"?"TIMEOUT":"NETWORK_ERROR",safeError:safeErrorMessage(e)};}finally{clearTimeout(timer)}}
class OpenAIAdapter implements WorkspaceAIAdapter{provider="OPENAI" as const;execute(s:string,i:AIAdapterRequest){return request(this.provider,"https://api.openai.com/v1/chat/completions",s,{model:i.model,messages:[{role:"system",content:i.system??""},{role:"user",content:i.prompt}],max_tokens:16},{authorization:`Bearer ${s}`},j=>({text:j.choices?.[0]?.message?.content,inputTokens:j.usage?.prompt_tokens,outputTokens:j.usage?.completion_tokens,requestId:j.id}),i)}test(s:string,m:string){return this.execute(s,{model:m,prompt:"Reply OK.",timeoutMs:10000})}}
class AnthropicAdapter implements WorkspaceAIAdapter{provider="ANTHROPIC" as const;execute(s:string,i:AIAdapterRequest){return request(this.provider,"https://api.anthropic.com/v1/messages",s,{model:i.model,system:i.system,max_tokens:16,messages:[{role:"user",content:i.prompt}]},{"x-api-key":s,"anthropic-version":"2023-06-01"},j=>({text:j.content?.[0]?.text,inputTokens:j.usage?.input_tokens,outputTokens:j.usage?.output_tokens,requestId:j.id}),i)}test(s:string,m:string){return this.execute(s,{model:m,prompt:"Reply OK.",timeoutMs:10000})}}
class GeminiAdapter implements WorkspaceAIAdapter{provider="GEMINI" as const;execute(s:string,i:AIAdapterRequest){return request(this.provider,`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(i.model)}:generateContent?key=${encodeURIComponent(s)}`,s,{contents:[{parts:[{text:`${i.system??""}\n${i.prompt}`}]}]},{},j=>({text:j.candidates?.[0]?.content?.parts?.[0]?.text,inputTokens:j.usageMetadata?.promptTokenCount,outputTokens:j.usageMetadata?.candidatesTokenCount}),i)}test(s:string,m:string){return this.execute(s,{model:m,prompt:"Reply OK.",timeoutMs:10000})}}
export function getWorkspaceAIAdapter(provider:AIProviderKey):WorkspaceAIAdapter{return provider==="OPENAI"?new OpenAIAdapter():provider==="ANTHROPIC"?new AnthropicAdapter():new GeminiAdapter()}
