/* eslint-disable @typescript-eslint/no-explicit-any */
import "server-only";
import { prisma } from "@/lib/db/prisma";
import { getWorkspaceAIAdapter } from "./adapters";
import { authorizeAISelection, credentialResponse, decryptAICredential, encryptAICredential, maskedCredential, type AIProviderKey } from "./workspace-providers";
type Db = typeof prisma;
export async function saveWorkspaceCredential(input: { workspaceId: string; actorId: string; provider: AIProviderKey; secret: string; allowedModels: string[] }, db: Db = prisma) { const encryptedSecret = encryptAICredential(input.secret), maskedKey = maskedCredential(input.secret); const record = await (db as any).workspaceAICredential.upsert({ where: { workspaceId_provider: { workspaceId: input.workspaceId, provider: input.provider } }, create: { workspaceId: input.workspaceId, provider: input.provider, encryptedSecret, maskedKey, createdById: input.actorId, allowedModels: input.allowedModels, enabled: true }, update: { encryptedSecret, maskedKey, rotatedById: input.actorId, allowedModels: input.allowedModels, enabled: true, revokedAt: null, status: "UNTESTED" } }); await db.auditLog.create({ data: { workspaceId: input.workspaceId, actorId: input.actorId, action: "AI_CREDENTIAL_ROTATED", entityType: "WorkspaceAICredential", entityId: record.id, metadata: { provider: input.provider, maskedKey } } }); return credentialResponse(record); }
export async function listWorkspaceProviders(workspaceId: string, db: Db = prisma) { const records = await (db as any).workspaceAICredential.findMany({ where: { workspaceId, revokedAt: null }, orderBy: { provider: "asc" } }); return records.map(credentialResponse); }
export async function removeWorkspaceCredential(input: { workspaceId: string; credentialId: string; actorId: string }, db: Db = prisma) { const result = await (db as any).workspaceAICredential.updateMany({ where: { id: input.credentialId, workspaceId: input.workspaceId }, data: { enabled: false, revokedAt: new Date(), encryptedSecret: "REVOKED" } }); if (result.count !== 1) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); await db.auditLog.create({ data: { workspaceId: input.workspaceId, actorId: input.actorId, action: "AI_CREDENTIAL_REMOVED", entityType: "WorkspaceAICredential", entityId: input.credentialId } }); }
export async function selectWorkspaceAI(input: { workspaceId: string; provider: AIProviderKey; model: string; clientAuthorized: boolean; feature: string; projectId?: string }, db: Db = prisma) { const credential = await (db as any).workspaceAICredential.findUnique({ where: { workspaceId_provider: { workspaceId: input.workspaceId, provider: input.provider } } }); if (!credential || credential.workspaceId !== input.workspaceId || credential.revokedAt) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); const selection = authorizeAISelection({ provider: input.provider, model: input.model, enabled: credential.enabled, allowedModels: Array.isArray(credential.allowedModels) ? credential.allowedModels : [], clientAuthorized: input.clientAuthorized }); return { ...selection, credentialId: credential.id, feature: input.feature, projectId: input.projectId };
}
export async function recordAIUsage(input: { workspaceId: string; credentialId: string; provider: AIProviderKey; model: string; feature: string; status: string; inputTokens?: number; outputTokens?: number; providerRequestId?: string }, db: Db = prisma) { const credential = await (db as any).workspaceAICredential.findFirst({ where: { id: input.credentialId, workspaceId: input.workspaceId, revokedAt: null } }); if (!credential) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); return (db as any).aIProviderUsage.create({ data: { ...input, subscriberPaid: true } }); }
export async function configureWorkspaceAI(input:{workspaceId:string;credentialId:string;actorId:string;enabled:boolean;allowedModels:string[];defaultModel?:string;featureDefaults?:object;projectDefaults?:object;clientPermissions?:object;monthlyAlertMinor?:number},db:Db=prisma){const current=await (db as any).workspaceAICredential.findFirst({where:{id:input.credentialId,workspaceId:input.workspaceId,revokedAt:null}});if(!current)throw new Error("AI_PROVIDER_NOT_CONFIGURED");if(input.defaultModel&&!input.allowedModels.includes(input.defaultModel))throw new Error("AI_MODEL_NOT_ALLOWED");const updated=await (db as any).workspaceAICredential.update({where:{id:current.id},data:{enabled:input.enabled,allowedModels:input.allowedModels,defaultModel:input.defaultModel,featureDefaults:input.featureDefaults??{},projectDefaults:input.projectDefaults??{},clientPermissions:input.clientPermissions??{},monthlyAlertMinor:input.monthlyAlertMinor}});await db.auditLog.create({data:{workspaceId:input.workspaceId,actorId:input.actorId,action:"AI_MODEL_PERMISSIONS_CHANGED",entityType:"WorkspaceAICredential",entityId:current.id,metadata:{provider:current.provider,enabled:input.enabled,allowedModels:input.allowedModels}}});return credentialResponse(updated);}

export async function testWorkspaceAIConnection(input:{workspaceId:string;credentialId:string;actorId:string},db:Db=prisma){const record=await (db as any).workspaceAICredential.findFirst({where:{id:input.credentialId,workspaceId:input.workspaceId,revokedAt:null}});if(!record)throw new Error("AI_PROVIDER_NOT_CONFIGURED");if(process.env.VERCEL_ENV==="preview"&&process.env.BYO_AI_PREVIEW_TESTS_ENABLED!=="true")throw new Error("AI_PREVIEW_TEST_DISABLED");const model=record.defaultModel??(Array.isArray(record.allowedModels)?record.allowedModels[0]:undefined);if(!model)throw new Error("AI_MODEL_NOT_ALLOWED");const result=await getWorkspaceAIAdapter(record.provider).test(decryptAICredential(record.encryptedSecret),model);await (db as any).workspaceAICredential.update({where:{id:record.id},data:{status:result.ok?"CONNECTED":"FAILED",lastTestedAt:new Date(),lastSucceededAt:result.ok?new Date():record.lastSucceededAt,lastSafeFailure:result.ok?null:result.safeError}});await db.auditLog.create({data:{workspaceId:input.workspaceId,actorId:input.actorId,action:result.ok?"AI_PROVIDER_CONNECTED":"AI_PROVIDER_CONNECTION_FAILED",entityType:"WorkspaceAICredential",entityId:record.id,metadata:{provider:record.provider,requestId:result.requestId,failureType:result.failureType}}});return result;}
