import { createCipheriv, createDecipheriv, randomBytes } from "node:crypto";
export type AIProviderKey = "OPENAI"|"ANTHROPIC"|"GEMINI";
export const PROVIDER_MODELS: Record<AIProviderKey, readonly string[]> = { OPENAI: ["gpt-4.1-mini", "gpt-4.1"], ANTHROPIC: ["claude-sonnet-4-20250514"], GEMINI: ["gemini-2.5-flash", "gemini-2.5-pro"] };
function encryptionKey() { const raw = process.env.AI_CREDENTIAL_ENCRYPTION_KEY; if (!raw) throw new Error("AI_CREDENTIAL_ENCRYPTION_KEY is required."); const key = Buffer.from(raw, /^[A-Za-z0-9+/]+={0,2}$/.test(raw) ? "base64" : "hex"); if (key.length !== 32) throw new Error("AI_CREDENTIAL_ENCRYPTION_KEY must encode exactly 32 bytes."); return key; }
export function encryptAICredential(secret: string) { if (!secret.trim()) throw new Error("AI credential cannot be empty."); const iv = randomBytes(12), cipher = createCipheriv("aes-256-gcm", encryptionKey(), iv); const encrypted = Buffer.concat([cipher.update(secret, "utf8"), cipher.final()]); return `v1:${iv.toString("base64url")}:${cipher.getAuthTag().toString("base64url")}:${encrypted.toString("base64url")}`; }
export function decryptAICredential(value: string) { const [version, iv, tag, body] = value.split(":"); if (version !== "v1" || !iv || !tag || !body) throw new Error("Invalid encrypted credential."); const decipher = createDecipheriv("aes-256-gcm", encryptionKey(), Buffer.from(iv, "base64url")); decipher.setAuthTag(Buffer.from(tag, "base64url")); return Buffer.concat([decipher.update(Buffer.from(body, "base64url")), decipher.final()]).toString("utf8"); }
export function maskedCredential(secret: string) { return `••••${secret.slice(-4)}`; }
export function authorizeAISelection(input: { provider: AIProviderKey; model: string; enabled: boolean; allowedModels: string[]; clientAuthorized: boolean }) { if (!input.clientAuthorized) throw new Error("AI_CLIENT_NOT_AUTHORIZED"); if (!input.enabled) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); if (!PROVIDER_MODELS[input.provider]?.includes(input.model) || !input.allowedModels.includes(input.model)) throw new Error("AI_MODEL_NOT_ALLOWED"); return { provider: input.provider, model: input.model, subscriberPaid: true }; }
export function credentialResponse(record: { id: string; provider: AIProviderKey; maskedKey: string; enabled: boolean; encryptedSecret?: string }) { return { id: record.id, provider: record.provider, maskedKey: record.maskedKey, enabled: record.enabled }; }
