/* eslint-disable @typescript-eslint/no-explicit-any */
import "server-only";
import { prisma } from "@/lib/db/prisma";
import { authorizeAISelection, credentialResponse, encryptAICredential, maskedCredential, type AIProviderKey } from "./workspace-providers";
type Db = typeof prisma;
export async function saveWorkspaceCredential(input: { workspaceId: string; actorId: string; provider: AIProviderKey; secret: string; allowedModels: string[] }, db: Db = prisma) { const encryptedSecret = encryptAICredential(input.secret), maskedKey = maskedCredential(input.secret); const record = await (db as any).workspaceAICredential.upsert({ where: { workspaceId_provider: { workspaceId: input.workspaceId, provider: input.provider } }, create: { workspaceId: input.workspaceId, provider: input.provider, encryptedSecret, maskedKey, createdById: input.actorId, allowedModels: input.allowedModels, enabled: true }, update: { encryptedSecret, maskedKey, rotatedById: input.actorId, allowedModels: input.allowedModels, enabled: true, revokedAt: null, status: "UNTESTED" } }); await db.auditLog.create({ data: { workspaceId: input.workspaceId, actorId: input.actorId, action: "AI_CREDENTIAL_ROTATED", entityType: "WorkspaceAICredential", entityId: record.id, metadata: { provider: input.provider, maskedKey } } }); return credentialResponse(record); }
export async function listWorkspaceProviders(workspaceId: string, db: Db = prisma) { const records = await (db as any).workspaceAICredential.findMany({ where: { workspaceId, revokedAt: null }, orderBy: { provider: "asc" } }); return records.map(credentialResponse); }
export async function removeWorkspaceCredential(input: { workspaceId: string; credentialId: string; actorId: string }, db: Db = prisma) { const result = await (db as any).workspaceAICredential.updateMany({ where: { id: input.credentialId, workspaceId: input.workspaceId }, data: { enabled: false, revokedAt: new Date(), encryptedSecret: "REVOKED" } }); if (result.count !== 1) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); await db.auditLog.create({ data: { workspaceId: input.workspaceId, actorId: input.actorId, action: "AI_CREDENTIAL_REMOVED", entityType: "WorkspaceAICredential", entityId: input.credentialId } }); }
export async function selectWorkspaceAI(input: { workspaceId: string; provider: AIProviderKey; model: string; clientAuthorized: boolean; feature: string; projectId?: string }, db: Db = prisma) { const credential = await (db as any).workspaceAICredential.findUnique({ where: { workspaceId_provider: { workspaceId: input.workspaceId, provider: input.provider } } }); if (!credential || credential.workspaceId !== input.workspaceId || credential.revokedAt) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); const selection = authorizeAISelection({ provider: input.provider, model: input.model, enabled: credential.enabled, allowedModels: Array.isArray(credential.allowedModels) ? credential.allowedModels : [], clientAuthorized: input.clientAuthorized }); return { ...selection, credentialId: credential.id, feature: input.feature, projectId: input.projectId };
}
export async function recordAIUsage(input: { workspaceId: string; credentialId: string; provider: AIProviderKey; model: string; feature: string; status: string; inputTokens?: number; outputTokens?: number; providerRequestId?: string }, db: Db = prisma) { const credential = await (db as any).workspaceAICredential.findFirst({ where: { id: input.credentialId, workspaceId: input.workspaceId, revokedAt: null } }); if (!credential) throw new Error("AI_PROVIDER_NOT_CONFIGURED"); return (db as any).aIProviderUsage.create({ data: { ...input, subscriberPaid: true } }); }
