"use server";
import { revalidatePath } from "next/cache";import { requireOperatorAccess } from "@/lib/admin/operator";import { prisma } from "@/lib/db/prisma";import { enqueueDurableJob } from "@/lib/jobs/service";import { addWarmupSimulationEvidence,assignWarmupPolicy,beginMailboxRecovery,cascadeDomainPause,createWarmupOverride,createWarmupPolicyDraft,publishWarmupPolicy,retireWarmupPolicy,revokeWarmupOverride,type SimulationAction,WARMUP_SIMULATION_SCENARIO } from "@/lib/sending-infrastructure/warmup-service";
const val=(f:FormData,k:string)=>String(f.get(k)??"").trim();
export async function runEvaluationAction(f:FormData){await requireOperatorAccess();const profileId=val(f,"profileId"),simulated=val(f,"simulated")==="true",date=val(f,"evaluationDate")||new Date().toISOString().slice(0,10);await enqueueDurableJob({workspaceId:val(f,"workspaceId"),jobType:"WARMUP_DAILY_EVALUATION",idempotencyKey:`warmup:${profileId}:${date}:${simulated}`,payload:{profileId,evaluationDate:`${date}T00:00:00.000Z`,isSimulated:simulated,scenarioIdentifier:simulated?WARMUP_SIMULATION_SCENARIO:undefined}});revalidatePath("/platform/mailboxes");}
export async function operatorWarmupAction(f:FormData){const operator=await requireOperatorAccess();const action=val(f,"action"),profileId=val(f,"profileId"),workspaceId=val(f,"workspaceId"),reason=val(f,"reason");if(reason.length<5)throw new Error("An explicit reason is required.");const profile=await prisma.mailboxWarmupProfile.findFirstOrThrow({where:{id:profileId,workspaceId}});if(action==="RECOVERY")await beginMailboxRecovery({workspaceId,profileId,actorId:operator.user.id,reason});else if(action==="DOMAIN_PAUSE")await cascadeDomainPause({workspaceId,domainId:profile.managedDomainId,actorId:operator.user.id,reason});else if(["PAUSED","RETIRED","WARMUP_HELD"].includes(action)){await prisma.$transaction([prisma.mailboxWarmupProfile.update({where:{id:profile.id},data:{lifecycleState:action,currentDailyLimit:0,lastDecision:`OPERATOR_${action}: ${reason}`}}),prisma.auditLog.create({data:{workspaceId,actorId:operator.user.id,action:`WARMUP_OPERATOR_${action}`,entityType:"MailboxWarmupProfile",entityId:profile.id,metadata:{reason}}})]);}else throw new Error("Unsupported operator action.");revalidatePath("/platform/mailboxes");}
export async function simulateWarmupAction(f:FormData){const operator=await requireOperatorAccess();await addWarmupSimulationEvidence({workspaceId:val(f,"workspaceId"),profileId:val(f,"profileId"),action:val(f,"simulationAction") as SimulationAction,actorId:operator.user.id});revalidatePath("/platform/mailboxes");}
export async function assignPolicyAction(f:FormData){await requireOperatorAccess();await assignWarmupPolicy({workspaceId:val(f,"workspaceId"),profileId:val(f,"profileId"),policyId:val(f,"policyId")});revalidatePath("/platform/mailboxes");}
export async function createOverrideAction(f:FormData){const operator=await requireOperatorAccess();await createWarmupOverride({workspaceId:val(f,"workspaceId"),targetType:val(f,"targetType") as "MAILBOX"|"DOMAIN",targetId:val(f,"targetId"),scope:val(f,"scope"),reason:val(f,"reason"),overrideState:"LIVE_READY",expiresAt:new Date(val(f,"expiresAt")),actorId:operator.user.id});revalidatePath("/platform/mailboxes");}
export async function revokeOverrideAction(f:FormData){const operator=await requireOperatorAccess();await revokeWarmupOverride({workspaceId:val(f,"workspaceId"),overrideId:val(f,"overrideId"),actorId:operator.user.id,reason:val(f,"reason")});revalidatePath("/platform/mailboxes");}
export async function createPolicyAction(f:FormData){const operator=await requireOperatorAccess();await createWarmupPolicyDraft({name:val(f,"name"),actorId:operator.user.id});revalidatePath("/platform/mailboxes");}
export async function publishPolicyAction(f:FormData){await requireOperatorAccess();await publishWarmupPolicy(val(f,"policyId"));revalidatePath("/platform/mailboxes");}
export async function retirePolicyAction(f:FormData){await requireOperatorAccess();await retireWarmupPolicy(val(f,"policyId"));revalidatePath("/platform/mailboxes");}
export async function requestOperationalCheckAction(f:FormData){const operator=await requireOperatorAccess();const type=val(f,"checkType"),workspaceId=val(f,"workspaceId"),profileId=val(f,"profileId");const p=await prisma.mailboxWarmupProfile.findFirstOrThrow({where:{id:profileId,workspaceId}});if(type==="DNS")await enqueueDurableJob({workspaceId,jobType:"DOMAIN_DNS_CONFIGURATION",idempotencyKey:`dns-recheck:${p.managedDomainId}:${Date.now()}`,payload:{domainId:p.managedDomainId}});else await prisma.auditLog.create({data:{workspaceId,actorId:operator.user.id,action:type,entityType:"MailboxWarmupProfile",entityId:p.id,metadata:{mailboxId:p.managedMailboxId,domainId:p.managedDomainId}}});revalidatePath("/platform/mailboxes");}
