import "./server-only";
import {afterAll,describe,expect,it} from "vitest";
import {randomUUID} from "node:crypto";
import {prisma} from "@/lib/db/prisma";
import {captureAffiliateAttribution,createAffiliateParticipant,endAffiliateMembership,lockAffiliateAttribution,resolveAffiliateCode,resumeSuspendedAffiliateMembership,startAffiliateMembership,suspendAffiliateMembership} from "@/lib/affiliates/service";
const suffix=randomUUID().replaceAll("-","").slice(0,12), userId=`affiliate-${suffix}`, ids:{participant?:string;sessions:string[];orders:string[]}={sessions:[],orders:[]};
afterAll(async()=>{await prisma.affiliateReferralAttribution.deleteMany({where:{OR:[{acquisitionSessionId:{in:ids.sessions}},{customerUserId:userId}]}});await prisma.customerOrder.deleteMany({where:{id:{in:ids.orders}}});await prisma.acquisitionSession.deleteMany({where:{id:{in:ids.sessions}}});if(ids.participant){await prisma.affiliateMembershipCode.deleteMany({where:{membershipPeriod:{participantId:ids.participant}}});await prisma.affiliateMembershipPeriod.deleteMany({where:{participantId:ids.participant}});await prisma.affiliateParticipant.delete({where:{id:ids.participant}}).catch(()=>undefined)}await prisma.$disconnect()});
describe("PostgreSQL affiliate membership periods",()=>{
 it("enforces lifecycle, attribution locking, retirement and rejoin",async()=>{const participant=await createAffiliateParticipant({email:`${suffix}@example.test`,displayName:"Lifecycle Affiliate",userId});ids.participant=participant.id;const first=await startAffiliateMembership({participantId:participant.id,code:`FIRST-${suffix}`});expect(await resolveAffiliateCode(first.code.code.toLowerCase())).toEqual({codeId:first.code.id,membershipPeriodId:first.id});await suspendAffiliateMembership(first.id);expect(await resolveAffiliateCode(first.code.code)).toBeNull();await resumeSuspendedAffiliateMembership(first.id);const session=await prisma.acquisitionSession.create({data:{anonymousId:`anon-${suffix}`,landingPage:"/start"}});ids.sessions.push(session.id);const captured=await captureAffiliateAttribution({code:first.code.code,acquisitionSessionId:session.id});expect(captured?.affiliateMembershipPeriodId).toBe(first.id);expect((await captureAffiliateAttribution({code:first.code.code,acquisitionSessionId:session.id}))?.id).toBe(captured?.id);const order=await prisma.customerOrder.create({data:{userId:`customer-${suffix}`}});ids.orders.push(order.id);const locked=await prisma.$transaction(tx=>lockAffiliateAttribution({acquisitionSessionId:session.id,orderId:order.id,customerUserId:`customer-${suffix}`},tx));expect(locked?.status).toBe("LOCKED");await endAffiliateMembership(first.id,"PROGRAM_EXIT");await expect(resumeSuspendedAffiliateMembership(first.id)).rejects.toThrow();expect(await resolveAffiliateCode(first.code.code)).toBeNull();const retired=await prisma.affiliateMembershipCode.findUniqueOrThrow({where:{id:first.code.id}});expect(retired.status).toBe("RETIRED");const second=await startAffiliateMembership({participantId:participant.id,code:`RETURN-${suffix}`});expect(second.id).not.toBe(first.id);expect(second.code.id).not.toBe(first.code.id);expect((await prisma.affiliateReferralAttribution.findUnique({where:{id:captured!.id}}))?.affiliateMembershipPeriodId).toBe(first.id)});
 it("invalidates definitive self-referrals instead of locking",async()=>{const membership=await prisma.affiliateMembershipPeriod.findFirstOrThrow({where:{participantId:ids.participant!,status:"ACTIVE"},include:{code:true}});const session=await prisma.acquisitionSession.create({data:{anonymousId:`self-${suffix}`,landingPage:"/start"}});ids.sessions.push(session.id);await captureAffiliateAttribution({code:membership.code!.code,acquisitionSessionId:session.id});const order=await prisma.customerOrder.create({data:{userId}});ids.orders.push(order.id);const result=await prisma.$transaction(tx=>lockAffiliateAttribution({acquisitionSessionId:session.id,orderId:order.id,customerUserId:userId},tx));expect(result?.status).toBe("INVALIDATED");expect(result?.invalidationReason).toBe("SELF_REFERRAL")});
});
