import "./server-only";
import {afterAll,describe,expect,it} from "vitest";
import {randomUUID} from "node:crypto";
import {prisma} from "@/lib/db/prisma";
import {captureAffiliateAttribution,reconcileAffiliateMembershipForSubscriptionStatus,resolveAffiliateCode} from "@/lib/affiliates/service";
const timeout=20_000,suffix=randomUUID().replaceAll("-","").slice(0,12),userId=`auto-affiliate-${suffix}`,subscriptionId=`subscription-${suffix}`,correlationId=`event-${suffix}`;
const sessions:string[]=[];let participantId="",firstMembershipId="",firstCodeId="",firstCode="",oldAttributionId="";
const identity={userId,email:`auto-${suffix}@example.test`,displayName:"Automatic Subscriber",subscriptionId,correlationId};
afterAll(async()=>{if(participantId){const memberships=await prisma.affiliateMembershipPeriod.findMany({where:{participantId},select:{id:true,code:{select:{id:true}}}});const entityIds=[participantId,...memberships.flatMap(m=>[m.id,...(m.code?[m.code.id]:[])])];await prisma.auditLog.deleteMany({where:{entityId:{in:entityIds}}});await prisma.affiliateReferralAttribution.deleteMany({where:{affiliateMembershipPeriodId:{in:memberships.map(m=>m.id)}}});await prisma.acquisitionSession.deleteMany({where:{id:{in:sessions}}});await prisma.affiliateMembershipCode.deleteMany({where:{membershipPeriod:{participantId}}});await prisma.affiliateMembershipPeriod.deleteMany({where:{participantId}});await prisma.affiliateParticipant.delete({where:{id:participantId}}).catch(()=>undefined)}await prisma.$disconnect()},timeout);
describe.sequential("automatic subscriber affiliate enrollment",()=>{
 it("creates one participant, membership, generated code, and system audits under concurrent activation",async()=>{const [one,two]=await Promise.all([reconcileAffiliateMembershipForSubscriptionStatus({...identity,status:"ACTIVE"}),reconcileAffiliateMembershipForSubscriptionStatus({...identity,correlationId:`${correlationId}-replay`,status:"ACTIVE"})]);expect(one).toBeTruthy();expect(two).toBeTruthy();const participant=await prisma.affiliateParticipant.findUniqueOrThrow({where:{userId},include:{memberships:{include:{code:true}}}});participantId=participant.id;expect(participant.memberships).toHaveLength(1);const membership=participant.memberships[0];firstMembershipId=membership.id;firstCodeId=membership.code!.id;firstCode=membership.code!.code;expect(firstCode).toMatch(/^QR-[A-HJ-NP-Z2-9]{8}$/);expect(await prisma.affiliateParticipant.count({where:{userId}})).toBe(1);expect(await prisma.affiliateMembershipPeriod.count({where:{participantId,status:{in:["ACTIVE","SUSPENDED"]}}})).toBe(1);expect(await prisma.auditLog.count({where:{action:"AFFILIATE_MEMBERSHIP_AUTOMATICALLY_STARTED",entityId:membership.id}})).toBe(1);expect(await prisma.auditLog.count({where:{action:"AFFILIATE_CODE_AUTOMATICALLY_GENERATED",entityId:firstCodeId}})).toBe(1)},timeout);
 it("keeps scheduled-cancellation and past-due processing idempotent without changing the code",async()=>{await reconcileAffiliateMembershipForSubscriptionStatus({...identity,correlationId:`${correlationId}-scheduled`,status:"ACTIVE"});await reconcileAffiliateMembershipForSubscriptionStatus({...identity,correlationId:`${correlationId}-pastdue`,status:"PAST_DUE"});const membership=await prisma.affiliateMembershipPeriod.findUniqueOrThrow({where:{id:firstMembershipId},include:{code:true}});expect(membership.status).toBe("ACTIVE");expect(membership.code?.code).toBe(firstCode);expect(await prisma.auditLog.count({where:{action:"AFFILIATE_MEMBERSHIP_AUTOMATICALLY_STARTED",entityId:firstMembershipId}})).toBe(1)},timeout);
 it("ends access idempotently, retires the code, and preserves historical referrals",async()=>{const session=await prisma.acquisitionSession.create({data:{anonymousId:`auto-old-${suffix}`,landingPage:"/start"}});sessions.push(session.id);const attribution=await captureAffiliateAttribution({code:firstCode,acquisitionSessionId:session.id});oldAttributionId=attribution!.id;const ended=await reconcileAffiliateMembershipForSubscriptionStatus({...identity,correlationId:`${correlationId}-ended`,status:"CANCELED"});expect(ended?.membership.status).toBe("ENDED");expect(ended?.code?.status).toBe("RETIRED");expect(await reconcileAffiliateMembershipForSubscriptionStatus({...identity,correlationId:`${correlationId}-ended-replay`,status:"CANCELED"})).toBeNull();expect(await resolveAffiliateCode(firstCode)).toBeNull();expect(await prisma.affiliateReferralAttribution.findUnique({where:{id:oldAttributionId}})).not.toBeNull();expect(await prisma.auditLog.count({where:{action:"AFFILIATE_MEMBERSHIP_AUTOMATICALLY_ENDED",entityId:firstMembershipId}})).toBe(1);expect(await prisma.auditLog.count({where:{action:"AFFILIATE_CODE_AUTOMATICALLY_RETIRED",entityId:firstCodeId}})).toBe(1)},timeout);
 it("reuses the participant but creates a new period and code on resubscription",async()=>{const result=await reconcileAffiliateMembershipForSubscriptionStatus({...identity,subscriptionId:`${subscriptionId}-new`,correlationId:`${correlationId}-resubscribed`,status:"ACTIVE"});if(!result?.code)throw new Error("Expected active resubscription membership code");expect(result.participant.id).toBe(participantId);expect(result.membership.id).not.toBe(firstMembershipId);expect(result.code.id).not.toBe(firstCodeId);expect(result.code.code).not.toBe(firstCode);expect((await prisma.affiliateMembershipCode.findUniqueOrThrow({where:{id:firstCodeId}})).status).toBe("RETIRED");expect((await prisma.affiliateReferralAttribution.findUniqueOrThrow({where:{id:oldAttributionId}})).affiliateMembershipPeriodId).toBe(firstMembershipId);const session=await prisma.acquisitionSession.create({data:{anonymousId:`auto-new-${suffix}`,landingPage:"/start"}});sessions.push(session.id);const newAttribution=await captureAffiliateAttribution({code:result.code.code,acquisitionSessionId:session.id});expect(newAttribution?.affiliateMembershipPeriodId).toBe(result.membership.id)},timeout);
});
