import { afterAll, describe, expect, it } from "vitest";import { PrismaClient } from "@prisma/client";import { acceptCommercialTerms } from "@/lib/commercial/service";
const db=new PrismaClient();const suffix=`dbtest-${Date.now()}`;const ids:{workspace?:string;user?:string;order?:string}={};
afterAll(async()=>{if(ids.workspace){await db.auditLog.deleteMany({where:{workspaceId:ids.workspace}});await db.sendingCapacityReservation.deleteMany({where:{workspaceId:ids.workspace}});await db.sendingCapacityLedger.deleteMany({where:{workspaceId:ids.workspace}});await db.mailboxWarmupProfile.deleteMany({where:{workspaceId:ids.workspace}});await db.managedMailbox.deleteMany({where:{workspaceId:ids.workspace}});await db.saasSubscription.deleteMany({where:{workspaceId:ids.workspace}});await db.workspaceMember.deleteMany({where:{workspaceId:ids.workspace}});await db.workspace.deleteMany({where:{id:ids.workspace}})}if(ids.order)await db.customerOrder.deleteMany({where:{id:ids.order}});if(ids.user)await db.userProfile.deleteMany({where:{id:ids.user}});await db.commerceProduct.deleteMany({where:{key:`TEST_LAUNCH_${suffix}`}});await db.commercialCatalogVersion.deleteMany({where:{productKey:`TEST_LAUNCH_${suffix}`}});await db.$disconnect()});
describe("PostgreSQL commercial lifecycle",()=>{it("persists immutable accepted terms and retry-safe capacity",async()=>{const user=await db.userProfile.create({data:{clerkUserId:suffix,email:`${suffix}@example.test`}});ids.user=user.id;const workspace=await db.workspace.create({data:{name:suffix,slug:suffix,ownerId:user.id,members:{create:{userId:user.id,roleKey:"WORKSPACE_OWNER"}}}});ids.workspace=workspace.id;const product=await db.commerceProduct.create({data:{key:`TEST_LAUNCH_${suffix}`,name:"Launch",category:"SENDING_PACKAGE",active:true,metadata:{version:1,slug:"launch",recurringPriceCents:29700,setupFeeCents:75000,effectiveAt:"2026-07-29T00:00:00.000Z"},entitlements:{create:[{entitlementKey:"MAILBOX_ALLOWANCE",integerValue:6},{entitlementKey:"MANAGED_DOMAIN_ALLOWANCE",integerValue:2},{entitlementKey:"MONTHLY_SEND_ALLOWANCE",integerValue:4500}]}}});const order=await db.customerOrder.create({data:{userId:user.id,workspaceId:workspace.id,status:"CHECKOUT_PENDING"}});ids.order=order.id;const accepted=await acceptCommercialTerms({orderId:order.id,productId:product.id},db);await db.commerceProduct.update({where:{id:product.id},data:{metadata:{version:2,slug:"launch",recurringPriceCents:99900,setupFeeCents:75000,effectiveAt:"2026-08-01T00:00:00.000Z"}}});const retry=await acceptCommercialTerms({orderId:order.id,productId:product.id},db);expect((accepted.acceptedCommercialTerms as any).recurringPriceCents).toBe(29700);expect(retry.acceptedCommercialTerms).toEqual(accepted.acceptedCommercialTerms);expect(await db.commercialCatalogVersion.count({where:{productKey:product.key}})).toBe(1);});});

it("repairs a partially initialized setup catalog idempotently without erasing mappings", async () => {
  const { upsertSetupProducts } = await import("@/lib/sending-infrastructure/operational");
  const keys = ["STANDARD_SETUP", "PRIORITY_SETUP"];const catalogKeys=[...keys,"EXPEDITED_SETUP"];
  const rollback = new Error("ROLLBACK_SETUP_CATALOG_TEST");
  await expect(db.$transaction(async (tx) => {
    await tx.commerceProduct.deleteMany({ where: { key: { in: catalogKeys } } });
    await tx.commerceProduct.create({ data: { key: "EXPEDITED_SETUP", name: "Obsolete", category: "SETUP_FEE", active: true, recurring: false, billingInterval: "ONE_TIME", sortOrder: 30, metadata: { priceCents: 50000 } } });await tx.commerceProduct.create({ data: { key: "PRIORITY_SETUP", name: "Existing priority", category: "SETUP_FEE", active: true, recurring: false, billingInterval: "ONE_TIME", sortOrder: 99, stripeProductId: "prod_test_preserve", stripePriceId: "price_test_preserve", metadata: { priceCents: 32100, operatorNote: "keep" } } });
    await upsertSetupProducts(tx as any);
    await upsertSetupProducts(tx as any);
    const products = await tx.commerceProduct.findMany({ where: { key: { in: keys }, category: "SETUP_FEE", active: true }, orderBy: { sortOrder: "asc" } });
    expect(products.map((p) => p.key)).toEqual(keys);
    expect(products).toHaveLength(2);
    expect(products.every((p) => !p.recurring && p.billingInterval === "ONE_TIME")).toBe(true);
    expect(await tx.commerceProduct.findUnique({where:{key:"EXPEDITED_SETUP"}})).toBeNull();expect(products.find((p) => p.key === "PRIORITY_SETUP")).toMatchObject({ stripeProductId: "prod_test_preserve", stripePriceId: "price_test_preserve", metadata: expect.objectContaining({ priceCents: 32100, operatorNote: "keep", setupPriorityProduct: true }) });
    throw rollback;
  })).rejects.toBe(rollback);
});
