/* eslint-disable @typescript-eslint/no-explicit-any */
import { prisma } from "@/lib/db/prisma";
import { generateRequiredDnsRecords } from "./dns";
export function parseDomain(domainName: string) { const clean = domainName.trim().toLowerCase(); const parts = clean.split("."); return { domainName: clean, rootDomain: parts.slice(-2).join("."), tld: parts.at(-1) || process.env.MANAGED_DOMAIN_DEFAULT_TLD || "com" }; }
export async function auditDomain(domainId: string, eventType: string, safeSummary: string, workspaceId?: string | null, actorUserId?: string | null) { return (prisma as any).domainAuditEvent.create({ data: { domainId, workspaceId, actorUserId, eventType, safeSummary } }); }
export async function createManagedDomain(input: { domainName: string; ownershipType: "QUANTUM_REACH_MANAGED"|"WORKSPACE_OWNED"|"SHARED_POOL"; workspaceId?: string; actorUserId?: string; lifecycleStatus?: string; }) { const parsed = parseDomain(input.domainName); const domain = await (prisma as any).managedDomain.create({ data: { ...parsed, ownershipType: input.ownershipType, workspaceId: input.workspaceId, lifecycleStatus: input.lifecycleStatus || "AVAILABLE", autoRenew: process.env.MANAGED_DOMAIN_AUTO_RENEW === "true", markupPercent: Number(process.env.MANAGED_DOMAIN_MARKUP_PERCENT || 0) || null } }); await auditDomain(domain.id, "created", `Managed domain ${domain.domainName} created as ${input.ownershipType}.`, input.workspaceId, input.actorUserId); return domain; }
export async function assignManagedDomain(domainId: string, workspaceId: string, assignedByUserId?: string, assignmentType: "LEASED"|"SOLD"|"INTERNAL"|"BROUGHT_BY_WORKSPACE" = "LEASED") { const domain = await (prisma as any).managedDomain.findUnique({ where: { id: domainId } }); if (!domain) throw new Error("Managed domain not found."); if (["BURNED", "RETIRED"].includes(domain.lifecycleStatus)) throw new Error("Burned or retired domains cannot be assigned."); const assignment = await (prisma as any).managedDomainAssignment.create({ data: { domainId, workspaceId, assignedByUserId, assignmentType } }); await (prisma as any).managedDomain.update({ where: { id: domainId }, data: { workspaceId, assignedAt: new Date(), assignedByUserId, lifecycleStatus: domain.lifecycleStatus === "AVAILABLE" ? "RESERVED" : domain.lifecycleStatus } }); await auditDomain(domainId, "assigned", `Domain assigned to workspace ${workspaceId}.`, workspaceId, assignedByUserId); return assignment; }
export async function transitionManagedDomain(domainId: string, lifecycleStatus: string, actorUserId?: string, override = false) { const domain = await (prisma as any).managedDomain.findUnique({ where: { id: domainId }, include: { dnsRecords: true, sesIdentity: true, warmupPlan: true } }); if (!domain) throw new Error("Managed domain not found."); if (["BURNED", "RETIRED"].includes(domain.lifecycleStatus) && lifecycleStatus === "ACTIVE") throw new Error("Burned or retired domains cannot become active."); if (lifecycleStatus === "ACTIVE" && !override && !(await isDomainSendReady(domainId)).ready) throw new Error("Domain cannot become active until DNS, SES, and warmup readiness pass or an operator override is audited."); const updated = await (prisma as any).managedDomain.update({ where: { id: domainId }, data: { lifecycleStatus } }); await auditDomain(domainId, "status_changed", `Domain status changed from ${domain.lifecycleStatus} to ${lifecycleStatus}${override ? " with operator override" : ""}.`, domain.workspaceId, actorUserId); return updated; }
export async function createRequiredDnsRecords(domainId: string, domainName: string) { const records = generateRequiredDnsRecords(domainName); return Promise.all(records.map((r) => (prisma as any).domainDnsRecord.create({ data: { domainId, ...r, status: "REQUIRED" } }))); }
export async function upsertSesIdentity(domainId: string, verificationStatus = "PENDING") { return (prisma as any).domainSesIdentity.upsert({ where: { domainId }, update: { verificationStatus, sesRegion: process.env.AWS_SES_REGION || "us-east-1", configurationSet: process.env.AWS_SES_CONFIGURATION_SET }, create: { domainId, verificationStatus, sesRegion: process.env.AWS_SES_REGION || "us-east-1", configurationSet: process.env.AWS_SES_CONFIGURATION_SET } }); }
export async function createWarmupPlan(domainId: string) { const startingDailyLimit = Number(process.env.DOMAIN_WARMUP_DEFAULT_DAILY_LIMIT || 10); const rampDays = Number(process.env.DOMAIN_WARMUP_RAMP_DAYS || 30); const maxDailyLimit = Number(process.env.DOMAIN_WARMUP_MAX_DAILY_LIMIT || 500); const plan = await (prisma as any).domainWarmupPlan.create({ data: { domainId, status: "SCHEDULED", startingDailyLimit, currentDailyLimit: startingDailyLimit, targetDailyLimit: maxDailyLimit, maxDailyLimit, rampDays, events: { create: { eventType: "CREATED", newLimit: startingDailyLimit, message: "Warmup plan created; no artificial warmup emails are sent." } } } }); return plan; }
export function nextWarmupLimit(plan: any) { const step = Math.max(1, Math.ceil((plan.targetDailyLimit - plan.startingDailyLimit) / Math.max(1, plan.rampDays))); return Math.min(plan.maxDailyLimit, plan.currentDailyLimit + step); }
export async function advanceWarmupPlan(planId: string) { const plan = await (prisma as any).domainWarmupPlan.findUnique({ where: { id: planId } }); const newLimit = nextWarmupLimit(plan); return (prisma as any).domainWarmupPlan.update({ where: { id: planId }, data: { status: newLimit >= plan.targetDailyLimit ? "COMPLETED" : "WARMING", currentDay: plan.currentDay + 1, currentDailyLimit: newLimit, lastAdvancedAt: new Date(), events: { create: { eventType: "LIMIT_INCREASED", oldLimit: plan.currentDailyLimit, newLimit } } } }); }
export function calculateHealthStatus(input: { sentCount: number; bounceCount: number; complaintCount: number }) { if (input.sentCount < 20) return "UNKNOWN"; const bounce = input.bounceCount / input.sentCount; const complaint = input.complaintCount / input.sentCount; if (complaint >= 0.01 || bounce >= 0.1) return "CRITICAL"; if (complaint >= 0.005 || bounce >= 0.05) return "DEGRADED"; if (complaint >= 0.002 || bounce >= 0.03) return "WATCH"; return "GOOD"; }
export async function createReputationSnapshot(domainId: string, counts: { sentCount: number; bounceCount: number; complaintCount: number; unsubscribeCount?: number; blockCount?: number }) { const bounceRate = counts.sentCount ? counts.bounceCount / counts.sentCount : 0; const complaintRate = counts.sentCount ? counts.complaintCount / counts.sentCount : 0; return (prisma as any).domainReputationSnapshot.create({ data: { domainId, date: new Date(), ...counts, bounceRate, complaintRate, healthStatus: calculateHealthStatus(counts) } }); }
export async function isDomainSendReady(domainId: string) { const domain = await (prisma as any).managedDomain.findUnique({ where: { id: domainId }, include: { dnsRecords: true, sesIdentity: true, warmupPlan: true, assignments: true } }); if (!domain) return { ready: false, reason: "Domain not found." }; if (!domain.workspaceId || !domain.assignments.some((a:any)=>a.workspaceId===domain.workspaceId && a.status === "ACTIVE")) return { ready: false, reason: "Domain is not actively assigned to workspace." }; if (["PAUSED", "RETIRED", "BURNED", "FAILED"].includes(domain.lifecycleStatus)) return { ready: false, reason: "Domain lifecycle status blocks sending." }; if (!domain.dnsRecords.length || domain.dnsRecords.some((r:any)=>r.status !== "VERIFIED")) return { ready: false, reason: "DNS records are not verified." }; if (!domain.sesIdentity || domain.sesIdentity.verificationStatus !== "VERIFIED") return { ready: false, reason: "AWS SES identity is not verified." }; if (!domain.warmupPlan || !["WARMING", "COMPLETED"].includes(domain.warmupPlan.status)) return { ready: false, reason: "Warmup is not started or is paused." }; return { ready: true, currentDailyLimit: domain.warmupPlan.currentDailyLimit }; }
export async function listWorkspaceDomains(workspaceId: string) { if (!process.env.DATABASE_URL) return []; return (prisma as any).managedDomain.findMany({ where: { workspaceId }, include: { dnsRecords: true, sesIdentity: true, warmupPlan: true, reputationSnapshots: { orderBy: { date: "desc" }, take: 1 } } }); }
export async function getOperatorDomainSummary() { if (!process.env.DATABASE_URL) return { total: 0, warming: 0, active: 0, pausedOrBurned: 0, unassigned: 0, needingDns: 0, needingSes: 0, purchaseRequestsPendingApproval: 0, label: "deliverability health signals" }; const [total, warming, active, blocked, unassigned, dns, ses, pending] = await Promise.all([(prisma as any).managedDomain.count(), (prisma as any).managedDomain.count({ where: { lifecycleStatus: "WARMING" } }), (prisma as any).managedDomain.count({ where: { lifecycleStatus: "ACTIVE" } }), (prisma as any).managedDomain.count({ where: { lifecycleStatus: { in: ["PAUSED", "BURNED"] } } }), (prisma as any).managedDomain.count({ where: { workspaceId: null } }), (prisma as any).managedDomain.count({ where: { dnsRecords: { some: { status: { not: "VERIFIED" } } } } }), (prisma as any).managedDomain.count({ where: { OR: [{ sesIdentity: null }, { sesIdentity: { verificationStatus: { not: "VERIFIED" } } }] } }), (prisma as any).domainPurchaseRequest.count({ where: { status: "APPROVED" } })]); return { total, warming, active, pausedOrBurned: blocked, unassigned, needingDns: dns, needingSes: ses, purchaseRequestsPendingApproval: pending, label: "deliverability health signals" }; }
