"use server";
import { revalidatePath } from "next/cache";
import { prisma } from "@/lib/db/prisma";
import { requireOperatorAccess } from "@/lib/admin/operator";
import { normalizeCouponCode, validateCouponConfiguration } from "@/lib/commercial/coupons";
const value=(f:FormData,k:string)=>String(f.get(k)??"").trim();const optionalInt=(f:FormData,k:string)=>{const raw=value(f,k);return raw?Number(raw):null};const list=(f:FormData,k:string)=>value(f,k).split(",").map(v=>v.trim()).filter(Boolean);
async function operatorContext(){const operator=await requireOperatorAccess();const membership=await prisma.workspaceMember.findFirst({where:{userId:operator.user.id},select:{workspaceId:true}});if(!membership)throw new Error("An operator workspace is required for audited coupon management.");return{operator,workspaceId:membership.workspaceId};}
export async function saveCouponAction(f:FormData){const{operator,workspaceId}=await operatorContext();const id=value(f,"id"),code=value(f,"code"),percentageOff=Number(value(f,"percentageOff")),recurringDiscountMonths=optionalInt(f,"recurringDiscountMonths"),trialDays=optionalInt(f,"trialDays"),minimumOrderAmountCents=Number(value(f,"minimumOrderAmountCents")||0);validateCouponConfiguration({code,percentageOff,recurringDiscountMonths,trialDays,minimumOrderAmountCents});const data={code,normalizedCode:normalizeCouponCode(code),displayName:value(f,"displayName"),description:value(f,"description")||null,active:value(f,"active")==="true",validFrom:value(f,"validFrom")?new Date(value(f,"validFrom")):null,expiresAt:value(f,"expiresAt")?new Date(value(f,"expiresAt")):null,percentageOff,recurringDiscountMonths,trialDays,minimumOrderAmountCents,maximumTotalRedemptions:optionalInt(f,"maximumTotalRedemptions"),maximumRedemptionsPerCustomer:optionalInt(f,"maximumRedemptionsPerCustomer"),stripeCouponId:value(f,"stripeCouponId")||null,stripePromotionCodeId:value(f,"stripePromotionCodeId")||null,eligiblePackageKeys:list(f,"eligiblePackageKeys"),eligibleProductKeys:list(f,"eligibleProductKeys"),eligibleChargeTypes:list(f,"eligibleChargeTypes")};const coupon=id?await prisma.commercialCoupon.update({where:{id},data:{...data,version:{increment:1}}}):await prisma.commercialCoupon.create({data});await prisma.auditLog.create({data:{workspaceId,actorId:operator.user.id,action:id?"COUPON_UPDATED":"COUPON_CREATED",entityType:"CommercialCoupon",entityId:coupon.id,metadata:{normalizedCode:coupon.normalizedCode,version:coupon.version}}});revalidatePath("/platform/coupons");}
export async function setCouponStateAction(f:FormData){const{operator,workspaceId}=await operatorContext();const id=value(f,"id"),action=value(f,"action");if(!["ACTIVATE","DEACTIVATE","RETIRE"].includes(action))throw new Error("Unsupported coupon action.");const coupon=await prisma.commercialCoupon.update({where:{id},data:action==="RETIRE"?{active:false,retiredAt:new Date(),version:{increment:1}}:{active:action==="ACTIVATE",version:{increment:1}}});await prisma.auditLog.create({data:{workspaceId,actorId:operator.user.id,action:`COUPON_${action}`,entityType:"CommercialCoupon",entityId:id,metadata:{normalizedCode:coupon.normalizedCode,version:coupon.version}}});revalidatePath("/platform/coupons");}
