import { prisma } from "@/lib/db/prisma";
import { requireOperatorAccess } from "@/lib/admin/operator";
import { transitionMembershipAction } from "./actions";

const control="rounded-lg border border-slate-300 bg-white px-3 py-2 text-slate-950 placeholder:text-slate-400 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:border-slate-600 dark:bg-slate-950 dark:text-slate-100";

export default async function AffiliatesPage({searchParams}:{searchParams:{affiliateError?:string;affiliateMessage?:string;q?:string}}){
  await requireOperatorAccess();
  const q=searchParams.q?.trim();
  const participants=await prisma.affiliateParticipant.findMany({
    where:q?{OR:[{email:{contains:q,mode:"insensitive"}},{displayName:{contains:q,mode:"insensitive"}},{memberships:{some:{code:{normalizedCode:{contains:q.toUpperCase()}}}}}]}:undefined,
    include:{memberships:{orderBy:{startedAt:"desc"},include:{code:true,referrals:{orderBy:{capturedAt:"desc"},take:20}}}},
    orderBy:{createdAt:"desc"},
  });
  return <main className="space-y-6">
    <header><h1 className="text-3xl font-semibold">Affiliates</h1><p className="text-slate-600 dark:text-slate-300">Manage subscriber affiliate lifecycle, eligibility, and referral history.</p></header>
    <aside className="rounded-xl border border-sky-200 bg-sky-50 p-4 text-sky-950 dark:border-sky-900 dark:bg-sky-950 dark:text-sky-100">Affiliate accounts are created automatically when customers become active subscribers. Referral codes are generated by the system.</aside>
    {searchParams.affiliateError?<p role="alert" className="rounded-lg bg-red-50 p-3 text-red-800 dark:bg-red-950 dark:text-red-200">{searchParams.affiliateError}</p>:null}
    {searchParams.affiliateMessage?<p role="status" className="rounded-lg bg-emerald-50 p-3 text-emerald-800 dark:bg-emerald-950 dark:text-emerald-200">{searchParams.affiliateMessage}</p>:null}
    <form className="flex gap-2"><label className="sr-only" htmlFor="affiliate-search">Search affiliates</label><input id="affiliate-search" className={control} name="q" placeholder="Search subscriber, email, or code" defaultValue={q}/><button className="rounded-lg bg-slate-950 px-4 py-2 text-white dark:bg-sky-600">Search</button></form>
    {participants.map(participant=><section key={participant.id} className="rounded-xl border border-slate-300 p-5 dark:border-slate-700">
      <h2 className="text-xl font-semibold">{participant.displayName}</h2><p className="text-slate-600 dark:text-slate-300">{participant.email}</p>
      <div className="mt-4 space-y-3">{participant.memberships.map(period=><article key={period.id} className="rounded-lg bg-slate-50 p-4 dark:bg-slate-900">
        <div className="flex flex-wrap justify-between gap-2"><strong>Period started {period.startedAt.toLocaleDateString()}</strong><span className="rounded-full border px-2 py-1 text-xs">{period.status}</span></div>
        <p>Generated code: <code>{period.code?.code??"Unavailable"}</code> · {period.code?.status??"—"} · {period.referrals.length} recent referrals</p>
        {period.referrals.length?<details className="mt-2"><summary className="cursor-pointer text-sm font-medium">Referral history</summary><ul className="mt-2 space-y-1 text-sm text-slate-600 dark:text-slate-300">{period.referrals.map(referral=><li key={referral.id}>{referral.status} · captured {referral.capturedAt.toLocaleDateString()}</li>)}</ul></details>:null}
        {period.status!=="ENDED"?<div className="mt-3 flex flex-wrap gap-2">{period.status==="ACTIVE"?<Action id={period.id} action="SUSPEND" label="Suspend for risk or compliance"/>:<Action id={period.id} action="RESUME" label="Resume"/>}<form action={transitionMembershipAction} className="flex flex-wrap gap-2"><input type="hidden" name="membershipId" value={period.id}/><input type="hidden" name="action" value="END"/><label className="sr-only" htmlFor={`reason-${period.id}`}>Termination reason</label><input id={`reason-${period.id}`} className={control} name="reason" placeholder="Required compliance or abuse reason" required/><label className="flex items-center gap-2 text-sm text-slate-700 dark:text-slate-200"><input type="checkbox" required/>I understand this is irreversible</label><button className="rounded-lg border border-red-500 px-3 py-2 text-red-700 dark:text-red-300">End permanently</button></form></div>:<p className="mt-2 text-sm text-slate-600 dark:text-slate-300">Ended memberships and retired codes cannot be reactivated. Resubscription creates a new period and code automatically.</p>}
      </article>)}</div>
    </section>)}
  </main>
}
function Action({id,action,label}:{id:string;action:"SUSPEND"|"RESUME";label:string}){return <form action={transitionMembershipAction}><input type="hidden" name="membershipId" value={id}/><input type="hidden" name="action" value={action}/><button className="rounded-lg border border-slate-400 px-3 py-2">{label}</button></form>}
