-- Additive Stripe provider records. Existing manual and complimentary orders remain valid.
CREATE TYPE "StripeWebhookProcessingStatus" AS ENUM ('RECEIVED', 'PROCESSING', 'PROCESSED', 'FAILED');
CREATE TYPE "StripePaymentProviderStatus" AS ENUM ('SUCCEEDED', 'FAILED', 'REFUNDED', 'DISPUTED');
ALTER TYPE "CustomerPaymentStatus" ADD VALUE IF NOT EXISTS 'DISPUTED';
ALTER TABLE "CustomerOrder" ADD COLUMN IF NOT EXISTS "stripeCustomerId" TEXT;
ALTER TABLE "CustomerOrder" ADD COLUMN IF NOT EXISTS "stripeCheckoutSessionId" TEXT;
ALTER TABLE "CustomerOrder" ADD COLUMN IF NOT EXISTS "stripePaymentIntentId" TEXT;
ALTER TABLE "CustomerOrder" ADD COLUMN IF NOT EXISTS "stripeSubscriptionId" TEXT;
ALTER TABLE "CustomerOrder" ADD COLUMN IF NOT EXISTS "refundedAmountCents" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "CustomerOrder" ADD COLUMN IF NOT EXISTS "disputedAt" TIMESTAMP(3);
CREATE UNIQUE INDEX IF NOT EXISTS "CustomerOrder_stripeCheckoutSessionId_key" ON "CustomerOrder"("stripeCheckoutSessionId");
CREATE UNIQUE INDEX IF NOT EXISTS "CustomerOrder_stripePaymentIntentId_key" ON "CustomerOrder"("stripePaymentIntentId");
CREATE INDEX IF NOT EXISTS "CustomerOrder_stripeCustomerId_idx" ON "CustomerOrder"("stripeCustomerId");
CREATE INDEX IF NOT EXISTS "CustomerOrder_stripeSubscriptionId_idx" ON "CustomerOrder"("stripeSubscriptionId");
CREATE TABLE "StripeCustomerLink" ("id" TEXT NOT NULL, "userId" TEXT NOT NULL, "stripeCustomerId" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StripeCustomerLink_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "StripeCustomerLink_userId_key" ON "StripeCustomerLink"("userId");
CREATE UNIQUE INDEX "StripeCustomerLink_stripeCustomerId_key" ON "StripeCustomerLink"("stripeCustomerId");
CREATE INDEX "StripeCustomerLink_stripeCustomerId_idx" ON "StripeCustomerLink"("stripeCustomerId");
CREATE TABLE "StripeWebhookEvent" ("id" TEXT NOT NULL, "stripeEventId" TEXT NOT NULL, "eventType" TEXT NOT NULL, "status" "StripeWebhookProcessingStatus" NOT NULL DEFAULT 'RECEIVED', "customerOrderId" TEXT, "retryCount" INTEGER NOT NULL DEFAULT 0, "safeError" TEXT, "receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "processedAt" TIMESTAMP(3), CONSTRAINT "StripeWebhookEvent_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "StripeWebhookEvent_stripeEventId_key" ON "StripeWebhookEvent"("stripeEventId");
CREATE INDEX "StripeWebhookEvent_status_receivedAt_idx" ON "StripeWebhookEvent"("status", "receivedAt");
CREATE INDEX "StripeWebhookEvent_customerOrderId_idx" ON "StripeWebhookEvent"("customerOrderId");
CREATE TABLE "StripePaymentRecord" ("id" TEXT NOT NULL, "customerOrderId" TEXT NOT NULL, "stripePaymentIntentId" TEXT, "stripeChargeId" TEXT, "stripeInvoiceId" TEXT, "stripeSubscriptionId" TEXT, "amountCents" INTEGER, "currency" TEXT DEFAULT 'usd', "status" "StripePaymentProviderStatus" NOT NULL, "paidAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StripePaymentRecord_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "StripePaymentRecord_stripePaymentIntentId_key" ON "StripePaymentRecord"("stripePaymentIntentId");
CREATE UNIQUE INDEX "StripePaymentRecord_stripeChargeId_key" ON "StripePaymentRecord"("stripeChargeId");
CREATE UNIQUE INDEX "StripePaymentRecord_stripeInvoiceId_key" ON "StripePaymentRecord"("stripeInvoiceId");
CREATE INDEX "StripePaymentRecord_customerOrderId_idx" ON "StripePaymentRecord"("customerOrderId");
CREATE INDEX "StripePaymentRecord_stripeSubscriptionId_idx" ON "StripePaymentRecord"("stripeSubscriptionId");
CREATE TABLE "StripeRefundRecord" ("id" TEXT NOT NULL, "stripeRefundId" TEXT NOT NULL, "customerOrderId" TEXT, "stripePaymentIntentId" TEXT, "amountCents" INTEGER NOT NULL, "status" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StripeRefundRecord_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "StripeRefundRecord_stripeRefundId_key" ON "StripeRefundRecord"("stripeRefundId");
CREATE INDEX "StripeRefundRecord_customerOrderId_idx" ON "StripeRefundRecord"("customerOrderId");
CREATE TABLE "StripeDisputeRecord" ("id" TEXT NOT NULL, "stripeDisputeId" TEXT NOT NULL, "customerOrderId" TEXT, "stripePaymentIntentId" TEXT, "amountCents" INTEGER, "status" TEXT NOT NULL, "reason" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "StripeDisputeRecord_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "StripeDisputeRecord_stripeDisputeId_key" ON "StripeDisputeRecord"("stripeDisputeId");
CREATE INDEX "StripeDisputeRecord_customerOrderId_idx" ON "StripeDisputeRecord"("customerOrderId");
