ALTER TYPE "WorkspaceRoleKey" ADD VALUE IF NOT EXISTS 'SALES';
ALTER TYPE "WorkspaceRoleKey" ADD VALUE IF NOT EXISTS 'CONSULTANT';
ALTER TYPE "WorkspaceRoleKey" ADD VALUE IF NOT EXISTS 'OPERATIONS';
ALTER TYPE "WorkspaceRoleKey" ADD VALUE IF NOT EXISTS 'CLIENT';
