import Link from "next/link";
import { requireOperatorAccess } from "@/lib/admin/operator";
import { getWorkspaceBootstrapDiagnostic, getWorkspaceDirectory, type WorkspaceDirectoryFilter } from "@/lib/platform/workspaces";
import { createMyWorkspaceAction } from "./actions";

const filters: WorkspaceDirectoryFilter[] = ["ALL", "ACTIVE", "SUSPENDED", "STUDENT_SUBSCRIBER", "DIRECT_CUSTOMER", "REFERRED_CLIENT_COMPANY", "INTERNAL"];
const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());

export default async function Page({ searchParams }: { searchParams?: { q?: string; filter?: string } }) {
  const { user } = await requireOperatorAccess();
  const filter = filters.includes(searchParams?.filter as WorkspaceDirectoryFilter) ? searchParams!.filter as WorkspaceDirectoryFilter : "ALL";
  const [rows, diagnostic] = await Promise.all([getWorkspaceDirectory(user.id, searchParams?.q, filter), getWorkspaceBootstrapDiagnostic(user.id)]);
  const query = searchParams?.q ?? "";
  return <main className="space-y-6"><header><h1>Workspaces</h1><p>Safe workspace operations directory. Tenant CRM, contacts, campaigns, and other tenant content are not displayed here.</p>{!diagnostic.hasMembership ? <form action={createMyWorkspaceAction} className="mt-3"><button className="rounded bg-sky-600 px-4 py-2 text-white">Create My Workspace</button></form> : null}</header>
    <form className="flex flex-wrap gap-3 rounded-xl border p-4" action="/platform/workspaces"><input name="q" defaultValue={query} placeholder="Search name, owner, email, or workspace ID" className="min-w-72 rounded border px-3 py-2"/><select name="filter" defaultValue={filter} className="rounded border px-3 py-2">{filters.map((item) => <option key={item} value={item}>{label(item)}</option>)}</select><button className="rounded bg-sky-600 px-4 py-2 text-white">Search</button></form>
    {!rows.length ? <section className="rounded-xl border p-5"><h2>{query || filter !== "ALL" ? "No workspaces match this directory search." : "No workspaces exist yet."}</h2>{!query && filter === "ALL" ? <><p className="mt-2 text-sm">Authenticated user ID: {user.id}. Active workspace membership: {diagnostic.hasMembership ? "Yes" : "No"}. SaaS workspace provisioning: {diagnostic.hasProvisioning ? "Yes" : "No"}.</p>{!diagnostic.hasMembership ? <p className="mt-2 text-sm">No persisted workspace membership exists for this operator. Dashboard access requires a real Workspace and membership; no demo workspace fallback is used.</p> : null}</> : null}</section> : <section className="overflow-x-auto rounded-xl border"><table className="w-full text-left text-sm"><thead><tr className="border-b"><th className="p-3">Workspace</th><th className="p-3">Owner</th><th className="p-3">Type</th><th className="p-3">Core</th><th className="p-3">Sending Package</th><th className="p-3">Agency</th><th className="p-3">Users</th><th className="p-3">Status</th><th className="p-3">Created</th><th className="p-3">Actions</th></tr></thead><tbody>{rows.map((row) => { const core = row.items.find((item) => item.commerceProduct.key === "QUANTUM_REACH_CORE"); const sending = row.items.find((item) => item.commerceProduct.key === "GROWTH_SENDER_PACKAGE"); const agency = row.items.find((item) => item.commerceProduct.key === "AGENCY_WHITE_LABEL_UPGRADE"); const state = row.suspended ? "Suspended" : row.provisioning && row.provisioning.status !== "READY" && row.provisioning.status !== "FAILED" ? "Provisioning" : !row.profile ? "Needs setup" : "Active"; return <tr key={row.workspace.id} className="border-b"><td className="p-3"><Link className="font-medium text-sky-700 underline" href={`/platform/workspaces/${row.workspace.id}`}>{row.workspace.name}</Link><div className="text-xs text-slate-500">{row.workspace.id}</div>{row.isMine ? <span className="text-xs font-medium text-sky-700">My Workspace</span> : null}</td><td className="p-3">{row.owner ? <>{[row.owner.firstName, row.owner.lastName].filter(Boolean).join(" ") || "Unavailable"}<div className="text-xs text-slate-500">{row.owner.email}</div></> : "Unavailable"}</td><td className="p-3">{label(row.type)}</td><td className="p-3">{core ? "Active" : "Unavailable"}</td><td className="p-3">{sending?.commerceProduct.name ?? "Unavailable"}</td><td className="p-3">{agency ? "Active" : "Unavailable"}</td><td className="p-3">{row.userCount}</td><td className="p-3"><span className="rounded bg-slate-100 px-2 py-1">{state}</span><div className="text-xs text-slate-500">{row.provisioning?.status ?? "Unavailable"}</div></td><td className="p-3">{row.workspace.createdAt.toLocaleDateString()}</td><td className="p-3"><Link className="text-sky-700 underline" href={`/platform/workspaces/${row.workspace.id}`}>Open Workspace</Link></td></tr>; })}</tbody></table></section>}</main>;
}
