-- Additive prospect-to-subscriber journey schema. Prisma-managed SQL generated from prisma/schema.prisma.
CREATE TYPE "CourseDeliveryType" AS ENUM ('SKOOL','SELF_HOSTED','EXTERNAL','MANUAL');
CREATE TYPE "ProgramEnrollmentStatus" AS ENUM ('PENDING','ACTIVE','PAUSED','CANCELED','COMPLETED','MANUAL_REVIEW');
CREATE TYPE "CustomerOrderStatus" AS ENUM ('DRAFT','CHECKOUT_PENDING','PAID','PARTIALLY_FULFILLED','FULFILLED','CANCELED','REFUNDED','FAILED');
CREATE TYPE "CustomerPaymentStatus" AS ENUM ('UNPAID','PENDING','PAID','PARTIALLY_REFUNDED','REFUNDED','FAILED');
CREATE TYPE "SetupPriority" AS ENUM ('STANDARD','PRIORITY','EXPEDITED','MANUAL_HOLD');
CREATE TYPE "InfrastructureOrderStatus" AS ENUM ('PENDING','QUEUED','IN_PROGRESS','WAITING_ON_CUSTOMER','WAITING_ON_PROVIDER','READY','FAILED','CANCELED');
CREATE TYPE "SetupTaskStatus" AS ENUM ('PENDING','IN_PROGRESS','COMPLETED','BLOCKED','WAIVED');
CREATE TYPE "NotificationIntentStatus" AS ENUM ('PENDING','SENT','FAILED','SKIPPED');
CREATE TABLE "AcquisitionSession" ("id" TEXT PRIMARY KEY, "anonymousId" TEXT UNIQUE, "userId" TEXT, "source" TEXT, "medium" TEXT, "campaign" TEXT, "content" TEXT, "term" TEXT, "landingPage" TEXT NOT NULL, "affiliateAttributionId" TEXT, "clickedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "metadata" JSONB NOT NULL DEFAULT '{}');
CREATE TABLE "ProgramOffer" ("id" TEXT PRIMARY KEY, "key" TEXT UNIQUE NOT NULL, "name" TEXT NOT NULL, "description" TEXT, "active" BOOLEAN NOT NULL DEFAULT true, "courseDeliveryType" "CourseDeliveryType" NOT NULL DEFAULT 'SKOOL', "externalGroupRef" TEXT, "commerceProductId" TEXT, "includedSoftwareProductKey" TEXT, "includedSetupPriority" "SetupPriority" NOT NULL DEFAULT 'STANDARD', "metadata" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "ProgramEnrollment" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "programOfferId" TEXT NOT NULL, "status" "ProgramEnrollmentStatus" NOT NULL DEFAULT 'PENDING', "source" TEXT NOT NULL DEFAULT 'MANUAL', "externalProvider" TEXT, "externalMembershipId" TEXT, "enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "activatedAt" TIMESTAMP(3), "canceledAt" TIMESTAMP(3), "metadata" JSONB NOT NULL DEFAULT '{}', UNIQUE("userId","programOfferId"));
CREATE TABLE "CustomerOrder" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "workspaceId" TEXT, "programEnrollmentId" TEXT, "acquisitionSessionId" TEXT, "affiliateAttributionId" TEXT, "status" "CustomerOrderStatus" NOT NULL DEFAULT 'DRAFT', "paymentStatus" "CustomerPaymentStatus" NOT NULL DEFAULT 'UNPAID', "paymentMethod" TEXT NOT NULL DEFAULT 'MANUAL', "setupPriority" "SetupPriority" NOT NULL DEFAULT 'STANDARD', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CustomerOrderItem" ("id" TEXT PRIMARY KEY, "orderId" TEXT NOT NULL REFERENCES "CustomerOrder"("id") ON DELETE CASCADE, "commerceProductId" TEXT, "itemType" TEXT NOT NULL, "quantity" INTEGER NOT NULL DEFAULT 1, "fulfillmentStatus" TEXT NOT NULL DEFAULT 'PENDING', "metadata" JSONB NOT NULL DEFAULT '{}');
CREATE TABLE "InfrastructureOrder" ("id" TEXT PRIMARY KEY, "customerOrderId" TEXT UNIQUE NOT NULL REFERENCES "CustomerOrder"("id") ON DELETE CASCADE, "workspaceId" TEXT, "selectedProductKey" TEXT NOT NULL, "priority" "SetupPriority" NOT NULL DEFAULT 'STANDARD', "status" "InfrastructureOrderStatus" NOT NULL DEFAULT 'PENDING', "currentStage" TEXT NOT NULL DEFAULT 'Infrastructure package selected', "assignedOperatorId" TEXT, "blockedReason" TEXT, "customerActionRequired" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CustomerSetupTask" ("id" TEXT PRIMARY KEY, "infrastructureOrderId" TEXT NOT NULL REFERENCES "InfrastructureOrder"("id") ON DELETE CASCADE, "workspaceId" TEXT, "taskType" TEXT NOT NULL, "title" TEXT NOT NULL, "status" "SetupTaskStatus" NOT NULL DEFAULT 'PENDING', "required" BOOLEAN NOT NULL DEFAULT true, "dueAt" TIMESTAMP(3), "completedAt" TIMESTAMP(3));
CREATE TABLE "OperatorSetupTask" ("id" TEXT PRIMARY KEY, "infrastructureOrderId" TEXT NOT NULL REFERENCES "InfrastructureOrder"("id") ON DELETE CASCADE, "assignedOperatorId" TEXT, "taskType" TEXT NOT NULL, "title" TEXT NOT NULL, "notes" TEXT, "status" "SetupTaskStatus" NOT NULL DEFAULT 'PENDING', "priority" "SetupPriority" NOT NULL DEFAULT 'STANDARD', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "CustomerNotificationIntent" ("id" TEXT PRIMARY KEY, "userId" TEXT NOT NULL, "customerOrderId" TEXT, "recipient" TEXT NOT NULL, "templateKey" TEXT NOT NULL, "status" "NotificationIntentStatus" NOT NULL DEFAULT 'PENDING', "providerMessageId" TEXT, "sentAt" TIMESTAMP(3), "metadata" JSONB NOT NULL DEFAULT '{}', "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX "InfrastructureOrder_priority_status_createdAt_idx" ON "InfrastructureOrder"("priority","status","createdAt");
